// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_supplier_receipts.sql

package inventorydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSupplierReceipt = `-- name: CancelSupplierReceipt :execrows
UPDATE inventory_supplier_receipts
SET status = 'canceled', canceled_at = clock_timestamp(), updated_at = clock_timestamp()
WHERE id = $1 AND status = 'expected'
`

func (q *Queries) CancelSupplierReceipt(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSupplierReceipt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countExpectedSupplierReceipts = `-- name: CountExpectedSupplierReceipts :one
SELECT COUNT(*) FROM inventory_supplier_receipts
WHERE inventory_item_id = $1 AND status = 'expected'
`

// CountExpectedSupplierReceipts is the item deletion's count, read under the
// item's exclusive lock, which recording waits on.
func (q *Queries) CountExpectedSupplierReceipts(ctx context.Context, inventoryItemID string) (int64, error) {
	row := q.db.QueryRow(ctx, countExpectedSupplierReceipts, inventoryItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpectedSupplierReceiptsAtLocation = `-- name: CountExpectedSupplierReceiptsAtLocation :one
SELECT COUNT(*) FROM inventory_supplier_receipts
WHERE location_id = $1 AND status = 'expected'
`

// CountExpectedSupplierReceiptsAtLocation is the close's count, read under the
// location's exclusive lock, which recording waits on.
func (q *Queries) CountExpectedSupplierReceiptsAtLocation(ctx context.Context, locationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countExpectedSupplierReceiptsAtLocation, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSupplierReceipts = `-- name: CountSupplierReceipts :one
SELECT COUNT(*) FROM inventory_supplier_receipts
WHERE inventory_item_id = $1::text
  AND ($2::text IS NULL OR status = $2::text)
`

type CountSupplierReceiptsParams struct {
	InventoryItemID string
	Status          *string
}

func (q *Queries) CountSupplierReceipts(ctx context.Context, arg CountSupplierReceiptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSupplierReceipts, arg.InventoryItemID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupplierReceipt = `-- name: CreateSupplierReceipt :one

INSERT INTO inventory_supplier_receipts (
    id, inventory_item_id, location_id, quantity, expected_at, reference
) VALUES (
    $1::text, $2::text, $3::text,
    $4::bigint, $5::timestamptz, $6::text
)
RETURNING id, inventory_item_id, location_id, quantity, expected_at, reference, status, received_quantity, received_at, canceled_at, created_at, updated_at
`

type CreateSupplierReceiptParams struct {
	ID              string
	InventoryItemID string
	LocationID      string
	Quantity        int64
	ExpectedAt      pgtype.Timestamptz
	Reference       *string
}

// inventory_supplier_receipts queries (ADR 0399).
//
// A receipt is recorded by an operator, closed by receiving it — which writes the
// counted units through the ledger — or by cancelling it, and never deleted. A
// status leaves 'expected' once, so every write here is guarded by it.
func (q *Queries) CreateSupplierReceipt(ctx context.Context, arg CreateSupplierReceiptParams) (InventorySupplierReceipt, error) {
	row := q.db.QueryRow(ctx, createSupplierReceipt,
		arg.ID,
		arg.InventoryItemID,
		arg.LocationID,
		arg.Quantity,
		arg.ExpectedAt,
		arg.Reference,
	)
	var i InventorySupplierReceipt
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.LocationID,
		&i.Quantity,
		&i.ExpectedAt,
		&i.Reference,
		&i.Status,
		&i.ReceivedQuantity,
		&i.ReceivedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expectedSupplierReceiptsOfItems = `-- name: ExpectedSupplierReceiptsOfItems :many
SELECT id, inventory_item_id, location_id, quantity, expected_at, reference, status, received_quantity, received_at, canceled_at, created_at, updated_at FROM inventory_supplier_receipts
WHERE inventory_item_id = ANY ($1::text[])
  AND status = 'expected' AND expected_at > now()
ORDER BY inventory_item_id, expected_at, id
`

// ExpectedSupplierReceiptsOfItems is the forecast's read: the items' receipts
// still expected and not yet due, in the order they are expected. A receipt
// whose moment has passed is left out, so the forecast errs late.
func (q *Queries) ExpectedSupplierReceiptsOfItems(ctx context.Context, itemIds []string) ([]InventorySupplierReceipt, error) {
	rows, err := q.db.Query(ctx, expectedSupplierReceiptsOfItems, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventorySupplierReceipt{}
	for rows.Next() {
		var i InventorySupplierReceipt
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.LocationID,
			&i.Quantity,
			&i.ExpectedAt,
			&i.Reference,
			&i.Status,
			&i.ReceivedQuantity,
			&i.ReceivedAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierReceipt = `-- name: GetSupplierReceipt :one
SELECT id, inventory_item_id, location_id, quantity, expected_at, reference, status, received_quantity, received_at, canceled_at, created_at, updated_at FROM inventory_supplier_receipts WHERE id = $1
`

func (q *Queries) GetSupplierReceipt(ctx context.Context, id string) (InventorySupplierReceipt, error) {
	row := q.db.QueryRow(ctx, getSupplierReceipt, id)
	var i InventorySupplierReceipt
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.LocationID,
		&i.Quantity,
		&i.ExpectedAt,
		&i.Reference,
		&i.Status,
		&i.ReceivedQuantity,
		&i.ReceivedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSupplierReceipts = `-- name: ListSupplierReceipts :many
SELECT id, inventory_item_id, location_id, quantity, expected_at, reference, status, received_quantity, received_at, canceled_at, created_at, updated_at FROM inventory_supplier_receipts
WHERE inventory_item_id = $1::text
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY expected_at, id
LIMIT $4::bigint OFFSET $3::bigint
`

type ListSupplierReceiptsParams struct {
	InventoryItemID string
	Status          *string
	RowOffset       int64
	RowLimit        int64
}

// ListSupplierReceipts pages one item's receipts by expected moment, every
// status or one.
func (q *Queries) ListSupplierReceipts(ctx context.Context, arg ListSupplierReceiptsParams) ([]InventorySupplierReceipt, error) {
	rows, err := q.db.Query(ctx, listSupplierReceipts,
		arg.InventoryItemID,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventorySupplierReceipt{}
	for rows.Next() {
		var i InventorySupplierReceipt
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.LocationID,
			&i.Quantity,
			&i.ExpectedAt,
			&i.Reference,
			&i.Status,
			&i.ReceivedQuantity,
			&i.ReceivedAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSupplierReceipt = `-- name: LockSupplierReceipt :one
SELECT id, inventory_item_id, location_id, quantity, expected_at, reference, status, received_quantity, received_at, canceled_at, created_at, updated_at FROM inventory_supplier_receipts WHERE id = $1 FOR UPDATE
`

// LockSupplierReceipt locks the receipt for a receive or a cancel; it comes
// after the level in the lock order.
func (q *Queries) LockSupplierReceipt(ctx context.Context, id string) (InventorySupplierReceipt, error) {
	row := q.db.QueryRow(ctx, lockSupplierReceipt, id)
	var i InventorySupplierReceipt
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.LocationID,
		&i.Quantity,
		&i.ExpectedAt,
		&i.Reference,
		&i.Status,
		&i.ReceivedQuantity,
		&i.ReceivedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const receiveSupplierReceipt = `-- name: ReceiveSupplierReceipt :execrows
UPDATE inventory_supplier_receipts r
SET status = 'received', received_quantity = m.delta, received_at = m.created_at,
    updated_at = m.created_at
FROM inventory_movements m
WHERE r.id = $1::text AND r.status = 'expected'
  AND m.reason = 'supplier_receipt' AND m.reference = r.id
`

// ReceiveSupplierReceipt closes an expected receipt with the count and the
// moment of the supplier_receipt movement that names it, so the record and the
// ledger cannot disagree. No such movement, or a receipt no longer expected,
// changes nothing.
func (q *Queries) ReceiveSupplierReceipt(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, receiveSupplierReceipt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const waitingBackordersOfItems = `-- name: WaitingBackordersOfItems :many
SELECT id, inventory_item_id, order_id, order_line_item_id, quantity, withdrawn_quantity, location_ids, status, reservation_id, filled_location_id, seq, created_at, updated_at FROM inventory_backorders
WHERE inventory_item_id = ANY ($1::text[]) AND status = 'waiting'
ORDER BY inventory_item_id, seq
`

// WaitingBackordersOfItems is the forecast's view of the queue ADR 0392 fills:
// the items' waiting claims in queue order, unlocked.
func (q *Queries) WaitingBackordersOfItems(ctx context.Context, itemIds []string) ([]InventoryBackorder, error) {
	rows, err := q.db.Query(ctx, waitingBackordersOfItems, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryBackorder{}
	for rows.Next() {
		var i InventoryBackorder
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.OrderID,
			&i.OrderLineItemID,
			&i.Quantity,
			&i.WithdrawnQuantity,
			&i.LocationIds,
			&i.Status,
			&i.ReservationID,
			&i.FilledLocationID,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
