// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_levels.sql

package inventorydb

import (
	"context"
)

const availableByItemAndLocation = `-- name: AvailableByItemAndLocation :many
SELECT inventory_item_id,
       location_id,
       (stocked_quantity - reserved_quantity)::bigint AS available_quantity
FROM inventory_levels
WHERE inventory_item_id = ANY ($1::text[])
  AND deleted_at IS NULL
  AND stocked_quantity > reserved_quantity
`

type AvailableByItemAndLocationRow struct {
	InventoryItemID   string
	LocationID        string
	AvailableQuantity int64
}

// AvailableByItemAndLocation returns the sellable quantity of each item BROKEN
// DOWN by location, in one round trip.
//
// # Why the breakdown and not a filtered sum
//
// The caller that needs it is a storefront read going through the Query layer
// (ADR 0004), and an expansion carries no filter: the provider is handed ids
// and field names and nothing else, so it cannot be told WHICH locations the
// caller may count. It therefore answers with all of them and the caller sums
// the ones its sales channel ships from.
//
// A location with nothing sellable is left out rather than reported as a zero,
// for AvailableQuantityByItemIDs' reason: the query returns rows, not a census.
func (q *Queries) AvailableByItemAndLocation(ctx context.Context, ids []string) ([]AvailableByItemAndLocationRow, error) {
	rows, err := q.db.Query(ctx, availableByItemAndLocation, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailableByItemAndLocationRow{}
	for rows.Next() {
		var i AvailableByItemAndLocationRow
		if err := rows.Scan(&i.InventoryItemID, &i.LocationID, &i.AvailableQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const availableQuantityByItemIDs = `-- name: AvailableQuantityByItemIDs :many
SELECT inventory_item_id,
       COALESCE(SUM(stocked_quantity - reserved_quantity), 0)::bigint AS available_quantity
FROM inventory_levels
WHERE inventory_item_id = ANY ($1::text[]) AND deleted_at IS NULL
GROUP BY inventory_item_id
`

type AvailableQuantityByItemIDsRow struct {
	InventoryItemID   string
	AvailableQuantity int64
}

// AvailableQuantityByItemIDs returns, per item, the available total over ALL
// locations in one round trip; the Query provider uses it.
// For an item that has no level at all NO ROW comes back; the caller counts it
// as zero.
func (q *Queries) AvailableQuantityByItemIDs(ctx context.Context, ids []string) ([]AvailableQuantityByItemIDsRow, error) {
	rows, err := q.db.Query(ctx, availableQuantityByItemIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailableQuantityByItemIDsRow{}
	for rows.Next() {
		var i AvailableQuantityByItemIDsRow
		if err := rows.Scan(&i.InventoryItemID, &i.AvailableQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createInventoryLevel = `-- name: CreateInventoryLevel :one
INSERT INTO inventory_levels (
    id, inventory_item_id, location_id, stocked_quantity, reserved_quantity
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, inventory_item_id, location_id, stocked_quantity, reserved_quantity, created_at, updated_at, deleted_at
`

type CreateInventoryLevelParams struct {
	ID               string
	InventoryItemID  string
	LocationID       string
	StockedQuantity  int64
	ReservedQuantity int64
}

func (q *Queries) CreateInventoryLevel(ctx context.Context, arg CreateInventoryLevelParams) (InventoryLevel, error) {
	row := q.db.QueryRow(ctx, createInventoryLevel,
		arg.ID,
		arg.InventoryItemID,
		arg.LocationID,
		arg.StockedQuantity,
		arg.ReservedQuantity,
	)
	var i InventoryLevel
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.LocationID,
		&i.StockedQuantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInventoryLevels = `-- name: ListInventoryLevels :many
SELECT id, inventory_item_id, location_id, stocked_quantity, reserved_quantity, created_at, updated_at, deleted_at FROM inventory_levels
WHERE inventory_item_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListInventoryLevels(ctx context.Context, inventoryItemID string) ([]InventoryLevel, error) {
	rows, err := q.db.Query(ctx, listInventoryLevels, inventoryItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryLevel{}
	for rows.Next() {
		var i InventoryLevel
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.LocationID,
			&i.StockedQuantity,
			&i.ReservedQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInventoryLevel = `-- name: LockInventoryLevel :one

SELECT id, inventory_item_id, location_id, stocked_quantity, reserved_quantity, created_at, updated_at, deleted_at FROM inventory_levels
WHERE inventory_item_id = $1 AND location_id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type LockInventoryLevelParams struct {
	InventoryItemID string
	LocationID      string
}

// inventory_levels queries.
//
// The available quantity is read from a STORED column in no query here; it is
// derived everywhere as stocked_quantity - reserved_quantity.
// LockInventoryLevel locks the level row for the duration of the transaction.
//
// THIS IS THE BASIS OF THE CONCURRENCY. Two concurrent reservations are obliged
// to lock the same row; the second waits until the first one's transaction ends
// and, under READ COMMITTED, sees the CURRENT version of the row. That is why a
// "read first, then write" race cannot arise: the read is already made after
// the lock.
func (q *Queries) LockInventoryLevel(ctx context.Context, arg LockInventoryLevelParams) (InventoryLevel, error) {
	row := q.db.QueryRow(ctx, lockInventoryLevel, arg.InventoryItemID, arg.LocationID)
	var i InventoryLevel
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.LocationID,
		&i.StockedQuantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteInventoryLevelsByItem = `-- name: SoftDeleteInventoryLevelsByItem :exec
UPDATE inventory_levels
SET deleted_at = now(), updated_at = now()
WHERE inventory_item_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteInventoryLevelsByItem(ctx context.Context, inventoryItemID string) error {
	_, err := q.db.Exec(ctx, softDeleteInventoryLevelsByItem, inventoryItemID)
	return err
}

const stockHeldAtLocation = `-- name: StockHeldAtLocation :one
SELECT COALESCE(SUM(stocked_quantity), 0)::bigint  AS stocked_quantity,
       COALESCE(SUM(reserved_quantity), 0)::bigint AS reserved_quantity
FROM inventory_levels
WHERE location_id = $1 AND deleted_at IS NULL
`

type StockHeldAtLocationRow struct {
	StockedQuantity  int64
	ReservedQuantity int64
}

// StockHeldAtLocation returns what a location still holds: the physical total
// and the promised part of it, over its LIVING levels.
//
// It is what the close reads (ADR 0055). Two numbers rather than one, because
// they send the operator to two different places: units that are merely stocked
// have to be moved or written down, and units that are reserved are promised to
// a sale that has to finish or be released first.
//
// Soft-deleted levels are excluded, and that is not a copy of the other reads'
// filter. A deleted level is not stock: no read sums it, availability does not
// see it, and no path brings it back — it is the residue of a deleted item, and
// counting it would make a location impossible to close for stock that cannot
// be sold, moved or written down.
func (q *Queries) StockHeldAtLocation(ctx context.Context, locationID string) (StockHeldAtLocationRow, error) {
	row := q.db.QueryRow(ctx, stockHeldAtLocation, locationID)
	var i StockHeldAtLocationRow
	err := row.Scan(&i.StockedQuantity, &i.ReservedQuantity)
	return i, err
}

const updateInventoryLevelQuantities = `-- name: UpdateInventoryLevelQuantities :one
UPDATE inventory_levels
SET stocked_quantity = $2, reserved_quantity = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, inventory_item_id, location_id, stocked_quantity, reserved_quantity, created_at, updated_at, deleted_at
`

type UpdateInventoryLevelQuantitiesParams struct {
	ID               string
	StockedQuantity  int64
	ReservedQuantity int64
}

func (q *Queries) UpdateInventoryLevelQuantities(ctx context.Context, arg UpdateInventoryLevelQuantitiesParams) (InventoryLevel, error) {
	row := q.db.QueryRow(ctx, updateInventoryLevelQuantities, arg.ID, arg.StockedQuantity, arg.ReservedQuantity)
	var i InventoryLevel
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.LocationID,
		&i.StockedQuantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
