// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_levels.sql

package inventorydb

import (
	"context"
)

const availableQuantityByItemIDs = `-- name: AvailableQuantityByItemIDs :many
SELECT inventory_item_id,
       COALESCE(SUM(stocked_quantity - reserved_quantity), 0)::bigint AS available_quantity
FROM inventory_levels
WHERE inventory_item_id = ANY ($1::text[]) AND deleted_at IS NULL
GROUP BY inventory_item_id
`

type AvailableQuantityByItemIDsRow struct {
	InventoryItemID   string
	AvailableQuantity int64
}

// AvailableQuantityByItemIDs returns, per item, the available total over ALL
// locations in one round trip; the Query provider uses it.
// For an item that has no level at all NO ROW comes back; the caller counts it
// as zero.
func (q *Queries) AvailableQuantityByItemIDs(ctx context.Context, ids []string) ([]AvailableQuantityByItemIDsRow, error) {
	rows, err := q.db.Query(ctx, availableQuantityByItemIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailableQuantityByItemIDsRow{}
	for rows.Next() {
		var i AvailableQuantityByItemIDsRow
		if err := rows.Scan(&i.InventoryItemID, &i.AvailableQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createInventoryLevel = `-- name: CreateInventoryLevel :one
INSERT INTO inventory_levels (
    id, inventory_item_id, location_id, stocked_quantity, reserved_quantity
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, inventory_item_id, location_id, stocked_quantity, reserved_quantity, created_at, updated_at, deleted_at
`

type CreateInventoryLevelParams struct {
	ID               string
	InventoryItemID  string
	LocationID       string
	StockedQuantity  int64
	ReservedQuantity int64
}

func (q *Queries) CreateInventoryLevel(ctx context.Context, arg CreateInventoryLevelParams) (InventoryLevel, error) {
	row := q.db.QueryRow(ctx, createInventoryLevel,
		arg.ID,
		arg.InventoryItemID,
		arg.LocationID,
		arg.StockedQuantity,
		arg.ReservedQuantity,
	)
	var i InventoryLevel
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.LocationID,
		&i.StockedQuantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInventoryLevels = `-- name: ListInventoryLevels :many
SELECT id, inventory_item_id, location_id, stocked_quantity, reserved_quantity, created_at, updated_at, deleted_at FROM inventory_levels
WHERE inventory_item_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListInventoryLevels(ctx context.Context, inventoryItemID string) ([]InventoryLevel, error) {
	rows, err := q.db.Query(ctx, listInventoryLevels, inventoryItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryLevel{}
	for rows.Next() {
		var i InventoryLevel
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.LocationID,
			&i.StockedQuantity,
			&i.ReservedQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInventoryLevel = `-- name: LockInventoryLevel :one

SELECT id, inventory_item_id, location_id, stocked_quantity, reserved_quantity, created_at, updated_at, deleted_at FROM inventory_levels
WHERE inventory_item_id = $1 AND location_id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type LockInventoryLevelParams struct {
	InventoryItemID string
	LocationID      string
}

// inventory_levels queries.
//
// The available quantity is read from a STORED column in no query here; it is
// derived everywhere as stocked_quantity - reserved_quantity.
// LockInventoryLevel locks the level row for the duration of the transaction.
//
// THIS IS THE BASIS OF THE CONCURRENCY. Two concurrent reservations are obliged
// to lock the same row; the second waits until the first one's transaction ends
// and, under READ COMMITTED, sees the CURRENT version of the row. That is why a
// "read first, then write" race cannot arise: the read is already made after
// the lock.
func (q *Queries) LockInventoryLevel(ctx context.Context, arg LockInventoryLevelParams) (InventoryLevel, error) {
	row := q.db.QueryRow(ctx, lockInventoryLevel, arg.InventoryItemID, arg.LocationID)
	var i InventoryLevel
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.LocationID,
		&i.StockedQuantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteInventoryLevelsByItem = `-- name: SoftDeleteInventoryLevelsByItem :exec
UPDATE inventory_levels
SET deleted_at = now(), updated_at = now()
WHERE inventory_item_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteInventoryLevelsByItem(ctx context.Context, inventoryItemID string) error {
	_, err := q.db.Exec(ctx, softDeleteInventoryLevelsByItem, inventoryItemID)
	return err
}

const updateInventoryLevelQuantities = `-- name: UpdateInventoryLevelQuantities :one
UPDATE inventory_levels
SET stocked_quantity = $2, reserved_quantity = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, inventory_item_id, location_id, stocked_quantity, reserved_quantity, created_at, updated_at, deleted_at
`

type UpdateInventoryLevelQuantitiesParams struct {
	ID               string
	StockedQuantity  int64
	ReservedQuantity int64
}

func (q *Queries) UpdateInventoryLevelQuantities(ctx context.Context, arg UpdateInventoryLevelQuantitiesParams) (InventoryLevel, error) {
	row := q.db.QueryRow(ctx, updateInventoryLevelQuantities, arg.ID, arg.StockedQuantity, arg.ReservedQuantity)
	var i InventoryLevel
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.LocationID,
		&i.StockedQuantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
