// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_backorders.sql

package inventorydb

import (
	"context"
)

const countBackorders = `-- name: CountBackorders :one
SELECT COUNT(*) FROM inventory_backorders
WHERE inventory_item_id = $1::text
  AND ($2::text IS NULL OR status = $2::text)
`

type CountBackordersParams struct {
	InventoryItemID string
	Status          *string
}

func (q *Queries) CountBackorders(ctx context.Context, arg CountBackordersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBackorders, arg.InventoryItemID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWaitingBackorders = `-- name: CountWaitingBackorders :one
SELECT COUNT(*) FROM inventory_backorders
WHERE inventory_item_id = $1 AND status = 'waiting'
`

func (q *Queries) CountWaitingBackorders(ctx context.Context, inventoryItemID string) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitingBackorders, inventoryItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBackorder = `-- name: CreateBackorder :one

INSERT INTO inventory_backorders (
    id, inventory_item_id, order_id, order_line_item_id, quantity, location_ids
) VALUES ($1, $2, $3, $4, $5, $6::text[])
ON CONFLICT (order_line_item_id, inventory_item_id) DO NOTHING
RETURNING id, inventory_item_id, order_id, order_line_item_id, quantity, withdrawn_quantity, location_ids, status, reservation_id, filled_location_id, seq, created_at, updated_at
`

type CreateBackorderParams struct {
	ID              string
	InventoryItemID string
	OrderID         string
	OrderLineItemID string
	Quantity        int64
	LocationIds     []string
}

// inventory_backorders queries (ADR 0392).
//
// A claim is written by the checkout, filled by a write that makes units
// sellable, and withdrawn by a write-off. It is never deleted: the row is what a
// filled line's write-off reads to find the shelf its units left.
// CreateBackorder records a claim, or nothing when the line already has one for
// the item: a recovery that runs the checkout's last step again reads the first.
func (q *Queries) CreateBackorder(ctx context.Context, arg CreateBackorderParams) (InventoryBackorder, error) {
	row := q.db.QueryRow(ctx, createBackorder,
		arg.ID,
		arg.InventoryItemID,
		arg.OrderID,
		arg.OrderLineItemID,
		arg.Quantity,
		arg.LocationIds,
	)
	var i InventoryBackorder
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.OrderID,
		&i.OrderLineItemID,
		&i.Quantity,
		&i.WithdrawnQuantity,
		&i.LocationIds,
		&i.Status,
		&i.ReservationID,
		&i.FilledLocationID,
		&i.Seq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fillBackorder = `-- name: FillBackorder :execrows
UPDATE inventory_backorders
SET status = 'filled', reservation_id = $1::text,
    filled_location_id = $2::text, updated_at = now()
WHERE id = $3::text AND status = 'waiting'
`

type FillBackorderParams struct {
	ReservationID string
	LocationID    string
	ID            string
}

// FillBackorder marks a waiting claim filled by the reservation at the location.
func (q *Queries) FillBackorder(ctx context.Context, arg FillBackorderParams) (int64, error) {
	result, err := q.db.Exec(ctx, fillBackorder, arg.ReservationID, arg.LocationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBackorderOfLine = `-- name: GetBackorderOfLine :one
SELECT id, inventory_item_id, order_id, order_line_item_id, quantity, withdrawn_quantity, location_ids, status, reservation_id, filled_location_id, seq, created_at, updated_at FROM inventory_backorders
WHERE order_line_item_id = $1 AND inventory_item_id = $2
`

type GetBackorderOfLineParams struct {
	OrderLineItemID string
	InventoryItemID string
}

func (q *Queries) GetBackorderOfLine(ctx context.Context, arg GetBackorderOfLineParams) (InventoryBackorder, error) {
	row := q.db.QueryRow(ctx, getBackorderOfLine, arg.OrderLineItemID, arg.InventoryItemID)
	var i InventoryBackorder
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.OrderID,
		&i.OrderLineItemID,
		&i.Quantity,
		&i.WithdrawnQuantity,
		&i.LocationIds,
		&i.Status,
		&i.ReservationID,
		&i.FilledLocationID,
		&i.Seq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBackorders = `-- name: ListBackorders :many
SELECT id, inventory_item_id, order_id, order_line_item_id, quantity, withdrawn_quantity, location_ids, status, reservation_id, filled_location_id, seq, created_at, updated_at FROM inventory_backorders
WHERE inventory_item_id = $1::text
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY seq
LIMIT $4::bigint OFFSET $3::bigint
`

type ListBackordersParams struct {
	InventoryItemID string
	Status          *string
	RowOffset       int64
	RowLimit        int64
}

// ListBackorders pages one item's claims in queue order, every status or one.
func (q *Queries) ListBackorders(ctx context.Context, arg ListBackordersParams) ([]InventoryBackorder, error) {
	rows, err := q.db.Query(ctx, listBackorders,
		arg.InventoryItemID,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryBackorder{}
	for rows.Next() {
		var i InventoryBackorder
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.OrderID,
			&i.OrderLineItemID,
			&i.Quantity,
			&i.WithdrawnQuantity,
			&i.LocationIds,
			&i.Status,
			&i.ReservationID,
			&i.FilledLocationID,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBackordersOfLine = `-- name: LockBackordersOfLine :many
SELECT id, inventory_item_id, order_id, order_line_item_id, quantity, withdrawn_quantity, location_ids, status, reservation_id, filled_location_id, seq, created_at, updated_at FROM inventory_backorders
WHERE order_line_item_id = $1
ORDER BY seq
FOR UPDATE
`

// LockBackordersOfLine locks one line's claims, in queue order, for a
// settlement.
func (q *Queries) LockBackordersOfLine(ctx context.Context, orderLineItemID string) ([]InventoryBackorder, error) {
	rows, err := q.db.Query(ctx, lockBackordersOfLine, orderLineItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryBackorder{}
	for rows.Next() {
		var i InventoryBackorder
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.OrderID,
			&i.OrderLineItemID,
			&i.Quantity,
			&i.WithdrawnQuantity,
			&i.LocationIds,
			&i.Status,
			&i.ReservationID,
			&i.FilledLocationID,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWaitingBackordersAt = `-- name: LockWaitingBackordersAt :many
SELECT id, inventory_item_id, order_id, order_line_item_id, quantity, withdrawn_quantity, location_ids, status, reservation_id, filled_location_id, seq, created_at, updated_at FROM inventory_backorders
WHERE inventory_item_id = $1::text
  AND status = 'waiting'
  AND $2::text = ANY (location_ids)
  AND quantity - withdrawn_quantity <= $3::bigint
ORDER BY seq
FOR UPDATE
`

type LockWaitingBackordersAtParams struct {
	InventoryItemID string
	LocationID      string
	Available       int64
}

// LockWaitingBackordersAt locks the claims a fill at one level can complete: the
// item's waiting claims that name the location and owe no more than is sellable
// there, in queue order.
//
// Rows are locked in seq order, so two fills cannot deadlock on them, and under
// READ COMMITTED a row that changed while this waited is checked against the
// predicate again. The fit predicate keeps a fill from locking claims it cannot
// complete, so a large claim does not hold up a settlement of its line.
func (q *Queries) LockWaitingBackordersAt(ctx context.Context, arg LockWaitingBackordersAtParams) ([]InventoryBackorder, error) {
	rows, err := q.db.Query(ctx, lockWaitingBackordersAt, arg.InventoryItemID, arg.LocationID, arg.Available)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryBackorder{}
	for rows.Next() {
		var i InventoryBackorder
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.OrderID,
			&i.OrderLineItemID,
			&i.Quantity,
			&i.WithdrawnQuantity,
			&i.LocationIds,
			&i.Status,
			&i.ReservationID,
			&i.FilledLocationID,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawBackorder = `-- name: WithdrawBackorder :one
UPDATE inventory_backorders
SET withdrawn_quantity = $1::bigint,
    status = $2::text, updated_at = now()
WHERE id = $3::text
RETURNING id, inventory_item_id, order_id, order_line_item_id, quantity, withdrawn_quantity, location_ids, status, reservation_id, filled_location_id, seq, created_at, updated_at
`

type WithdrawBackorderParams struct {
	WithdrawnQuantity int64
	Status            string
	ID                string
}

// WithdrawBackorder writes how many of a waiting claim's units the order will no
// longer take.
func (q *Queries) WithdrawBackorder(ctx context.Context, arg WithdrawBackorderParams) (InventoryBackorder, error) {
	row := q.db.QueryRow(ctx, withdrawBackorder, arg.WithdrawnQuantity, arg.Status, arg.ID)
	var i InventoryBackorder
	err := row.Scan(
		&i.ID,
		&i.InventoryItemID,
		&i.OrderID,
		&i.OrderLineItemID,
		&i.Quantity,
		&i.WithdrawnQuantity,
		&i.LocationIds,
		&i.Status,
		&i.ReservationID,
		&i.FilledLocationID,
		&i.Seq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
