// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package inventorydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryBackorder struct {
	ID                string
	InventoryItemID   string
	OrderID           string
	OrderLineItemID   string
	Quantity          int64
	WithdrawnQuantity int64
	LocationIds       []string
	Status            string
	ReservationID     *string
	FilledLocationID  *string
	Seq               *int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type InventoryItem struct {
	ID               string
	Sku              string
	Title            *string
	Description      *string
	RequiresShipping bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type InventoryLevel struct {
	ID               string
	InventoryItemID  string
	LocationID       string
	StockedQuantity  int64
	ReservedQuantity int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type InventoryMovement struct {
	ID              string
	InventoryItemID string
	LocationID      string
	ReservationID   *string
	Reason          string
	Delta           int64
	StockedAfter    int64
	CreatedAt       pgtype.Timestamptz
	Reference       *string
	LineItemID      *string
}

type InventoryReservation struct {
	ID              string
	InventoryItemID string
	LocationID      string
	Quantity        int64
	LineItemID      *string
	Status          string
	Description     *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Purpose         string
}

type InventorySupplierReceipt struct {
	ID               string
	InventoryItemID  string
	LocationID       string
	Quantity         int64
	ExpectedAt       pgtype.Timestamptz
	Reference        *string
	Status           string
	ReceivedQuantity *int64
	ReceivedAt       pgtype.Timestamptz
	CanceledAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type StockLocation struct {
	ID          string
	Name        string
	Address1    *string
	Address2    *string
	City        *string
	Province    *string
	PostalCode  *string
	CountryCode *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ClosedAt    pgtype.Timestamptz
}
