-- region modülünün TOHUM (seed) verisi: para birimleri ve ISO 3166-1 ülkeleri.
--
-- Neden ayrı bir migration: şema ile referans verisi ayrı sürümlerdir. Tohum
-- 000001'in içine yazılsaydı, veriyi güncellemek şemayı da geri almayı
-- gerektirirdi; ayrı dosya, tohumun tek başına geri alınabilmesini korur
-- (plan Bölüm 8: her migration geri alınabilir olmalıdır).
--
-- Neden migration ile: currency ve country REFERANS VERİDİR. Her kurulumun
-- 249 ülkeyi elle girmesi beklenemez ve bir kurulumda eksik kalan ülke,
-- ResolveRegionForCountry'nin o ülkede sessizce çalışmaması demektir.
--
-- ON CONFLICT DO NOTHING tohumu yeniden çalıştırılabilir kılar: operatörün
-- düzelttiği bir ad ya da sembol EZİLMEZ.

-- Para birimleri (ISO 4217).
--
-- decimal_digits ISO 4217'nin minor unit tanımıdır ve listede bilinçli olarak
-- üç ayrı sınıf vardır: 0 basamaklı (JPY, KRW, CLP, ISK, VND), 2 basamaklı
-- (çoğunluk) ve 3 basamaklı (KWD, BHD, JOD, OMR, TND). Sabit bir 100 çarpanı
-- varsayan bir sunum katmanı bu üç sınıfın ikisinde yanlış tutar gösterir.
INSERT INTO currency (code, symbol, name, decimal_digits) VALUES
    ('AED', 'د.إ', 'UAE Dirham', 2),
    ('AUD', '$', 'Australian Dollar', 2),
    ('BHD', '.د.ب', 'Bahraini Dinar', 3),
    ('BRL', 'R$', 'Brazilian Real', 2),
    ('CAD', '$', 'Canadian Dollar', 2),
    ('CHF', 'CHF', 'Swiss Franc', 2),
    ('CLP', '$', 'Chilean Peso', 0),
    ('CNY', '¥', 'Yuan Renminbi', 2),
    ('CZK', 'Kč', 'Czech Koruna', 2),
    ('DKK', 'kr', 'Danish Krone', 2),
    ('EUR', '€', 'Euro', 2),
    ('GBP', '£', 'Pound Sterling', 2),
    ('HUF', 'Ft', 'Forint', 2),
    ('IDR', 'Rp', 'Rupiah', 2),
    ('ILS', '₪', 'New Israeli Sheqel', 2),
    ('INR', '₹', 'Indian Rupee', 2),
    ('ISK', 'kr', 'Iceland Krona', 0),
    ('JOD', 'د.ا', 'Jordanian Dinar', 3),
    ('JPY', '¥', 'Yen', 0),
    ('KRW', '₩', 'Won', 0),
    ('KWD', 'د.ك', 'Kuwaiti Dinar', 3),
    ('MXN', '$', 'Mexican Peso', 2),
    ('MYR', 'RM', 'Malaysian Ringgit', 2),
    ('NOK', 'kr', 'Norwegian Krone', 2),
    ('NZD', '$', 'New Zealand Dollar', 2),
    ('OMR', 'ر.ع.', 'Rial Omani', 3),
    ('PLN', 'zł', 'Zloty', 2),
    ('QAR', 'ر.ق', 'Qatari Rial', 2),
    ('RON', 'lei', 'Romanian Leu', 2),
    ('RUB', '₽', 'Russian Ruble', 2),
    ('SAR', 'ر.س', 'Saudi Riyal', 2),
    ('SEK', 'kr', 'Swedish Krona', 2),
    ('SGD', '$', 'Singapore Dollar', 2),
    ('THB', '฿', 'Baht', 2),
    ('TND', 'د.ت', 'Tunisian Dinar', 3),
    ('TRY', '₺', 'Turkish Lira', 2),
    ('TWD', 'NT$', 'New Taiwan Dollar', 2),
    ('UAH', '₴', 'Hryvnia', 2),
    ('USD', '$', 'US Dollar', 2),
    ('VND', '₫', 'Dong', 0),
    ('ZAR', 'R', 'Rand', 2)
ON CONFLICT (code) DO NOTHING;

-- Ülkeler (ISO 3166-1 alpha-2, resmî İngilizce kısa adlarıyla).
--
-- Adlar ÇEVRİLMEZ: burası referans veridir ve yerelleştirme vitrinin işidir.
-- Ülkeler bölgesiz (region_id NULL) yüklenir; bölgeye atama bir yönetim
-- kararıdır ve servis üzerinden yapılır.
INSERT INTO country (iso_2, name) VALUES
    ('AD', 'Andorra'),
    ('AE', 'United Arab Emirates'),
    ('AF', 'Afghanistan'),
    ('AG', 'Antigua and Barbuda'),
    ('AI', 'Anguilla'),
    ('AL', 'Albania'),
    ('AM', 'Armenia'),
    ('AO', 'Angola'),
    ('AQ', 'Antarctica'),
    ('AR', 'Argentina'),
    ('AS', 'American Samoa'),
    ('AT', 'Austria'),
    ('AU', 'Australia'),
    ('AW', 'Aruba'),
    ('AX', 'Åland Islands'),
    ('AZ', 'Azerbaijan'),
    ('BA', 'Bosnia and Herzegovina'),
    ('BB', 'Barbados'),
    ('BD', 'Bangladesh'),
    ('BE', 'Belgium'),
    ('BF', 'Burkina Faso'),
    ('BG', 'Bulgaria'),
    ('BH', 'Bahrain'),
    ('BI', 'Burundi'),
    ('BJ', 'Benin'),
    ('BL', 'Saint Barthélemy'),
    ('BM', 'Bermuda'),
    ('BN', 'Brunei Darussalam'),
    ('BO', 'Bolivia (Plurinational State of)'),
    ('BQ', 'Bonaire, Sint Eustatius and Saba'),
    ('BR', 'Brazil'),
    ('BS', 'Bahamas'),
    ('BT', 'Bhutan'),
    ('BV', 'Bouvet Island'),
    ('BW', 'Botswana'),
    ('BY', 'Belarus'),
    ('BZ', 'Belize'),
    ('CA', 'Canada'),
    ('CC', 'Cocos (Keeling) Islands'),
    ('CD', 'Congo, Democratic Republic of the'),
    ('CF', 'Central African Republic'),
    ('CG', 'Congo'),
    ('CH', 'Switzerland'),
    ('CI', 'Côte d''Ivoire'),
    ('CK', 'Cook Islands'),
    ('CL', 'Chile'),
    ('CM', 'Cameroon'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('CR', 'Costa Rica'),
    ('CU', 'Cuba'),
    ('CV', 'Cabo Verde'),
    ('CW', 'Curaçao'),
    ('CX', 'Christmas Island'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czechia'),
    ('DE', 'Germany'),
    ('DJ', 'Djibouti'),
    ('DK', 'Denmark'),
    ('DM', 'Dominica'),
    ('DO', 'Dominican Republic'),
    ('DZ', 'Algeria'),
    ('EC', 'Ecuador'),
    ('EE', 'Estonia'),
    ('EG', 'Egypt'),
    ('EH', 'Western Sahara'),
    ('ER', 'Eritrea'),
    ('ES', 'Spain'),
    ('ET', 'Ethiopia'),
    ('FI', 'Finland'),
    ('FJ', 'Fiji'),
    ('FK', 'Falkland Islands (Malvinas)'),
    ('FM', 'Micronesia (Federated States of)'),
    ('FO', 'Faroe Islands'),
    ('FR', 'France'),
    ('GA', 'Gabon'),
    ('GB', 'United Kingdom of Great Britain and Northern Ireland'),
    ('GD', 'Grenada'),
    ('GE', 'Georgia'),
    ('GF', 'French Guiana'),
    ('GG', 'Guernsey'),
    ('GH', 'Ghana'),
    ('GI', 'Gibraltar'),
    ('GL', 'Greenland'),
    ('GM', 'Gambia'),
    ('GN', 'Guinea'),
    ('GP', 'Guadeloupe'),
    ('GQ', 'Equatorial Guinea'),
    ('GR', 'Greece'),
    ('GS', 'South Georgia and the South Sandwich Islands'),
    ('GT', 'Guatemala'),
    ('GU', 'Guam'),
    ('GW', 'Guinea-Bissau'),
    ('GY', 'Guyana'),
    ('HK', 'Hong Kong'),
    ('HM', 'Heard Island and McDonald Islands'),
    ('HN', 'Honduras'),
    ('HR', 'Croatia'),
    ('HT', 'Haiti'),
    ('HU', 'Hungary'),
    ('ID', 'Indonesia'),
    ('IE', 'Ireland'),
    ('IL', 'Israel'),
    ('IM', 'Isle of Man'),
    ('IN', 'India'),
    ('IO', 'British Indian Ocean Territory'),
    ('IQ', 'Iraq'),
    ('IR', 'Iran (Islamic Republic of)'),
    ('IS', 'Iceland'),
    ('IT', 'Italy'),
    ('JE', 'Jersey'),
    ('JM', 'Jamaica'),
    ('JO', 'Jordan'),
    ('JP', 'Japan'),
    ('KE', 'Kenya'),
    ('KG', 'Kyrgyzstan'),
    ('KH', 'Cambodia'),
    ('KI', 'Kiribati'),
    ('KM', 'Comoros'),
    ('KN', 'Saint Kitts and Nevis'),
    ('KP', 'Korea (Democratic People''s Republic of)'),
    ('KR', 'Korea, Republic of'),
    ('KW', 'Kuwait'),
    ('KY', 'Cayman Islands'),
    ('KZ', 'Kazakhstan'),
    ('LA', 'Lao People''s Democratic Republic'),
    ('LB', 'Lebanon'),
    ('LC', 'Saint Lucia'),
    ('LI', 'Liechtenstein'),
    ('LK', 'Sri Lanka'),
    ('LR', 'Liberia'),
    ('LS', 'Lesotho'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('LV', 'Latvia'),
    ('LY', 'Libya'),
    ('MA', 'Morocco'),
    ('MC', 'Monaco'),
    ('MD', 'Moldova, Republic of'),
    ('ME', 'Montenegro'),
    ('MF', 'Saint Martin (French part)'),
    ('MG', 'Madagascar'),
    ('MH', 'Marshall Islands'),
    ('MK', 'North Macedonia'),
    ('ML', 'Mali'),
    ('MM', 'Myanmar'),
    ('MN', 'Mongolia'),
    ('MO', 'Macao'),
    ('MP', 'Northern Mariana Islands'),
    ('MQ', 'Martinique'),
    ('MR', 'Mauritania'),
    ('MS', 'Montserrat'),
    ('MT', 'Malta'),
    ('MU', 'Mauritius'),
    ('MV', 'Maldives'),
    ('MW', 'Malawi'),
    ('MX', 'Mexico'),
    ('MY', 'Malaysia'),
    ('MZ', 'Mozambique'),
    ('NA', 'Namibia'),
    ('NC', 'New Caledonia'),
    ('NE', 'Niger'),
    ('NF', 'Norfolk Island'),
    ('NG', 'Nigeria'),
    ('NI', 'Nicaragua'),
    ('NL', 'Netherlands'),
    ('NO', 'Norway'),
    ('NP', 'Nepal'),
    ('NR', 'Nauru'),
    ('NU', 'Niue'),
    ('NZ', 'New Zealand'),
    ('OM', 'Oman'),
    ('PA', 'Panama'),
    ('PE', 'Peru'),
    ('PF', 'French Polynesia'),
    ('PG', 'Papua New Guinea'),
    ('PH', 'Philippines'),
    ('PK', 'Pakistan'),
    ('PL', 'Poland'),
    ('PM', 'Saint Pierre and Miquelon'),
    ('PN', 'Pitcairn'),
    ('PR', 'Puerto Rico'),
    ('PS', 'Palestine, State of'),
    ('PT', 'Portugal'),
    ('PW', 'Palau'),
    ('PY', 'Paraguay'),
    ('QA', 'Qatar'),
    ('RE', 'Réunion'),
    ('RO', 'Romania'),
    ('RS', 'Serbia'),
    ('RU', 'Russian Federation'),
    ('RW', 'Rwanda'),
    ('SA', 'Saudi Arabia'),
    ('SB', 'Solomon Islands'),
    ('SC', 'Seychelles'),
    ('SD', 'Sudan'),
    ('SE', 'Sweden'),
    ('SG', 'Singapore'),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
    ('SI', 'Slovenia'),
    ('SJ', 'Svalbard and Jan Mayen'),
    ('SK', 'Slovakia'),
    ('SL', 'Sierra Leone'),
    ('SM', 'San Marino'),
    ('SN', 'Senegal'),
    ('SO', 'Somalia'),
    ('SR', 'Suriname'),
    ('SS', 'South Sudan'),
    ('ST', 'Sao Tome and Principe'),
    ('SV', 'El Salvador'),
    ('SX', 'Sint Maarten (Dutch part)'),
    ('SY', 'Syrian Arab Republic'),
    ('SZ', 'Eswatini'),
    ('TC', 'Turks and Caicos Islands'),
    ('TD', 'Chad'),
    ('TF', 'French Southern Territories'),
    ('TG', 'Togo'),
    ('TH', 'Thailand'),
    ('TJ', 'Tajikistan'),
    ('TK', 'Tokelau'),
    ('TL', 'Timor-Leste'),
    ('TM', 'Turkmenistan'),
    ('TN', 'Tunisia'),
    ('TO', 'Tonga'),
    ('TR', 'Türkiye'),
    ('TT', 'Trinidad and Tobago'),
    ('TV', 'Tuvalu'),
    ('TW', 'Taiwan, Province of China'),
    ('TZ', 'Tanzania, United Republic of'),
    ('UA', 'Ukraine'),
    ('UG', 'Uganda'),
    ('UM', 'United States Minor Outlying Islands'),
    ('US', 'United States of America'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistan'),
    ('VA', 'Holy See'),
    ('VC', 'Saint Vincent and the Grenadines'),
    ('VE', 'Venezuela (Bolivarian Republic of)'),
    ('VG', 'Virgin Islands (British)'),
    ('VI', 'Virgin Islands (U.S.)'),
    ('VN', 'Viet Nam'),
    ('VU', 'Vanuatu'),
    ('WF', 'Wallis and Futuna'),
    ('WS', 'Samoa'),
    ('YE', 'Yemen'),
    ('YT', 'Mayotte'),
    ('ZA', 'South Africa'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe')
ON CONFLICT (iso_2) DO NOTHING;
