// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipping_option_revise.sql

package fulfillmentdb

import (
	"context"
)

const reviseShippingOption = `-- name: ReviseShippingOption :one
UPDATE shipping_options
SET name       = $1::text,
    amount     = $2::bigint,
    admin_only = $3::boolean,
    updated_at = now()
WHERE id = $4
  AND deleted_at IS NULL
  AND name = $5::text
  AND amount = $6::bigint
  AND admin_only = $7::boolean
RETURNING id, name, provider_id, shipping_profile_id, price_type, amount, currency_code, region_id, is_return, admin_only, data, metadata, created_at, updated_at, deleted_at
`

type ReviseShippingOptionParams struct {
	Name          string
	Amount        int64
	AdminOnly     bool
	ID            string
	ReadName      string
	ReadAmount    int64
	ReadAdminOnly bool
}

// ReviseShippingOption writes the option's name, fee and storefront
// visibility only while they are still the ones the caller read (ADR 0333):
// one conditional UPDATE, so a revision made meanwhile is never written over.
//
// The provider, the profile, the price type, the region and the provider's
// configuration are not among them. A calculated option takes no fee of its
// own: shipping_options_calculated_zero refuses one, and the repository tells
// the operator so in the words it tells a new option's.
func (q *Queries) ReviseShippingOption(ctx context.Context, arg ReviseShippingOptionParams) (ShippingOption, error) {
	row := q.db.QueryRow(ctx, reviseShippingOption,
		arg.Name,
		arg.Amount,
		arg.AdminOnly,
		arg.ID,
		arg.ReadName,
		arg.ReadAmount,
		arg.ReadAdminOnly,
	)
	var i ShippingOption
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderID,
		&i.ShippingProfileID,
		&i.PriceType,
		&i.Amount,
		&i.CurrencyCode,
		&i.RegionID,
		&i.IsReturn,
		&i.AdminOnly,
		&i.Data,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
