// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipping_locations.sql

package fulfillmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countShippingLocations = `-- name: CountShippingLocations :one
SELECT COUNT(*) FROM shipping_locations
`

// CountShippingLocations ListShippingLocations ile AYNI kümeyi sayar; ikisi
// birlikte değişmek zorundadır.
func (q *Queries) CountShippingLocations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countShippingLocations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteShippingLocation = `-- name: DeleteShippingLocation :execrows
DELETE FROM shipping_locations
WHERE location_id = $1
`

// DeleteShippingLocation politikayı KALICI olarak siler; bölge bağları
// ON DELETE CASCADE ile birlikte düşer.
//
// Silmenin anlamı "depoyu kapat" DEĞİL, "depoyu varsayılana döndür"dür:
// politikası olmayan depo varsayılan öncelikte ve tüm bölgelere hizmet ediyor
// sayılır.
func (q *Queries) DeleteShippingLocation(ctx context.Context, locationID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShippingLocation, locationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteShippingLocationRegions = `-- name: DeleteShippingLocationRegions :exec
DELETE FROM shipping_location_regions
WHERE location_id = $1
`

// ReplaceShippingLocationRegions bir deponun bölge bağlarını TOPTAN yazar:
// önce hepsi silinir, sonra verilenler yazılır. Çağıran ikisini AYNI işlemde
// çağırmalıdır, yoksa arada kalan bir okuma depoyu bölgesiz (yani tüm
// bölgelere açık) görürdü.
func (q *Queries) DeleteShippingLocationRegions(ctx context.Context, locationID string) error {
	_, err := q.db.Exec(ctx, deleteShippingLocationRegions, locationID)
	return err
}

const getShippingLocation = `-- name: GetShippingLocation :one
SELECT
    l.location_id,
    l.priority,
    l.created_at,
    l.updated_at,
    COALESCE(
        array_agg(r.region_id ORDER BY r.region_id) FILTER (WHERE r.region_id IS NOT NULL),
        '{}'
    )::text[] AS region_ids
FROM shipping_locations l
LEFT JOIN shipping_location_regions r ON r.location_id = l.location_id
WHERE l.location_id = $1
GROUP BY l.location_id, l.priority, l.created_at, l.updated_at
`

type GetShippingLocationRow struct {
	LocationID string
	Priority   int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	RegionIds  []string
}

// GetShippingLocation politikayı BÖLGELERİYLE BİRLİKTE tek deyimde döner.
//
// İki ayrı SELECT ile okumak (önce satır, sonra bağlar) yırtık bir kayıt
// üretirdi: işlem dışında yapılan iki okuma iki ayrı anlık görüntüden gelir ve
// aralarına giren bir yazma, deponun YENİ önceliğiyle ESKİ bölgelerini yan yana
// gösterirdi. Yazma yolu bunu işlemle kapatıyor; okuma yolu tek deyimle
// kapatır. Kalıp ShippingLocationPolicies'in aynısıdır.
func (q *Queries) GetShippingLocation(ctx context.Context, locationID string) (GetShippingLocationRow, error) {
	row := q.db.QueryRow(ctx, getShippingLocation, locationID)
	var i GetShippingLocationRow
	err := row.Scan(
		&i.LocationID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegionIds,
	)
	return i, err
}

const insertShippingLocationRegions = `-- name: InsertShippingLocationRegions :exec
INSERT INTO shipping_location_regions (location_id, region_id)
SELECT $1::text, region
FROM unnest($2::text[]) AS region
ON CONFLICT (location_id, region_id) DO NOTHING
`

type InsertShippingLocationRegionsParams struct {
	LocationID string
	RegionIds  []string
}

// InsertShippingLocationRegions bölge bağlarını TEK deyimde yazar; bölge başına
// INSERT yapılmaz. Yinelenen bir bölge kimliği sessizce yutulur (ON CONFLICT
// DO NOTHING) çünkü "aynı bölgeyi iki kez bağlamak" ifade edilmek istenen şeyle
// aynı sonucu verir ve çağıranı bir çakışma hatasıyla karşılamak yanıltıcı
// olurdu.
func (q *Queries) InsertShippingLocationRegions(ctx context.Context, arg InsertShippingLocationRegionsParams) error {
	_, err := q.db.Exec(ctx, insertShippingLocationRegions, arg.LocationID, arg.RegionIds)
	return err
}

const listShippingLocations = `-- name: ListShippingLocations :many
SELECT
    l.location_id,
    l.priority,
    l.created_at,
    l.updated_at,
    COALESCE(
        array_agg(r.region_id ORDER BY r.region_id) FILTER (WHERE r.region_id IS NOT NULL),
        '{}'
    )::text[] AS region_ids
FROM shipping_locations l
LEFT JOIN shipping_location_regions r ON r.location_id = l.location_id
GROUP BY l.location_id, l.priority, l.created_at, l.updated_at
ORDER BY l.priority, l.location_id
LIMIT $2::bigint OFFSET $1::bigint
`

type ListShippingLocationsParams struct {
	RowOffset int64
	RowLimit  int64
}

type ListShippingLocationsRow struct {
	LocationID string
	Priority   int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	RegionIds  []string
}

// ListShippingLocations politikaları bağlarıyla birlikte sayfalar.
//
// Bağlar burada da AYNI deyimde toplanır; sayfadaki depo başına ikinci bir
// sorgu (N+1) yapılmaz ve tekil okumayla aynı yırtılma kapısı kapalı kalır.
func (q *Queries) ListShippingLocations(ctx context.Context, arg ListShippingLocationsParams) ([]ListShippingLocationsRow, error) {
	rows, err := q.db.Query(ctx, listShippingLocations, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShippingLocationsRow{}
	for rows.Next() {
		var i ListShippingLocationsRow
		if err := rows.Scan(
			&i.LocationID,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegionIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shippingLocationPolicies = `-- name: ShippingLocationPolicies :many
SELECT
    l.location_id,
    l.priority,
    COALESCE(
        array_agg(r.region_id ORDER BY r.region_id) FILTER (WHERE r.region_id IS NOT NULL),
        '{}'
    )::text[] AS region_ids
FROM shipping_locations l
LEFT JOIN shipping_location_regions r ON r.location_id = l.location_id
WHERE l.location_id = ANY ($1::text[])
GROUP BY l.location_id, l.priority
ORDER BY l.location_id
`

type ShippingLocationPoliciesRow struct {
	LocationID string
	Priority   int64
	RegionIds  []string
}

// ShippingLocationPolicies aday depoların kararı etkileyen olgularını TEK
// turda döner; aday başına sorgu (N+1) yapılmaz.
//
// Dönen satır YALNIZCA politikası olan depolar içindir. Listede olmayan aday
// "politikasız"dır ve varsayılan sayılır (öncelik 0, tüm bölgelere hizmet
// eder); bu ayrımı çağıran yapar, sorgu değil.
//
// Bölge bağları SAYI ya da BAYRAK olarak değil, KİMLİK DİZİSİ olarak döner ve
// bu bilinçlidir. İki sebebi var: kural ("bağı olmayan tüm bölgelere hizmet
// eder, olan yalnızca bağlılarına") saf bir fonksiyonda, veritabanı olmadan
// sınanabilir kalır; ve tüm adaylar elendiğinde hata mesajı depoların GERÇEKTE
// hangi bölgelere bağlı olduğunu yazabilir. İkincisi bir konfor değil,
// teşhisin tek yoludur: silinip yeniden açılmış bir bölgenin kimliği hiçbir
// yerde eşleşmez ve bayrak dönen bir sorguyla operatör yalnızca "hizmet eden
// depo yok" görürdü.
//
// FILTER, bağı olmayan depo için '{}' üretir; onsuz LEFT JOIN tek elemanı NULL
// olan bir dizi döndürür ve "bağı yok" ile "bağı NULL" ayırt edilemezdi.
func (q *Queries) ShippingLocationPolicies(ctx context.Context, locationIds []string) ([]ShippingLocationPoliciesRow, error) {
	rows, err := q.db.Query(ctx, shippingLocationPolicies, locationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingLocationPoliciesRow{}
	for rows.Next() {
		var i ShippingLocationPoliciesRow
		if err := rows.Scan(&i.LocationID, &i.Priority, &i.RegionIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertShippingLocation = `-- name: UpsertShippingLocation :one

INSERT INTO shipping_locations (location_id, priority)
VALUES ($1, $2)
ON CONFLICT (location_id) DO UPDATE
    SET priority = EXCLUDED.priority, updated_at = now()
RETURNING location_id, priority, created_at, updated_at
`

type UpsertShippingLocationParams struct {
	LocationID string
	Priority   int64
}

// shipping_locations ve shipping_location_regions sorguları.
//
// Okuma yolu ikiye ayrılır ve ayrım shipping_options'ınkiyle AYNI gerekçeye
// dayanır:
//
//   - Yönetim listelemesi (ListShippingLocations) — sayfalanır.
//   - Seçim okuması (ShippingLocationPolicies) — aday depoların kararı
//     etkileyen OLGULARINI tek turda döner. Politikanın KENDİSİ burada
//     çalışmaz; eleme ve sıralama servis katmanındaki saf fonksiyonda yaşar ve
//     veritabanı olmadan birim testiyle kanıtlanabilir.
//
// Silme YUMUŞAK DEĞİLDİR; gerekçesi migration'ın başındadır. Bu yüzden
// sorguların hiçbirinde deleted_at süzgeci yoktur ve olmaması bir unutma
// değildir.
// UpsertShippingLocation politikayı YAZAR ya da ÜZERİNE yazar.
//
// Ayrı bir Create/Update çifti yerine tek upsert olmasının sebebi, yüzeyin
// ifade ettiği şeyin bir VARLIK oluşturmak değil bir depoya ait AYARI
// belirlemek olmasıdır: çağıran "bu depo şu öncelikte" der ve satırın daha önce
// var olup olmadığı onun sorunu değildir.
func (q *Queries) UpsertShippingLocation(ctx context.Context, arg UpsertShippingLocationParams) (ShippingLocation, error) {
	row := q.db.QueryRow(ctx, upsertShippingLocation, arg.LocationID, arg.Priority)
	var i ShippingLocation
	err := row.Scan(
		&i.LocationID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
