// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_store_credit.sql

package paymentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStoreCreditEntries = `-- name: CountStoreCreditEntries :one
SELECT COUNT(*) FROM payment_store_credit_entries
WHERE customer_id = $1 AND currency_code = $2
`

type CountStoreCreditEntriesParams struct {
	CustomerID   string
	CurrencyCode string
}

// CountStoreCreditEntries counts them for the listing's envelope.
func (q *Queries) CountStoreCreditEntries(ctx context.Context, arg CountStoreCreditEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStoreCreditEntries, arg.CustomerID, arg.CurrencyCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStoreCreditSession = `-- name: GetStoreCreditSession :one
SELECT id, idempotency_key, reference, customer_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at, partial FROM payment_store_credit_sessions
WHERE id = $1
`

func (q *Queries) GetStoreCreditSession(ctx context.Context, id string) (PaymentStoreCreditSession, error) {
	row := q.db.QueryRow(ctx, getStoreCreditSession, id)
	var i PaymentStoreCreditSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CustomerID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Partial,
	)
	return i, err
}

const getStoreCreditSessionByIdempotencyKey = `-- name: GetStoreCreditSessionByIdempotencyKey :one
SELECT id, idempotency_key, reference, customer_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at, partial FROM payment_store_credit_sessions
WHERE idempotency_key = $1
`

func (q *Queries) GetStoreCreditSessionByIdempotencyKey(ctx context.Context, idempotencyKey string) (PaymentStoreCreditSession, error) {
	row := q.db.QueryRow(ctx, getStoreCreditSessionByIdempotencyKey, idempotencyKey)
	var i PaymentStoreCreditSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CustomerID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Partial,
	)
	return i, err
}

const insertStoreCreditEntry = `-- name: InsertStoreCreditEntry :one

INSERT INTO payment_store_credit_entries (
    id, customer_id, currency_code, amount, kind, reference, reason, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, customer_id, currency_code, amount, kind, reference, reason, created_at, expires_at
`

type InsertStoreCreditEntryParams struct {
	ID           string
	CustomerID   string
	CurrencyCode string
	Amount       int64
	Kind         string
	Reference    string
	Reason       string
	ExpiresAt    pgtype.Timestamptz
}

// payment_store_credit queries — the ledger and the provider's own sessions.
//
// Two tables and two readers. The ENTRIES are the module's own money record: the
// service issues credit into them and answers a balance out of them. The SESSIONS
// belong to the store-credit PROVIDER, the way payment_manual_sessions belongs to
// the manual one, and the service never touches them.
// InsertStoreCreditEntry appends one event to the ledger.
//
// There is no update and no delete anywhere in this file, and that is the table's
// whole design: a balance is the sum of what happened to it, so a correction is a
// NEW ROW rather than an edited one (the module's own rule since its 000003 —
// "a money record is kept").
func (q *Queries) InsertStoreCreditEntry(ctx context.Context, arg InsertStoreCreditEntryParams) (PaymentStoreCreditEntry, error) {
	row := q.db.QueryRow(ctx, insertStoreCreditEntry,
		arg.ID,
		arg.CustomerID,
		arg.CurrencyCode,
		arg.Amount,
		arg.Kind,
		arg.Reference,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i PaymentStoreCreditEntry
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CurrencyCode,
		&i.Amount,
		&i.Kind,
		&i.Reference,
		&i.Reason,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertStoreCreditSessionIfAbsent = `-- name: InsertStoreCreditSessionIfAbsent :one
INSERT INTO payment_store_credit_sessions (
    id, idempotency_key, reference, customer_id, amount, currency_code, status, partial
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, idempotency_key, reference, customer_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at, partial
`

type InsertStoreCreditSessionIfAbsentParams struct {
	ID             string
	IdempotencyKey string
	Reference      string
	CustomerID     string
	Amount         int64
	CurrencyCode   string
	Status         string
	Partial        bool
}

// InsertStoreCreditSessionIfAbsent writes the provider's session only if that
// idempotency key has not been used yet; see InsertManualSessionIfAbsent for why
// the conflict is handled in one statement.
func (q *Queries) InsertStoreCreditSessionIfAbsent(ctx context.Context, arg InsertStoreCreditSessionIfAbsentParams) (PaymentStoreCreditSession, error) {
	row := q.db.QueryRow(ctx, insertStoreCreditSessionIfAbsent,
		arg.ID,
		arg.IdempotencyKey,
		arg.Reference,
		arg.CustomerID,
		arg.Amount,
		arg.CurrencyCode,
		arg.Status,
		arg.Partial,
	)
	var i PaymentStoreCreditSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CustomerID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Partial,
	)
	return i, err
}

const listStoreCreditEntries = `-- name: ListStoreCreditEntries :many
SELECT id, customer_id, currency_code, amount, kind, reference, reason, created_at, expires_at FROM payment_store_credit_entries
WHERE customer_id = $1 AND currency_code = $2
ORDER BY created_at DESC, id DESC
LIMIT $4::bigint OFFSET $3::bigint
`

type ListStoreCreditEntriesParams struct {
	CustomerID   string
	CurrencyCode string
	RowOffset    int64
	RowLimit     int64
}

// ListStoreCreditEntries returns one customer's history, newest first.
func (q *Queries) ListStoreCreditEntries(ctx context.Context, arg ListStoreCreditEntriesParams) ([]PaymentStoreCreditEntry, error) {
	rows, err := q.db.Query(ctx, listStoreCreditEntries,
		arg.CustomerID,
		arg.CurrencyCode,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentStoreCreditEntry{}
	for rows.Next() {
		var i PaymentStoreCreditEntry
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CurrencyCode,
			&i.Amount,
			&i.Kind,
			&i.Reference,
			&i.Reason,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStoreCreditSession = `-- name: LockStoreCreditSession :one
SELECT id, idempotency_key, reference, customer_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at, partial FROM payment_store_credit_sessions
WHERE id = $1
FOR UPDATE
`

// LockStoreCreditSession locks the session for the length of the transaction;
// every status transition is made under it, which is what makes a repeated
// Authorize see what the first one wrote instead of holding the money twice.
func (q *Queries) LockStoreCreditSession(ctx context.Context, id string) (PaymentStoreCreditSession, error) {
	row := q.db.QueryRow(ctx, lockStoreCreditSession, id)
	var i PaymentStoreCreditSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CustomerID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Partial,
	)
	return i, err
}

const storeCreditExpiryDue = `-- name: StoreCreditExpiryDue :many
WITH candidates AS (
    SELECT DISTINCT customer_id, currency_code
    FROM payment_store_credit_entries
    WHERE kind = 'issue' AND expires_at IS NOT NULL
      AND expires_at <= $2::timestamptz
), figures AS (
    SELECT e.customer_id, e.currency_code,
        SUM(e.amount) AS balance,
        COALESCE(SUM(e.amount) FILTER (WHERE e.kind = 'refund'
            OR (e.kind = 'issue' AND (e.expires_at IS NULL OR e.expires_at > $2::timestamptz))), 0) AS unexpired,
        COALESCE(SUM(e.amount) FILTER (WHERE e.kind = 'issue'
            AND e.expires_at <= $2::timestamptz), 0) AS expired,
        COALESCE(-SUM(e.amount) FILTER (WHERE e.kind = 'expire'), 0) AS written
    FROM payment_store_credit_entries e
    JOIN candidates c ON c.customer_id = e.customer_id AND c.currency_code = e.currency_code
    GROUP BY e.customer_id, e.currency_code
)
SELECT customer_id, currency_code
FROM figures
WHERE LEAST(GREATEST(balance - unexpired, 0), expired - written) > 0
ORDER BY customer_id, currency_code
LIMIT $1::bigint
`

type StoreCreditExpiryDueParams struct {
	RowLimit int64
	At       pgtype.Timestamptz
}

type StoreCreditExpiryDueRow struct {
	CustomerID   string
	CurrencyCode string
}

// StoreCreditExpiryDue lists the balances an expiry is owed from, at the given
// moment, at most row_limit of them: those holding an expired issue whose
// figures still leave something to take back (StoreCreditExpiryFigures). The
// inner read walks the partial index of expiring issues, so a balance that
// never had one is never summed.
func (q *Queries) StoreCreditExpiryDue(ctx context.Context, arg StoreCreditExpiryDueParams) ([]StoreCreditExpiryDueRow, error) {
	rows, err := q.db.Query(ctx, storeCreditExpiryDue, arg.RowLimit, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoreCreditExpiryDueRow{}
	for rows.Next() {
		var i StoreCreditExpiryDueRow
		if err := rows.Scan(&i.CustomerID, &i.CurrencyCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeCreditExpiryFigures = `-- name: StoreCreditExpiryFigures :one
SELECT
    COALESCE(SUM(amount), 0)::bigint AS balance,
    COALESCE(SUM(amount) FILTER (WHERE kind = 'refund'
        OR (kind = 'issue' AND (expires_at IS NULL OR expires_at > $1::timestamptz))), 0)::bigint AS unexpired,
    COALESCE(SUM(amount) FILTER (WHERE kind = 'issue'
        AND expires_at <= $1::timestamptz), 0)::bigint AS expired,
    COALESCE(-SUM(amount) FILTER (WHERE kind = 'expire'), 0)::bigint AS written
FROM payment_store_credit_entries
WHERE customer_id = $2 AND currency_code = $3
`

type StoreCreditExpiryFiguresParams struct {
	At           pgtype.Timestamptz
	CustomerID   string
	CurrencyCode string
}

type StoreCreditExpiryFiguresRow struct {
	Balance   int64
	Unexpired int64
	Expired   int64
	Written   int64
}

// StoreCreditExpiryFigures reads the four sums the expiry of one balance is
// decided from (ADR 0258), at the given moment:
//
//	balance    every row;
//	unexpired  the issues not yet expired, and the refunds, which never expire;
//	expired    the issues whose moment has come;
//	written    what expire rows have already taken back, as a positive amount.
//
// Credit is taken to be spent soonest-expiring first, so the balance is made of
// the latest money: whatever of it the unexpired sources cannot account for is
// expired credit, up to what the expired issues gave and has not been taken.
// The caller holds the balance's lock (LockStoreCreditBalance) while it reads
// these and writes the row they decide.
func (q *Queries) StoreCreditExpiryFigures(ctx context.Context, arg StoreCreditExpiryFiguresParams) (StoreCreditExpiryFiguresRow, error) {
	row := q.db.QueryRow(ctx, storeCreditExpiryFigures, arg.At, arg.CustomerID, arg.CurrencyCode)
	var i StoreCreditExpiryFiguresRow
	err := row.Scan(
		&i.Balance,
		&i.Unexpired,
		&i.Expired,
		&i.Written,
	)
	return i, err
}

const updateStoreCreditSessionState = `-- name: UpdateStoreCreditSessionState :one
UPDATE payment_store_credit_sessions
SET status            = $2,
    authorized_amount = $3,
    captured_amount   = $4,
    refunded_amount   = $5,
    decline_reason    = $6,
    updated_at        = now()
WHERE id = $1
RETURNING id, idempotency_key, reference, customer_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at, partial
`

type UpdateStoreCreditSessionStateParams struct {
	ID               string
	Status           string
	AuthorizedAmount int64
	CapturedAmount   int64
	RefundedAmount   int64
	DeclineReason    *string
}

// UpdateStoreCreditSessionState writes the status and the three amounts as
// ABSOLUTE values; an incremental update would pull the value the deciding code
// saw apart from the value that gets written.
func (q *Queries) UpdateStoreCreditSessionState(ctx context.Context, arg UpdateStoreCreditSessionStateParams) (PaymentStoreCreditSession, error) {
	row := q.db.QueryRow(ctx, updateStoreCreditSessionState,
		arg.ID,
		arg.Status,
		arg.AuthorizedAmount,
		arg.CapturedAmount,
		arg.RefundedAmount,
		arg.DeclineReason,
	)
	var i PaymentStoreCreditSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CustomerID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Partial,
	)
	return i, err
}
