// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package paymentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one

INSERT INTO payments (
    id, payment_session_id, payment_collection_id, amount, currency_code, captured_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, payment_session_id, payment_collection_id, amount, currency_code, refunded_amount, captured_at, created_at, updated_at
`

type CreatePaymentParams struct {
	ID                  string
	PaymentSessionID    string
	PaymentCollectionID string
	Amount              int64
	CurrencyCode        string
	CapturedAt          pgtype.Timestamptz
}

// payments queries.
//
// AT MOST ONE capture comes out of a session (payments_session_uniq). That is
// what makes Capture idempotent: the second call writes no new row, it finds
// the existing one with GetPaymentBySession and returns it.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.PaymentSessionID,
		arg.PaymentCollectionID,
		arg.Amount,
		arg.CurrencyCode,
		arg.CapturedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentSessionID,
		&i.PaymentCollectionID,
		&i.Amount,
		&i.CurrencyCode,
		&i.RefundedAmount,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, payment_session_id, payment_collection_id, amount, currency_code, refunded_amount, captured_at, created_at, updated_at FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentSessionID,
		&i.PaymentCollectionID,
		&i.Amount,
		&i.CurrencyCode,
		&i.RefundedAmount,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentBySession = `-- name: GetPaymentBySession :one
SELECT id, payment_session_id, payment_collection_id, amount, currency_code, refunded_amount, captured_at, created_at, updated_at FROM payments
WHERE payment_session_id = $1
`

func (q *Queries) GetPaymentBySession(ctx context.Context, paymentSessionID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentBySession, paymentSessionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentSessionID,
		&i.PaymentCollectionID,
		&i.Amount,
		&i.CurrencyCode,
		&i.RefundedAmount,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByCollection = `-- name: ListPaymentsByCollection :many
SELECT id, payment_session_id, payment_collection_id, amount, currency_code, refunded_amount, captured_at, created_at, updated_at FROM payments
WHERE payment_collection_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPaymentsByCollection(ctx context.Context, paymentCollectionID string) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByCollection, paymentCollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PaymentSessionID,
			&i.PaymentCollectionID,
			&i.Amount,
			&i.CurrencyCode,
			&i.RefundedAmount,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPayment = `-- name: LockPayment :one
SELECT id, payment_session_id, payment_collection_id, amount, currency_code, refunded_amount, captured_at, created_at, updated_at FROM payments
WHERE id = $1
FOR UPDATE
`

// LockPayment locks the capture for the length of the transaction; the refunded
// amount is updated only under this lock. In the lock order it comes AFTER the
// collection and the session (see service.Store, "Transaction boundary").
func (q *Queries) LockPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, lockPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentSessionID,
		&i.PaymentCollectionID,
		&i.Amount,
		&i.CurrencyCode,
		&i.RefundedAmount,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentRefundedAmount = `-- name: UpdatePaymentRefundedAmount :one
UPDATE payments
SET refunded_amount = $2,
    updated_at      = now()
WHERE id = $1
RETURNING id, payment_session_id, payment_collection_id, amount, currency_code, refunded_amount, captured_at, created_at, updated_at
`

type UpdatePaymentRefundedAmountParams struct {
	ID             string
	RefundedAmount int64
}

func (q *Queries) UpdatePaymentRefundedAmount(ctx context.Context, arg UpdatePaymentRefundedAmountParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentRefundedAmount, arg.ID, arg.RefundedAmount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentSessionID,
		&i.PaymentCollectionID,
		&i.Amount,
		&i.CurrencyCode,
		&i.RefundedAmount,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
