// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_gift_card.sql

package paymentdb

import (
	"context"
)

const countGiftCardEntries = `-- name: CountGiftCardEntries :one
SELECT COUNT(*) FROM payment_gift_card_entries
WHERE gift_card_id = $1
`

func (q *Queries) CountGiftCardEntries(ctx context.Context, giftCardID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGiftCardEntries, giftCardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGiftCards = `-- name: CountGiftCards :one
SELECT COUNT(*) FROM payment_gift_cards
`

func (q *Queries) CountGiftCards(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGiftCards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGiftCard = `-- name: GetGiftCard :one
SELECT id, code_digest, code_tail, currency_code, reason, created_at FROM payment_gift_cards
WHERE id = $1
`

func (q *Queries) GetGiftCard(ctx context.Context, id string) (PaymentGiftCard, error) {
	row := q.db.QueryRow(ctx, getGiftCard, id)
	var i PaymentGiftCard
	err := row.Scan(
		&i.ID,
		&i.CodeDigest,
		&i.CodeTail,
		&i.CurrencyCode,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getGiftCardByDigest = `-- name: GetGiftCardByDigest :one
SELECT id, code_digest, code_tail, currency_code, reason, created_at FROM payment_gift_cards
WHERE code_digest = $1
`

// GetGiftCardByDigest finds the card a presented code opens.
func (q *Queries) GetGiftCardByDigest(ctx context.Context, codeDigest string) (PaymentGiftCard, error) {
	row := q.db.QueryRow(ctx, getGiftCardByDigest, codeDigest)
	var i PaymentGiftCard
	err := row.Scan(
		&i.ID,
		&i.CodeDigest,
		&i.CodeTail,
		&i.CurrencyCode,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getGiftCardSession = `-- name: GetGiftCardSession :one
SELECT id, idempotency_key, reference, gift_card_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at FROM payment_gift_card_sessions
WHERE id = $1
`

func (q *Queries) GetGiftCardSession(ctx context.Context, id string) (PaymentGiftCardSession, error) {
	row := q.db.QueryRow(ctx, getGiftCardSession, id)
	var i PaymentGiftCardSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.GiftCardID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGiftCardSessionByIdempotencyKey = `-- name: GetGiftCardSessionByIdempotencyKey :one
SELECT id, idempotency_key, reference, gift_card_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at FROM payment_gift_card_sessions
WHERE idempotency_key = $1
`

func (q *Queries) GetGiftCardSessionByIdempotencyKey(ctx context.Context, idempotencyKey string) (PaymentGiftCardSession, error) {
	row := q.db.QueryRow(ctx, getGiftCardSessionByIdempotencyKey, idempotencyKey)
	var i PaymentGiftCardSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.GiftCardID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const giftCardBalance = `-- name: GiftCardBalance :one
SELECT COALESCE(SUM(amount), 0)::bigint AS balance
FROM payment_gift_card_entries
WHERE gift_card_id = $1
`

func (q *Queries) GiftCardBalance(ctx context.Context, giftCardID string) (int64, error) {
	row := q.db.QueryRow(ctx, giftCardBalance, giftCardID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const giftCardBalances = `-- name: GiftCardBalances :many
SELECT gift_card_id, COALESCE(SUM(amount), 0)::bigint AS balance
FROM payment_gift_card_entries
WHERE gift_card_id = ANY($1::text[])
GROUP BY gift_card_id
`

type GiftCardBalancesRow struct {
	GiftCardID string
	Balance    int64
}

// GiftCardBalances sums several cards at once, for a page of the listing.
func (q *Queries) GiftCardBalances(ctx context.Context, ids []string) ([]GiftCardBalancesRow, error) {
	rows, err := q.db.Query(ctx, giftCardBalances, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GiftCardBalancesRow{}
	for rows.Next() {
		var i GiftCardBalancesRow
		if err := rows.Scan(&i.GiftCardID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGiftCard = `-- name: InsertGiftCard :one

INSERT INTO payment_gift_cards (id, code_digest, code_tail, currency_code, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code_digest, code_tail, currency_code, reason, created_at
`

type InsertGiftCardParams struct {
	ID           string
	CodeDigest   string
	CodeTail     string
	CurrencyCode string
	Reason       string
}

// payment_gift_card queries — the cards, their ledger and the provider's own
// sessions (ADR 0208).
//
// As with store credit, there is no update or delete of a card or an entry: a
// balance is the sum of what happened to it, and a correction is a new row.
func (q *Queries) InsertGiftCard(ctx context.Context, arg InsertGiftCardParams) (PaymentGiftCard, error) {
	row := q.db.QueryRow(ctx, insertGiftCard,
		arg.ID,
		arg.CodeDigest,
		arg.CodeTail,
		arg.CurrencyCode,
		arg.Reason,
	)
	var i PaymentGiftCard
	err := row.Scan(
		&i.ID,
		&i.CodeDigest,
		&i.CodeTail,
		&i.CurrencyCode,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertGiftCardEntry = `-- name: InsertGiftCardEntry :one
INSERT INTO payment_gift_card_entries (id, gift_card_id, amount, kind, reference)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, gift_card_id, amount, kind, reference, created_at
`

type InsertGiftCardEntryParams struct {
	ID         string
	GiftCardID string
	Amount     int64
	Kind       string
	Reference  string
}

func (q *Queries) InsertGiftCardEntry(ctx context.Context, arg InsertGiftCardEntryParams) (PaymentGiftCardEntry, error) {
	row := q.db.QueryRow(ctx, insertGiftCardEntry,
		arg.ID,
		arg.GiftCardID,
		arg.Amount,
		arg.Kind,
		arg.Reference,
	)
	var i PaymentGiftCardEntry
	err := row.Scan(
		&i.ID,
		&i.GiftCardID,
		&i.Amount,
		&i.Kind,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const insertGiftCardSessionIfAbsent = `-- name: InsertGiftCardSessionIfAbsent :one
INSERT INTO payment_gift_card_sessions (
    id, idempotency_key, reference, gift_card_id, amount, currency_code, status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, idempotency_key, reference, gift_card_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at
`

type InsertGiftCardSessionIfAbsentParams struct {
	ID             string
	IdempotencyKey string
	Reference      string
	GiftCardID     string
	Amount         int64
	CurrencyCode   string
	Status         string
}

func (q *Queries) InsertGiftCardSessionIfAbsent(ctx context.Context, arg InsertGiftCardSessionIfAbsentParams) (PaymentGiftCardSession, error) {
	row := q.db.QueryRow(ctx, insertGiftCardSessionIfAbsent,
		arg.ID,
		arg.IdempotencyKey,
		arg.Reference,
		arg.GiftCardID,
		arg.Amount,
		arg.CurrencyCode,
		arg.Status,
	)
	var i PaymentGiftCardSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.GiftCardID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGiftCardEntries = `-- name: ListGiftCardEntries :many
SELECT id, gift_card_id, amount, kind, reference, created_at FROM payment_gift_card_entries
WHERE gift_card_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3::bigint OFFSET $2::bigint
`

type ListGiftCardEntriesParams struct {
	GiftCardID string
	RowOffset  int64
	RowLimit   int64
}

func (q *Queries) ListGiftCardEntries(ctx context.Context, arg ListGiftCardEntriesParams) ([]PaymentGiftCardEntry, error) {
	rows, err := q.db.Query(ctx, listGiftCardEntries, arg.GiftCardID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentGiftCardEntry{}
	for rows.Next() {
		var i PaymentGiftCardEntry
		if err := rows.Scan(
			&i.ID,
			&i.GiftCardID,
			&i.Amount,
			&i.Kind,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGiftCards = `-- name: ListGiftCards :many
SELECT id, code_digest, code_tail, currency_code, reason, created_at FROM payment_gift_cards
ORDER BY created_at DESC, id DESC
LIMIT $2::bigint OFFSET $1::bigint
`

type ListGiftCardsParams struct {
	RowOffset int64
	RowLimit  int64
}

func (q *Queries) ListGiftCards(ctx context.Context, arg ListGiftCardsParams) ([]PaymentGiftCard, error) {
	rows, err := q.db.Query(ctx, listGiftCards, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentGiftCard{}
	for rows.Next() {
		var i PaymentGiftCard
		if err := rows.Scan(
			&i.ID,
			&i.CodeDigest,
			&i.CodeTail,
			&i.CurrencyCode,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGiftCard = `-- name: LockGiftCard :one
SELECT id FROM payment_gift_cards
WHERE id = $1
FOR UPDATE
`

// LockGiftCard locks the card's row for the transaction. It is the balance's
// lock: unlike a customer's credit, a card always has its row, so the row is
// there to be locked before the balance is summed.
func (q *Queries) LockGiftCard(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockGiftCard, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const lockGiftCardSession = `-- name: LockGiftCardSession :one
SELECT id, idempotency_key, reference, gift_card_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at FROM payment_gift_card_sessions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockGiftCardSession(ctx context.Context, id string) (PaymentGiftCardSession, error) {
	row := q.db.QueryRow(ctx, lockGiftCardSession, id)
	var i PaymentGiftCardSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.GiftCardID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGiftCardSessionState = `-- name: UpdateGiftCardSessionState :one
UPDATE payment_gift_card_sessions
SET status            = $2,
    authorized_amount = $3,
    captured_amount   = $4,
    refunded_amount   = $5,
    decline_reason    = $6,
    updated_at        = now()
WHERE id = $1
RETURNING id, idempotency_key, reference, gift_card_id, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, decline_reason, created_at, updated_at
`

type UpdateGiftCardSessionStateParams struct {
	ID               string
	Status           string
	AuthorizedAmount int64
	CapturedAmount   int64
	RefundedAmount   int64
	DeclineReason    *string
}

func (q *Queries) UpdateGiftCardSessionState(ctx context.Context, arg UpdateGiftCardSessionStateParams) (PaymentGiftCardSession, error) {
	row := q.db.QueryRow(ctx, updateGiftCardSessionState,
		arg.ID,
		arg.Status,
		arg.AuthorizedAmount,
		arg.CapturedAmount,
		arg.RefundedAmount,
		arg.DeclineReason,
	)
	var i PaymentGiftCardSession
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Reference,
		&i.GiftCardID,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
