// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_sessions.sql

package paymentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPaymentSessionStates = `-- name: CountPaymentSessionStates :one
SELECT
    COUNT(*) FILTER (WHERE status IN ('pending', 'authorized')) AS live_count,
    COUNT(*) FILTER (WHERE status = 'canceled')                 AS canceled_count,
    COUNT(*) FILTER (WHERE status = 'failed')                   AS failed_count,
    COUNT(*)                                                    AS total_count
FROM payment_sessions
WHERE payment_collection_id = $1
`

type CountPaymentSessionStatesRow struct {
	LiveCount     int64
	CanceledCount int64
	FailedCount   int64
	TotalCount    int64
}

// CountPaymentSessionStates counts a collection's sessions by status in a
// SINGLE query. The collection's derived status looks at these counts: a
// collection with no session at all is "not_paid", one with a live session is
// "awaiting", one whose only sessions are canceled is "canceled" (see
// service.CollectionStatusFor).
func (q *Queries) CountPaymentSessionStates(ctx context.Context, paymentCollectionID string) (CountPaymentSessionStatesRow, error) {
	row := q.db.QueryRow(ctx, countPaymentSessionStates, paymentCollectionID)
	var i CountPaymentSessionStatesRow
	err := row.Scan(
		&i.LiveCount,
		&i.CanceledCount,
		&i.FailedCount,
		&i.TotalCount,
	)
	return i, err
}

const createPaymentSession = `-- name: CreatePaymentSession :one

INSERT INTO payment_sessions (
    id, payment_collection_id, provider_id, external_id, status,
    amount, authorized_amount, currency_code, data, idempotency_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, payment_collection_id, provider_id, external_id, status, amount, authorized_amount, currency_code, data, idempotency_key, decline_reason, created_at, updated_at
`

type CreatePaymentSessionParams struct {
	ID                  string
	PaymentCollectionID string
	ProviderID          string
	ExternalID          string
	Status              string
	Amount              int64
	AuthorizedAmount    int64
	CurrencyCode        string
	Data                []byte
	IdempotencyKey      string
}

// payment_sessions queries.
//
// A session record is NEVER DELETED, its status changes. The idempotence of the
// compensation (CancelPayment) rests on that: the second call finds the record,
// sees "canceled" and returns successfully without going to the provider a
// second time. A deleted session and a session that never existed could not be
// told apart.
//
// The schema now says the same thing: there is no deleted_at to write and no
// read here filters on one (ADR 0054).
func (q *Queries) CreatePaymentSession(ctx context.Context, arg CreatePaymentSessionParams) (PaymentSession, error) {
	row := q.db.QueryRow(ctx, createPaymentSession,
		arg.ID,
		arg.PaymentCollectionID,
		arg.ProviderID,
		arg.ExternalID,
		arg.Status,
		arg.Amount,
		arg.AuthorizedAmount,
		arg.CurrencyCode,
		arg.Data,
		arg.IdempotencyKey,
	)
	var i PaymentSession
	err := row.Scan(
		&i.ID,
		&i.PaymentCollectionID,
		&i.ProviderID,
		&i.ExternalID,
		&i.Status,
		&i.Amount,
		&i.AuthorizedAmount,
		&i.CurrencyCode,
		&i.Data,
		&i.IdempotencyKey,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentSession = `-- name: GetPaymentSession :one
SELECT id, payment_collection_id, provider_id, external_id, status, amount, authorized_amount, currency_code, data, idempotency_key, decline_reason, created_at, updated_at FROM payment_sessions
WHERE id = $1
`

func (q *Queries) GetPaymentSession(ctx context.Context, id string) (PaymentSession, error) {
	row := q.db.QueryRow(ctx, getPaymentSession, id)
	var i PaymentSession
	err := row.Scan(
		&i.ID,
		&i.PaymentCollectionID,
		&i.ProviderID,
		&i.ExternalID,
		&i.Status,
		&i.Amount,
		&i.AuthorizedAmount,
		&i.CurrencyCode,
		&i.Data,
		&i.IdempotencyKey,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentSessionByIdempotencyKey = `-- name: GetPaymentSessionByIdempotencyKey :one
SELECT id, payment_collection_id, provider_id, external_id, status, amount, authorized_amount, currency_code, data, idempotency_key, decline_reason, created_at, updated_at FROM payment_sessions
WHERE provider_id = $1 AND idempotency_key = $2
`

type GetPaymentSessionByIdempotencyKeyParams struct {
	ProviderID     string
	IdempotencyKey string
}

// GetPaymentSessionByIdempotencyKey finds the session opened with the same key.
// CreateSession asks this BEFORE IT GOES to the provider; a second call opens
// no new session (plan Section 2.6, the core/provider idempotency requirement).
func (q *Queries) GetPaymentSessionByIdempotencyKey(ctx context.Context, arg GetPaymentSessionByIdempotencyKeyParams) (PaymentSession, error) {
	row := q.db.QueryRow(ctx, getPaymentSessionByIdempotencyKey, arg.ProviderID, arg.IdempotencyKey)
	var i PaymentSession
	err := row.Scan(
		&i.ID,
		&i.PaymentCollectionID,
		&i.ProviderID,
		&i.ExternalID,
		&i.Status,
		&i.Amount,
		&i.AuthorizedAmount,
		&i.CurrencyCode,
		&i.Data,
		&i.IdempotencyKey,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentSessionsByCollection = `-- name: ListPaymentSessionsByCollection :many
SELECT id, payment_collection_id, provider_id, external_id, status, amount, authorized_amount, currency_code, data, idempotency_key, decline_reason, created_at, updated_at FROM payment_sessions
WHERE payment_collection_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPaymentSessionsByCollection(ctx context.Context, paymentCollectionID string) ([]PaymentSession, error) {
	rows, err := q.db.Query(ctx, listPaymentSessionsByCollection, paymentCollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentSession{}
	for rows.Next() {
		var i PaymentSession
		if err := rows.Scan(
			&i.ID,
			&i.PaymentCollectionID,
			&i.ProviderID,
			&i.ExternalID,
			&i.Status,
			&i.Amount,
			&i.AuthorizedAmount,
			&i.CurrencyCode,
			&i.Data,
			&i.IdempotencyKey,
			&i.DeclineReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForReconciliation = `-- name: ListSessionsForReconciliation :many
SELECT id, payment_collection_id, provider_id, external_id, status, amount, authorized_amount, currency_code, data, idempotency_key, decline_reason, created_at, updated_at FROM payment_sessions
WHERE status = 'authorized'
  AND updated_at < $1
ORDER BY updated_at
LIMIT $2
`

type ListSessionsForReconciliationParams struct {
	UpdatedAt pgtype.Timestamptz
	Limit     int32
}

// ListSessionsForReconciliation returns the sessions the provider has to be
// ASKED about: the ones that look authorized but not captured, and have looked
// that way for a while.
//
// # Why exactly this set
//
// The module makes its provider call INSIDE ITS OWN transaction. If the
// transaction is rolled back after the money was taken, the session stays
// 'authorized' locally while at the provider it is 'captured' — and that
// difference is visible from nowhere else (see
// internal/workflows/checkout/doc.go, "REMAINING RISK").
//
// 'pending' is LEFT OUT, and that is deliberate: before a session is authorized
// no money has moved, so there is no amount that could diverge either. Widening
// the scope to there would mean asking the provider about every cart that was
// ever opened and abandoned — that is, putting the noise in front of the row
// that has to be looked at.
//
// $2 is a WAITING PERIOD, not an optional threshold: a capture in flight stands
// in exactly this state for seconds at a time, and counting that as a
// divergence would drop every normal payment into the report.
func (q *Queries) ListSessionsForReconciliation(ctx context.Context, arg ListSessionsForReconciliationParams) ([]PaymentSession, error) {
	rows, err := q.db.Query(ctx, listSessionsForReconciliation, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentSession{}
	for rows.Next() {
		var i PaymentSession
		if err := rows.Scan(
			&i.ID,
			&i.PaymentCollectionID,
			&i.ProviderID,
			&i.ExternalID,
			&i.Status,
			&i.Amount,
			&i.AuthorizedAmount,
			&i.CurrencyCode,
			&i.Data,
			&i.IdempotencyKey,
			&i.DeclineReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentSession = `-- name: LockPaymentSession :one
SELECT id, payment_collection_id, provider_id, external_id, status, amount, authorized_amount, currency_code, data, idempotency_key, decline_reason, created_at, updated_at FROM payment_sessions
WHERE id = $1
FOR UPDATE
`

// LockPaymentSession locks the session for the length of the transaction;
// status transitions (authorize/capture/cancel) are made only under this lock.
// Of two calls trying to authorize the same session at the same time, the
// second sees the status the first wrote and does NOT go to the provider A
// SECOND TIME.
func (q *Queries) LockPaymentSession(ctx context.Context, id string) (PaymentSession, error) {
	row := q.db.QueryRow(ctx, lockPaymentSession, id)
	var i PaymentSession
	err := row.Scan(
		&i.ID,
		&i.PaymentCollectionID,
		&i.ProviderID,
		&i.ExternalID,
		&i.Status,
		&i.Amount,
		&i.AuthorizedAmount,
		&i.CurrencyCode,
		&i.Data,
		&i.IdempotencyKey,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumLiveSessionAmounts = `-- name: SumLiveSessionAmounts :one
SELECT COALESCE(SUM(
    CASE WHEN status = 'pending' THEN amount ELSE authorized_amount END
), 0)::bigint AS reserved_amount
FROM payment_sessions
WHERE payment_collection_id = $1
  AND status IN ('pending', 'authorized')
`

// SumLiveSessionAmounts gives the total amount the collection's LIVE sessions
// have reserved. The amount left for a new session to claim is computed from
// it.
//
// A pending session reserves its own AMOUNT: it has not been authorized yet,
// but when it is it can block that amount in full. An authorized session, on
// the other hand, holds only WHAT IT BLOCKED; since it cannot be authorized a
// second time (see models.SessionStatus.AuthorizeAction), the remainder will
// never be used again. A computation that looked only at the authorized amount
// would allow two FULL-amount sessions, neither of them authorized, to be
// opened on the same collection — and, once both were authorized, permit a
// DOUBLE CHARGE.
func (q *Queries) SumLiveSessionAmounts(ctx context.Context, paymentCollectionID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumLiveSessionAmounts, paymentCollectionID)
	var reserved_amount int64
	err := row.Scan(&reserved_amount)
	return reserved_amount, err
}

const updatePaymentSessionState = `-- name: UpdatePaymentSessionState :one
UPDATE payment_sessions
SET status            = $2,
    authorized_amount = $3,
    data              = $4,
    decline_reason    = $5,
    updated_at        = now()
WHERE id = $1
RETURNING id, payment_collection_id, provider_id, external_id, status, amount, authorized_amount, currency_code, data, idempotency_key, decline_reason, created_at, updated_at
`

type UpdatePaymentSessionStateParams struct {
	ID               string
	Status           string
	AuthorizedAmount int64
	Data             []byte
	DeclineReason    *string
}

// UpdatePaymentSessionState writes the session's status, its authorized amount,
// the raw provider data and the decline reason as ABSOLUTE values.
func (q *Queries) UpdatePaymentSessionState(ctx context.Context, arg UpdatePaymentSessionStateParams) (PaymentSession, error) {
	row := q.db.QueryRow(ctx, updatePaymentSessionState,
		arg.ID,
		arg.Status,
		arg.AuthorizedAmount,
		arg.Data,
		arg.DeclineReason,
	)
	var i PaymentSession
	err := row.Scan(
		&i.ID,
		&i.PaymentCollectionID,
		&i.ProviderID,
		&i.ExternalID,
		&i.Status,
		&i.Amount,
		&i.AuthorizedAmount,
		&i.CurrencyCode,
		&i.Data,
		&i.IdempotencyKey,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
