// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_collections.sql

package paymentdb

import (
	"context"
)

const countPaymentCollections = `-- name: CountPaymentCollections :one
SELECT COUNT(*) FROM payment_collections
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR reference = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
`

type CountPaymentCollectionsParams struct {
	Reference *string
	Status    *string
}

// CountPaymentCollections sayfalama zarfının toplam sayısını verir ve
// ListPaymentCollections ile AYNI filtreleri uygular; ikisi birlikte
// değiştirilmelidir.
//
// Toplam, satırlarla birlikte dönen bir pencere fonksiyonundan okunamaz:
// aralık dışı bir sayfada hiç satır dönmez, pencere değerlendirilmez ve toplam
// 0 görünürdü. Toplam sayfanın değil FİLTRENİN sayısıdır.
func (q *Queries) CountPaymentCollections(ctx context.Context, arg CountPaymentCollectionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentCollections, arg.Reference, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentCollection = `-- name: CreatePaymentCollection :one

INSERT INTO payment_collections (
    id, reference, amount, currency_code, status, metadata
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, reference, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, metadata, created_at, updated_at, deleted_at
`

type CreatePaymentCollectionParams struct {
	ID           string
	Reference    string
	Amount       int64
	CurrencyCode string
	Status       string
	Metadata     []byte
}

// payment_collections sorguları.
//
// Koleksiyon satırı, bir ödemenin TÜM alt kayıtları için kilit sırasının İLK
// adımıdır (bkz. service.Store "Kilit sırası"). Oturum, tahsilat ve iade
// yazan her akış işlemine LockPaymentCollection ile başlar; bu sayede aynı
// koleksiyona dokunan iki akış birbirini seri hâle getirir ve türetilen durum
// alanı asla iki farklı hesaptan yazılmaz.
func (q *Queries) CreatePaymentCollection(ctx context.Context, arg CreatePaymentCollectionParams) (PaymentCollection, error) {
	row := q.db.QueryRow(ctx, createPaymentCollection,
		arg.ID,
		arg.Reference,
		arg.Amount,
		arg.CurrencyCode,
		arg.Status,
		arg.Metadata,
	)
	var i PaymentCollection
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentCollection = `-- name: GetPaymentCollection :one
SELECT id, reference, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, metadata, created_at, updated_at, deleted_at FROM payment_collections
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPaymentCollection(ctx context.Context, id string) (PaymentCollection, error) {
	row := q.db.QueryRow(ctx, getPaymentCollection, id)
	var i PaymentCollection
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentCollectionsByIDs = `-- name: GetPaymentCollectionsByIDs :many
SELECT id, reference, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, metadata, created_at, updated_at, deleted_at FROM payment_collections
WHERE id = ANY ($1::text[]) AND deleted_at IS NULL
ORDER BY id
`

// GetPaymentCollectionsByIDs Query katmanının FetchByIDs çağrısını TEK turda
// karşılar; kimlik başına sorgu (N+1) yapılmaz.
func (q *Queries) GetPaymentCollectionsByIDs(ctx context.Context, ids []string) ([]PaymentCollection, error) {
	rows, err := q.db.Query(ctx, getPaymentCollectionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentCollection{}
	for rows.Next() {
		var i PaymentCollection
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Amount,
			&i.CurrencyCode,
			&i.Status,
			&i.AuthorizedAmount,
			&i.CapturedAmount,
			&i.RefundedAmount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentCollections = `-- name: ListPaymentCollections :many
SELECT id, reference, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, metadata, created_at, updated_at, deleted_at FROM payment_collections
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR reference = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4::bigint OFFSET $3::bigint
`

type ListPaymentCollectionsParams struct {
	Reference *string
	Status    *string
	RowOffset int64
	RowLimit  int64
}

func (q *Queries) ListPaymentCollections(ctx context.Context, arg ListPaymentCollectionsParams) ([]PaymentCollection, error) {
	rows, err := q.db.Query(ctx, listPaymentCollections,
		arg.Reference,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentCollection{}
	for rows.Next() {
		var i PaymentCollection
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Amount,
			&i.CurrencyCode,
			&i.Status,
			&i.AuthorizedAmount,
			&i.CapturedAmount,
			&i.RefundedAmount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentCollection = `-- name: LockPaymentCollection :one
SELECT id, reference, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, metadata, created_at, updated_at, deleted_at FROM payment_collections
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// LockPaymentCollection koleksiyonu işlem boyunca kilitler ve güncel hâlini
// döner. Tutarları değiştiren her akış okumasını BU metotla yapar: kilitsiz
// okunan bir tutar yazma anında bayat olabilir ve iki eşzamanlı tahsilat aynı
// yetkilendirmeyi iki kez harcayabilirdi.
func (q *Queries) LockPaymentCollection(ctx context.Context, id string) (PaymentCollection, error) {
	row := q.db.QueryRow(ctx, lockPaymentCollection, id)
	var i PaymentCollection
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePaymentCollectionTotals = `-- name: UpdatePaymentCollectionTotals :one
UPDATE payment_collections
SET status            = $2,
    authorized_amount = $3,
    captured_amount   = $4,
    refunded_amount   = $5,
    updated_at        = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, reference, amount, currency_code, status, authorized_amount, captured_amount, refunded_amount, metadata, created_at, updated_at, deleted_at
`

type UpdatePaymentCollectionTotalsParams struct {
	ID               string
	Status           string
	AuthorizedAmount int64
	CapturedAmount   int64
	RefundedAmount   int64
}

// UpdatePaymentCollectionTotals tutarları ve türetilen durumu MUTLAK
// değerlerle yazar.
//
// Artımlı (amount = amount + n) güncelleme kasten kullanılmaz: yeni değer,
// kilit altında okunan değerden hesaplanır ve kararı veren kodun gördüğü sayı
// ile yazılan sayı aynı olur.
func (q *Queries) UpdatePaymentCollectionTotals(ctx context.Context, arg UpdatePaymentCollectionTotalsParams) (PaymentCollection, error) {
	row := q.db.QueryRow(ctx, updatePaymentCollectionTotals,
		arg.ID,
		arg.Status,
		arg.AuthorizedAmount,
		arg.CapturedAmount,
		arg.RefundedAmount,
	)
	var i PaymentCollection
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Amount,
		&i.CurrencyCode,
		&i.Status,
		&i.AuthorizedAmount,
		&i.CapturedAmount,
		&i.RefundedAmount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
