// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: currency.sql

package regiondb

import (
	"context"
)

const countCurrencies = `-- name: CountCurrencies :one
SELECT count(*) FROM currency
`

func (q *Queries) CountCurrencies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrencies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCurrenciesByCodes = `-- name: GetCurrenciesByCodes :many
SELECT code, symbol, name, decimal_digits, created_at, updated_at FROM currency
WHERE code = ANY($1::text[])
ORDER BY code
`

// GetCurrenciesByCodes reads several currencies in ONE round trip.
//
// The query provider returns regions together with their currencies; a separate
// query per code would be an N+1 (ADR 0004's batch-read requirement).
func (q *Queries) GetCurrenciesByCodes(ctx context.Context, codes []string) ([]Currency, error) {
	rows, err := q.db.Query(ctx, getCurrenciesByCodes, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Symbol,
			&i.Name,
			&i.DecimalDigits,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrency = `-- name: GetCurrency :one

SELECT code, symbol, name, decimal_digits, created_at, updated_at FROM currency
WHERE code = $1
`

// currency queries.
//
// The table has NO deleted_at and these reads carry NO such filter; the
// argument is the same one at the top of country.sql and it is written out in
// 000003.
func (q *Queries) GetCurrency(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Symbol,
		&i.Name,
		&i.DecimalDigits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT code, symbol, name, decimal_digits, created_at, updated_at FROM currency
ORDER BY code
LIMIT $1 OFFSET $2
`

type ListCurrenciesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCurrencies(ctx context.Context, arg ListCurrenciesParams) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Symbol,
			&i.Name,
			&i.DecimalDigits,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
