// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package pricingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPriceListHistory = `-- name: InsertPriceListHistory :exec
INSERT INTO price_list_history
    (id, price_list_id, recorded_at, type, status, starts_at, ends_at, deleted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPriceListHistoryParams struct {
	ID          string
	PriceListID string
	RecordedAt  pgtype.Timestamptz
	Type        string
	Status      string
	StartsAt    pgtype.Timestamptz
	EndsAt      pgtype.Timestamptz
	Deleted     bool
}

// InsertPriceListHistory records a list's header as it stands after a write.
func (q *Queries) InsertPriceListHistory(ctx context.Context, arg InsertPriceListHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPriceListHistory,
		arg.ID,
		arg.PriceListID,
		arg.RecordedAt,
		arg.Type,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.Deleted,
	)
	return err
}

const insertPriceSetHistory = `-- name: InsertPriceSetHistory :exec

INSERT INTO price_set_history (id, price_set_id, recorded_at, prices)
VALUES ($1, $2, $3, $4)
`

type InsertPriceSetHistoryParams struct {
	ID         string
	PriceSetID string
	RecordedAt pgtype.Timestamptz
	Prices     []byte
}

// history queries — what the ladder read, as it stood after every write
// (ADR 0167).
//
// There is no UPDATE and no DELETE in this file, and that is the tables' whole
// design: a snapshot is a fact about a moment that has passed.
// InsertPriceSetHistory records a set's live prices as they stand after a
// write, in the same transaction as the write.
func (q *Queries) InsertPriceSetHistory(ctx context.Context, arg InsertPriceSetHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPriceSetHistory,
		arg.ID,
		arg.PriceSetID,
		arg.RecordedAt,
		arg.Prices,
	)
	return err
}

const listPriceListHistory = `-- name: ListPriceListHistory :many
SELECT id, seq, price_list_id, recorded_at, type, status, starts_at, ends_at, deleted FROM price_list_history
WHERE price_list_id = ANY($1::text[])
ORDER BY price_list_id, recorded_at, seq
`

// ListPriceListHistory returns every snapshot of the given lists, oldest first.
func (q *Queries) ListPriceListHistory(ctx context.Context, priceListIds []string) ([]PriceListHistory, error) {
	rows, err := q.db.Query(ctx, listPriceListHistory, priceListIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceListHistory{}
	for rows.Next() {
		var i PriceListHistory
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.PriceListID,
			&i.RecordedAt,
			&i.Type,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceSetHistory = `-- name: ListPriceSetHistory :many
SELECT id, seq, price_set_id, recorded_at, prices FROM price_set_history
WHERE price_set_id = ANY($1::text[])
ORDER BY price_set_id, recorded_at, seq
`

// ListPriceSetHistory returns every snapshot of the given sets, oldest first.
//
// All of them rather than a window: the question a reader asks — since when has
// this reduction run, and what was the price in the thirty days before — reaches
// back as far as the reduction does, and a set is written when an operator
// edits it, which is rarely.
func (q *Queries) ListPriceSetHistory(ctx context.Context, priceSetIds []string) ([]PriceSetHistory, error) {
	rows, err := q.db.Query(ctx, listPriceSetHistory, priceSetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceSetHistory{}
	for rows.Next() {
		var i PriceSetHistory
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.PriceSetID,
			&i.RecordedAt,
			&i.Prices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
