// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales_channels.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSalesChannels = `-- name: CountSalesChannels :one
SELECT count(*) FROM sales_channel
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR name = $1::text)
  AND ($2::boolean IS NULL OR is_disabled = $2::boolean)
`

type CountSalesChannelsParams struct {
	Name       *string
	IsDisabled *bool
}

func (q *Queries) CountSalesChannels(ctx context.Context, arg CountSalesChannelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesChannels, arg.Name, arg.IsDisabled)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLinksOfSalesChannel = `-- name: DeleteLinksOfSalesChannel :exec
DELETE FROM api_key_sales_channel
WHERE sales_channel_id = $1
`

// DeleteLinksOfSalesChannel kanal silinirken anahtar bağlarını da kaldırır.
//
// Foreign key ON DELETE CASCADE yalnızca GERÇEK silmede çalışır; yumuşak silme
// bir UPDATE olduğu için bağ satırları yerinde kalırdı. Bağ silinmezse,
// silinmiş bir kanal aynı adla yeniden açıldığında eski anahtarlar sessizce
// yeni kanala bağlı sanılabilirdi — bağ satırı kimliğe bakar ve kimlik yeni
// olsa da bu, bağın neden kaldırıldığını unutulmaz kılar.
func (q *Queries) DeleteLinksOfSalesChannel(ctx context.Context, salesChannelID string) error {
	_, err := q.db.Exec(ctx, deleteLinksOfSalesChannel, salesChannelID)
	return err
}

const getSalesChannel = `-- name: GetSalesChannel :one
SELECT id, name, description, is_disabled, metadata, created_at, updated_at, deleted_at FROM sales_channel
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSalesChannel(ctx context.Context, id string) (SalesChannel, error) {
	row := q.db.QueryRow(ctx, getSalesChannel, id)
	var i SalesChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDisabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertSalesChannel = `-- name: InsertSalesChannel :one

INSERT INTO sales_channel (id, name, description, is_disabled, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, name, description, is_disabled, metadata, created_at, updated_at, deleted_at
`

type InsertSalesChannelParams struct {
	ID          string
	Name        string
	Description string
	IsDisabled  bool
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

// sales_channel sorguları. Tüm okumalar deleted_at IS NULL filtresi uygular.
func (q *Queries) InsertSalesChannel(ctx context.Context, arg InsertSalesChannelParams) (SalesChannel, error) {
	row := q.db.QueryRow(ctx, insertSalesChannel,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsDisabled,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i SalesChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDisabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSalesChannels = `-- name: ListSalesChannels :many
SELECT id, name, description, is_disabled, metadata, created_at, updated_at, deleted_at FROM sales_channel
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR name = $1::text)
  AND ($2::boolean IS NULL OR is_disabled = $2::boolean)
ORDER BY created_at DESC, id DESC
LIMIT $4::int OFFSET $3::int
`

type ListSalesChannelsParams struct {
	Name       *string
	IsDisabled *bool
	Off        int32
	Lim        int32
}

func (q *Queries) ListSalesChannels(ctx context.Context, arg ListSalesChannelsParams) ([]SalesChannel, error) {
	rows, err := q.db.Query(ctx, listSalesChannels,
		arg.Name,
		arg.IsDisabled,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesChannel{}
	for rows.Next() {
		var i SalesChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsDisabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesChannelsByIDs = `-- name: ListSalesChannelsByIDs :many
SELECT id, name, description, is_disabled, metadata, created_at, updated_at, deleted_at FROM sales_channel
WHERE id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListSalesChannelsByIDs(ctx context.Context, ids []string) ([]SalesChannel, error) {
	rows, err := q.db.Query(ctx, listSalesChannelsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesChannel{}
	for rows.Next() {
		var i SalesChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsDisabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLiveSalesChannel = `-- name: LockLiveSalesChannel :one
SELECT id FROM sales_channel
WHERE id = $1 AND deleted_at IS NULL
FOR SHARE
`

// LockLiveSalesChannel kanalın CANLI olduğunu doğrular ve satırı işlem sonuna
// kadar kilitler.
//
// Neden yalnızca foreign key yetmiyor: FK satırın FİZİKSEL varlığına bakar,
// yumuşak silinmiş (deleted_at dolu) bir kanal onu geçer. Oysa okuma sorguları
// o kanalı süzer; bağ kurulsa bile anahtar ÖLÜ DOĞAR — hiçbir kanala
// bağlanamamış publishable anahtar mağaza kimliği kuramaz ve hata ancak ilk
// istekte, "kanal bağlıydı ama çalışmıyor" biçiminde ortaya çıkardı.
//
// FOR SHARE bilinçlidir: koşul sorgulandıktan sonra bağ yazılana kadar
// geçen sürede kanalın yumuşak silinmesi mümkündü. Paylaşımlı kilit, silmeyi
// yapan UPDATE'i işlem bitene kadar bekletir; bağ yazımını engellemez, çünkü
// iki bağ yazımı birbirinin kilidiyle çakışmaz.
func (q *Queries) LockLiveSalesChannel(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockLiveSalesChannel, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const softDeleteSalesChannel = `-- name: SoftDeleteSalesChannel :one
UPDATE sales_channel
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteSalesChannelParams struct {
	ID        string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteSalesChannel(ctx context.Context, arg SoftDeleteSalesChannelParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteSalesChannel, arg.ID, arg.DeletedAt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateSalesChannel = `-- name: UpdateSalesChannel :one
UPDATE sales_channel SET
    name        = COALESCE($1::text, name),
    description = COALESCE($2::text, description),
    is_disabled = COALESCE($3::boolean, is_disabled),
    metadata    = COALESCE($4::jsonb, metadata),
    updated_at  = $5
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, name, description, is_disabled, metadata, created_at, updated_at, deleted_at
`

type UpdateSalesChannelParams struct {
	Name        *string
	Description *string
	IsDisabled  *bool
	Metadata    []byte
	UpdatedAt   pgtype.Timestamptz
	ID          string
}

func (q *Queries) UpdateSalesChannel(ctx context.Context, arg UpdateSalesChannelParams) (SalesChannel, error) {
	row := q.db.QueryRow(ctx, updateSalesChannel,
		arg.Name,
		arg.Description,
		arg.IsDisabled,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ID,
	)
	var i SalesChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDisabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
