// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeOtherSessions = `-- name: CloseOtherSessions :execrows
UPDATE auth_session SET revoked_at = $1
WHERE user_id = $2 AND id <> $3 AND revoked_at IS NULL
  AND expires_at > $1
`

type CloseOtherSessionsParams struct {
	Now    pgtype.Timestamptz
	UserID string
	KeepID string
}

// CloseOtherSessions closes every open session of the person but one.
func (q *Queries) CloseOtherSessions(ctx context.Context, arg CloseOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeOtherSessions, arg.Now, arg.UserID, arg.KeepID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeSession = `-- name: CloseSession :execrows
UPDATE auth_session SET revoked_at = $1
WHERE id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type CloseSessionParams struct {
	Now    pgtype.Timestamptz
	ID     string
	UserID string
}

// CloseSession closes one of the person's sessions and reports whether one
// was open.
func (q *Queries) CloseSession(ctx context.Context, arg CloseSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeSession, arg.Now, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, created_at, expires_at, revoked_at FROM auth_session WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec

INSERT INTO auth_session (id, user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	ID        string
	UserID    string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

// A session a sign-in opened (ADR 0267).
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const listUnclosedSessions = `-- name: ListUnclosedSessions :many
SELECT id, user_id, created_at, expires_at, revoked_at FROM auth_session
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > $2
ORDER BY created_at DESC, id DESC
`

type ListUnclosedSessionsParams struct {
	UserID string
	Now    pgtype.Timestamptz
}

// ListUnclosedSessions returns a person's sessions that are neither closed by
// themselves nor expired, newest first. The anchor is applied by the caller,
// as the verification applies it.
func (q *Queries) ListUnclosedSessions(ctx context.Context, arg ListUnclosedSessionsParams) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listUnclosedSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSessions = `-- name: PruneSessions :exec
DELETE FROM auth_session WHERE user_id = $1 AND expires_at <= $2
`

type PruneSessionsParams struct {
	UserID string
	Now    pgtype.Timestamptz
}

// PruneSessions forgets a person's sessions that expired, at their next
// sign-in, so the table holds what can still be used and nothing a job has to
// sweep.
func (q *Queries) PruneSessions(ctx context.Context, arg PruneSessionsParams) error {
	_, err := q.db.Exec(ctx, pruneSessions, arg.UserID, arg.Now)
	return err
}
