// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM auth_user
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR email = $1::text)
  AND ($2::text IS NULL OR $2::text = ANY(scopes))
`

type CountUsersParams struct {
	Email *string
	Scope *string
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Email, arg.Scope)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, first_name, last_name, avatar_url, scopes, metadata, created_at, updated_at, deleted_at FROM auth_user
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Scopes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, avatar_url, scopes, metadata, created_at, updated_at, deleted_at FROM auth_user
WHERE email = $1 AND deleted_at IS NULL
`

// GetUserByEmail e-postaya göre CANLI kullanıcıyı döner.
//
// Giriş akışının ilk adımıdır. Benzersizlik kısmi indeksle garanti altındadır,
// bu yüzden sonuç en fazla bir satırdır.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Scopes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one

INSERT INTO auth_user (id, email, first_name, last_name, avatar_url, scopes, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, email, first_name, last_name, avatar_url, scopes, metadata, created_at, updated_at, deleted_at
`

type InsertUserParams struct {
	ID        string
	Email     string
	FirstName string
	LastName  string
	AvatarUrl string
	Scopes    []string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

// auth_user sorguları. Tüm okumalar deleted_at IS NULL filtresi uygular.
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Scopes,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Scopes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, first_name, last_name, avatar_url, scopes, metadata, created_at, updated_at, deleted_at FROM auth_user
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR email = $1::text)
  AND ($2::text IS NULL OR $2::text = ANY(scopes))
ORDER BY created_at DESC, id DESC
LIMIT $4::int OFFSET $3::int
`

type ListUsersParams struct {
	Email *string
	Scope *string
	Off   int32
	Lim   int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]AuthUser, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Email,
		arg.Scope,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthUser{}
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.Scopes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, email, first_name, last_name, avatar_url, scopes, metadata, created_at, updated_at, deleted_at FROM auth_user
WHERE id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListUsersByIDs(ctx context.Context, ids []string) ([]AuthUser, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthUser{}
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.Scopes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteIdentitiesOfUser = `-- name: SoftDeleteIdentitiesOfUser :exec
UPDATE auth_identity
SET deleted_at = $2, updated_at = $2
WHERE user_id = $1 AND deleted_at IS NULL
`

type SoftDeleteIdentitiesOfUserParams struct {
	UserID    string
	DeletedAt pgtype.Timestamptz
}

// SoftDeleteIdentitiesOfUser kullanıcı silinirken kimliklerini de siler.
//
// Foreign key ON DELETE CASCADE yalnızca GERÇEK silmede çalışır; yumuşak silme
// bir UPDATE olduğu için kimlikleri kendiliğinden götürmez. Silinmiş bir
// kullanıcının canlı kimliği geride kalsaydı, o kullanıcı SİLİNDİKTEN SONRA DA
// giriş yapabilirdi — bu, modülün en pahalı sessiz hatası olurdu.
func (q *Queries) SoftDeleteIdentitiesOfUser(ctx context.Context, arg SoftDeleteIdentitiesOfUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteIdentitiesOfUser, arg.UserID, arg.DeletedAt)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE auth_user
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteUserParams struct {
	ID        string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, arg.ID, arg.DeletedAt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const syncIdentityProviderIdentity = `-- name: SyncIdentityProviderIdentity :exec
UPDATE auth_identity
SET provider_identity = $3, updated_at = $4
WHERE user_id = $1 AND provider = $2 AND deleted_at IS NULL
`

type SyncIdentityProviderIdentityParams struct {
	UserID           string
	Provider         string
	ProviderIdentity string
	UpdatedAt        pgtype.Timestamptz
}

// SyncIdentityProviderIdentity kullanıcının e-postası değiştiğinde giriş
// kimliğini de günceller.
//
// İkisi ayrı sütunlarda durur ama AYNI şeyi ifade eder: kullanıcının giriş
// adresi. Senkron tutulmasalardı, e-postasını değiştiren bir kullanıcı eski
// adresiyle giriş yapmaya devam eder ve (provider, provider_identity)
// benzersizlik indeksi artık kimsenin kullanmadığı bir adresi işgal ederdi.
// Çağrı, kullanıcı güncellemesiyle AYNI işlemdedir.
func (q *Queries) SyncIdentityProviderIdentity(ctx context.Context, arg SyncIdentityProviderIdentityParams) error {
	_, err := q.db.Exec(ctx, syncIdentityProviderIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderIdentity,
		arg.UpdatedAt,
	)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE auth_user SET
    email      = COALESCE($1::text, email),
    first_name = COALESCE($2::text, first_name),
    last_name  = COALESCE($3::text, last_name),
    avatar_url = COALESCE($4::text, avatar_url),
    scopes     = COALESCE($5::text[], scopes),
    metadata   = COALESCE($6::jsonb, metadata),
    updated_at = $7
WHERE id = $8 AND deleted_at IS NULL
RETURNING id, email, first_name, last_name, avatar_url, scopes, metadata, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Email     *string
	FirstName *string
	LastName  *string
	AvatarUrl *string
	Scopes    []string
	Metadata  []byte
	UpdatedAt pgtype.Timestamptz
	ID        string
}

// UpdateUser verilmeyen alanları OLDUĞU GİBİ bırakır.
//
// COALESCE ile yazılan bu kısmi güncelleme, "alan gönderilmedi" ile "alan boşa
// çekildi" ayrımını korur: NULL parametre eski değeri saklar, boş dize gerçek
// bir temizlemedir.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Scopes,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ID,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Scopes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
