// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attribute.sql

package productdb

import (
	"context"
)

const countAttributeOptions = `-- name: CountAttributeOptions :one
SELECT count(*) FROM product_attribute_option WHERE attribute_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAttributeOptions(ctx context.Context, attributeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAttributeOptions, attributeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAttributes = `-- name: CountAttributes :one
SELECT count(*) FROM product_attribute WHERE deleted_at IS NULL
`

func (q *Queries) CountAttributes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAttributes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProductAttributeValues = `-- name: DeleteProductAttributeValues :exec
DELETE FROM product_attribute_value WHERE product_id = $1
`

func (q *Queries) DeleteProductAttributeValues(ctx context.Context, productID string) error {
	_, err := q.db.Exec(ctx, deleteProductAttributeValues, productID)
	return err
}

const getAttribute = `-- name: GetAttribute :one
SELECT id, handle, title, kind, rank, created_at, updated_at, deleted_at FROM product_attribute WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAttribute(ctx context.Context, id string) (ProductAttribute, error) {
	row := q.db.QueryRow(ctx, getAttribute, id)
	var i ProductAttribute
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Kind,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAttribute = `-- name: InsertAttribute :one

INSERT INTO product_attribute (id, handle, title, kind, rank)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, handle, title, kind, rank, created_at, updated_at, deleted_at
`

type InsertAttributeParams struct {
	ID     string
	Handle string
	Title  string
	Kind   string
	Rank   int32
}

// Typed product attributes (ADR 0219).
func (q *Queries) InsertAttribute(ctx context.Context, arg InsertAttributeParams) (ProductAttribute, error) {
	row := q.db.QueryRow(ctx, insertAttribute,
		arg.ID,
		arg.Handle,
		arg.Title,
		arg.Kind,
		arg.Rank,
	)
	var i ProductAttribute
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Kind,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAttributeOption = `-- name: InsertAttributeOption :one
INSERT INTO product_attribute_option (id, attribute_id, handle, value, rank)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, attribute_id, handle, value, rank, created_at, deleted_at
`

type InsertAttributeOptionParams struct {
	ID          string
	AttributeID string
	Handle      string
	Value       string
	Rank        int32
}

func (q *Queries) InsertAttributeOption(ctx context.Context, arg InsertAttributeOptionParams) (ProductAttributeOption, error) {
	row := q.db.QueryRow(ctx, insertAttributeOption,
		arg.ID,
		arg.AttributeID,
		arg.Handle,
		arg.Value,
		arg.Rank,
	)
	var i ProductAttributeOption
	err := row.Scan(
		&i.ID,
		&i.AttributeID,
		&i.Handle,
		&i.Value,
		&i.Rank,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertProductAttributeValue = `-- name: InsertProductAttributeValue :exec
INSERT INTO product_attribute_value (product_id, attribute_id, option_id, number_value, boolean_value)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProductAttributeValueParams struct {
	ProductID    string
	AttributeID  string
	OptionID     *string
	NumberValue  *float64
	BooleanValue *bool
}

func (q *Queries) InsertProductAttributeValue(ctx context.Context, arg InsertProductAttributeValueParams) error {
	_, err := q.db.Exec(ctx, insertProductAttributeValue,
		arg.ProductID,
		arg.AttributeID,
		arg.OptionID,
		arg.NumberValue,
		arg.BooleanValue,
	)
	return err
}

const listAttributeOptions = `-- name: ListAttributeOptions :many
SELECT o.id, o.attribute_id, o.handle, o.value, o.rank, o.created_at, o.deleted_at FROM product_attribute_option o
WHERE o.attribute_id = ANY($1::text[]) AND o.deleted_at IS NULL
ORDER BY o.attribute_id, o.rank, o.handle
`

func (q *Queries) ListAttributeOptions(ctx context.Context, attributeIds []string) ([]ProductAttributeOption, error) {
	rows, err := q.db.Query(ctx, listAttributeOptions, attributeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductAttributeOption{}
	for rows.Next() {
		var i ProductAttributeOption
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Handle,
			&i.Value,
			&i.Rank,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributes = `-- name: ListAttributes :many
SELECT id, handle, title, kind, rank, created_at, updated_at, deleted_at FROM product_attribute
WHERE deleted_at IS NULL
ORDER BY rank, handle
LIMIT $1
`

func (q *Queries) ListAttributes(ctx context.Context, limit int32) ([]ProductAttribute, error) {
	rows, err := q.db.Query(ctx, listAttributes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductAttribute{}
	for rows.Next() {
		var i ProductAttribute
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.Title,
			&i.Kind,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributeValues = `-- name: ListProductAttributeValues :many
SELECT v.product_id, a.id AS attribute_id, a.handle AS attribute_handle, a.title AS attribute_title,
       a.kind, v.option_id, o.handle AS option_handle, o.value AS option_value,
       v.number_value, v.boolean_value
FROM product_attribute_value v
JOIN product_attribute a ON a.id = v.attribute_id AND a.deleted_at IS NULL
LEFT JOIN product_attribute_option o ON o.id = v.option_id
WHERE v.product_id = ANY($1::text[])
  AND (v.option_id IS NULL OR o.deleted_at IS NULL)
ORDER BY v.product_id, a.rank, a.handle, o.rank, o.handle
`

type ListProductAttributeValuesRow struct {
	ProductID       string
	AttributeID     string
	AttributeHandle string
	AttributeTitle  string
	Kind            string
	OptionID        *string
	OptionHandle    *string
	OptionValue     *string
	NumberValue     *float64
	BooleanValue    *bool
}

// ListProductAttributeValues reads the values of many products whose
// definition and option still stand, in the definitions' order.
func (q *Queries) ListProductAttributeValues(ctx context.Context, productIds []string) ([]ListProductAttributeValuesRow, error) {
	rows, err := q.db.Query(ctx, listProductAttributeValues, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductAttributeValuesRow{}
	for rows.Next() {
		var i ListProductAttributeValuesRow
		if err := rows.Scan(
			&i.ProductID,
			&i.AttributeID,
			&i.AttributeHandle,
			&i.AttributeTitle,
			&i.Kind,
			&i.OptionID,
			&i.OptionHandle,
			&i.OptionValue,
			&i.NumberValue,
			&i.BooleanValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAttribute = `-- name: SoftDeleteAttribute :execrows
UPDATE product_attribute SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAttribute(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAttribute, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteAttributeOption = `-- name: SoftDeleteAttributeOption :execrows
UPDATE product_attribute_option SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAttributeOption(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAttributeOption, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAttribute = `-- name: UpdateAttribute :one
UPDATE product_attribute
SET title = COALESCE($1::text, title),
    rank = COALESCE($2::int, rank),
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, handle, title, kind, rank, created_at, updated_at, deleted_at
`

type UpdateAttributeParams struct {
	Title *string
	Rank  *int32
	ID    string
}

// UpdateAttribute changes a definition's title and order; its handle and kind
// are what its values and every storefront filter were written against.
func (q *Queries) UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (ProductAttribute, error) {
	row := q.db.QueryRow(ctx, updateAttribute, arg.Title, arg.Rank, arg.ID)
	var i ProductAttribute
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Kind,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
