// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package productdb

import (
	"context"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM product
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR collection_id = $2::text)
  AND ($3::text IS NULL OR handle = $3::text)
  AND ($4::text IS NULL OR title ILIKE '%' || $4::text || '%')
`

type CountProductsParams struct {
	Status       *string
	CollectionID *string
	Handle       *string
	Search       *string
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts,
		arg.Status,
		arg.CollectionID,
		arg.Handle,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO product_image (id, product_id, url, rank, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, url, rank, metadata, created_at, updated_at, deleted_at
`

type CreateImageParams struct {
	ID        string
	ProductID string
	Url       string
	Rank      int32
	Metadata  []byte
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.ID,
		arg.ProductID,
		arg.Url,
		arg.Rank,
		arg.Metadata,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.Rank,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO product (
    id, handle, title, subtitle, description, thumbnail, status,
    is_giftcard, discountable, weight, length, height, width,
    material, origin_country, collection_id, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17
)
RETURNING id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	ID            string
	Handle        string
	Title         string
	Subtitle      *string
	Description   *string
	Thumbnail     *string
	Status        string
	IsGiftcard    bool
	Discountable  bool
	Weight        *int32
	Length        *int32
	Height        *int32
	Width         *int32
	Material      *string
	OriginCountry *string
	CollectionID  *string
	Metadata      []byte
}

// Ürün sorguları.
//
// Ortak kurallar:
//   - Her okuma "deleted_at IS NULL" filtresi uygular (plan Bölüm 8: soft delete).
//   - Listeleme sırası (created_at DESC, id DESC) sabittir; ikinci anahtar,
//     aynı milisaniyede oluşmuş iki kaydın sayfalar arasında yer değiştirmesini
//     engeller.
//   - Zaman damgalarını veritabanı üretir (now()); tek saat kaynağı budur.
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Handle,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Thumbnail,
		arg.Status,
		arg.IsGiftcard,
		arg.Discountable,
		arg.Weight,
		arg.Length,
		arg.Height,
		arg.Width,
		arg.Material,
		arg.OriginCountry,
		arg.CollectionID,
		arg.Metadata,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.Weight,
		&i.Length,
		&i.Height,
		&i.Width,
		&i.Material,
		&i.OriginCountry,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteImagesByProduct = `-- name: DeleteImagesByProduct :exec
UPDATE product_image SET deleted_at = now(), updated_at = now()
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteImagesByProduct(ctx context.Context, productID string) error {
	_, err := q.db.Exec(ctx, deleteImagesByProduct, productID)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at FROM product
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.Weight,
		&i.Length,
		&i.Height,
		&i.Width,
		&i.Material,
		&i.OriginCountry,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByHandle = `-- name: GetProductByHandle :one
SELECT id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at FROM product
WHERE handle = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByHandle(ctx context.Context, handle string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByHandle, handle)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.Weight,
		&i.Length,
		&i.Height,
		&i.Width,
		&i.Material,
		&i.OriginCountry,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listImagesByProductIDs = `-- name: ListImagesByProductIDs :many
SELECT id, product_id, url, rank, metadata, created_at, updated_at, deleted_at FROM product_image
WHERE product_id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY product_id, rank, id
`

func (q *Queries) ListImagesByProductIDs(ctx context.Context, dollar_1 []string) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listImagesByProductIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.Rank,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at FROM product
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR collection_id = $2::text)
  AND ($3::text IS NULL OR handle = $3::text)
  AND ($4::text IS NULL OR title ILIKE '%' || $4::text || '%')
ORDER BY created_at DESC, id DESC
LIMIT $6::int OFFSET $5::int
`

type ListProductsParams struct {
	Status       *string
	CollectionID *string
	Handle       *string
	Search       *string
	Off          int32
	Lim          int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Status,
		arg.CollectionID,
		arg.Handle,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.Weight,
			&i.Length,
			&i.Height,
			&i.Width,
			&i.Material,
			&i.OriginCountry,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByIDs = `-- name: ListProductsByIDs :many
SELECT id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at FROM product
WHERE id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProductsByIDs(ctx context.Context, dollar_1 []string) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.Weight,
			&i.Length,
			&i.Height,
			&i.Width,
			&i.Material,
			&i.OriginCountry,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantIDsByProduct = `-- name: ListVariantIDsByProduct :many
SELECT id FROM product_variant
WHERE product_id = $1 AND deleted_at IS NULL
ORDER BY rank, id
`

// Ürün silinirken varyantların link'leri (fiyat/stok) temizlenir; bunun için
// silinmeden ÖNCE kimlikler okunur.
func (q *Queries) ListVariantIDsByProduct(ctx context.Context, productID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listVariantIDsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOptionsByProduct = `-- name: SoftDeleteOptionsByProduct :execrows
UPDATE product_option SET deleted_at = now(), updated_at = now()
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOptionsByProduct(ctx context.Context, productID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOptionsByProduct, productID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE product SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteVariantsByProduct = `-- name: SoftDeleteVariantsByProduct :execrows
UPDATE product_variant SET deleted_at = now(), updated_at = now()
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteVariantsByProduct(ctx context.Context, productID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteVariantsByProduct, productID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product SET
    handle         = COALESCE($1::text, handle),
    title          = COALESCE($2::text, title),
    subtitle       = COALESCE($3::text, subtitle),
    description    = COALESCE($4::text, description),
    thumbnail      = COALESCE($5::text, thumbnail),
    status         = COALESCE($6::text, status),
    discountable   = COALESCE($7::boolean, discountable),
    weight         = COALESCE($8::int, weight),
    length         = COALESCE($9::int, length),
    height         = COALESCE($10::int, height),
    width          = COALESCE($11::int, width),
    material       = COALESCE($12::text, material),
    origin_country = COALESCE($13::text, origin_country),
    collection_id  = COALESCE($14::text, collection_id),
    metadata       = COALESCE($15::jsonb, metadata),
    updated_at     = now()
WHERE id = $16 AND deleted_at IS NULL
RETURNING id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	Handle        *string
	Title         *string
	Subtitle      *string
	Description   *string
	Thumbnail     *string
	Status        *string
	Discountable  *bool
	Weight        *int32
	Length        *int32
	Height        *int32
	Width         *int32
	Material      *string
	OriginCountry *string
	CollectionID  *string
	Metadata      []byte
	ID            string
}

// COALESCE kalıbı: NULL geçilen alan DEĞİŞMEZ. Bunun bilinen sınırı, bir alanı
// NULL'a çekmenin (örn. subtitle'ı silmenin) bu uçtan yapılamamasıdır; PATCH
// sözleşmesi "verilmeyen alan korunur" olarak belgelenmiştir.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Handle,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Thumbnail,
		arg.Status,
		arg.Discountable,
		arg.Weight,
		arg.Length,
		arg.Height,
		arg.Width,
		arg.Material,
		arg.OriginCountry,
		arg.CollectionID,
		arg.Metadata,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.Weight,
		&i.Length,
		&i.Height,
		&i.Width,
		&i.Material,
		&i.OriginCountry,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
