// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package productdb

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO product_image (id, product_id, url, rank, metadata, upload_id, alt_text)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, product_id, url, rank, metadata, created_at, updated_at, deleted_at, upload_id, alt_text
`

type CreateImageParams struct {
	ID        string
	ProductID string
	Url       string
	Rank      int32
	Metadata  []byte
	UploadID  *string
	AltText   string
}

// upload_id may be NULL and it is not an error: an image whose address was
// never uploaded here (an imported catalog, a hand-typed CDN address) has no
// upload record to point at. See migration 000002.
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.ID,
		arg.ProductID,
		arg.Url,
		arg.Rank,
		arg.Metadata,
		arg.UploadID,
		arg.AltText,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.Rank,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UploadID,
		&i.AltText,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO product (
    id, handle, title, subtitle, description, thumbnail, status,
    is_giftcard, discountable, weight, length, height, width,
    material, origin_country, collection_id, type_id, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18
)
RETURNING id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at, type_id
`

type CreateProductParams struct {
	ID            string
	Handle        string
	Title         string
	Subtitle      *string
	Description   *string
	Thumbnail     *string
	Status        string
	IsGiftcard    bool
	Discountable  bool
	Weight        *int32
	Length        *int32
	Height        *int32
	Width         *int32
	Material      *string
	OriginCountry *string
	CollectionID  *string
	TypeID        *string
	Metadata      []byte
}

// Product queries.
//
// Shared rules:
//   - Every read applies the "deleted_at IS NULL" filter (plan Section 8: soft
//     delete).
//   - The listing order (created_at DESC, id DESC) is fixed; the second key keeps
//     two records created in the same millisecond from swapping places between
//     pages.
//   - The database produces the timestamps (now()); that is the single clock
//     source.
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Handle,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Thumbnail,
		arg.Status,
		arg.IsGiftcard,
		arg.Discountable,
		arg.Weight,
		arg.Length,
		arg.Height,
		arg.Width,
		arg.Material,
		arg.OriginCountry,
		arg.CollectionID,
		arg.TypeID,
		arg.Metadata,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.Weight,
		&i.Length,
		&i.Height,
		&i.Width,
		&i.Material,
		&i.OriginCountry,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TypeID,
	)
	return i, err
}

const deleteImagesByProduct = `-- name: DeleteImagesByProduct :exec
UPDATE product_image SET deleted_at = now(), updated_at = now()
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteImagesByProduct(ctx context.Context, productID string) error {
	_, err := q.db.Exec(ctx, deleteImagesByProduct, productID)
	return err
}

const getImageOfProduct = `-- name: GetImageOfProduct :one
SELECT id, product_id, url, rank, metadata, created_at, updated_at, deleted_at, upload_id, alt_text FROM product_image
WHERE id = $1 AND product_id = $2 AND deleted_at IS NULL
`

type GetImageOfProductParams struct {
	ID        string
	ProductID string
}

// Both identifiers are in the WHERE clause and that is the point: the route
// carries the product's id and the image's, and reading only the image's would
// let a caller edit another product's picture by naming their own product.
func (q *Queries) GetImageOfProduct(ctx context.Context, arg GetImageOfProductParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getImageOfProduct, arg.ID, arg.ProductID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.Rank,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UploadID,
		&i.AltText,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at, type_id FROM product
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.Weight,
		&i.Length,
		&i.Height,
		&i.Width,
		&i.Material,
		&i.OriginCountry,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TypeID,
	)
	return i, err
}

const getProductByHandle = `-- name: GetProductByHandle :one
SELECT id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at, type_id FROM product
WHERE handle = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByHandle(ctx context.Context, handle string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByHandle, handle)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.Weight,
		&i.Length,
		&i.Height,
		&i.Width,
		&i.Material,
		&i.OriginCountry,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TypeID,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at, type_id FROM product
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// GetProductForUpdate reads the product WITH A ROW LOCK; it is meaningful only
// inside a transaction.
//
// Checking that the owner exists before writing a variant is not enough on its
// own: because deletion is SOFT, the foreign key does not close the gap, and if a
// concurrent deletion slips in between the check and the INSERT, a variant whose
// owner has been deleted comes into being. The lock PUTS the deletion IN SEQUENCE
// with this transaction: if the deletion comes first, no row is found here; if it
// comes second, the variant is caught by the deletion's cleanup.
func (q *Queries) GetProductForUpdate(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.Weight,
		&i.Length,
		&i.Height,
		&i.Width,
		&i.Material,
		&i.OriginCountry,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TypeID,
	)
	return i, err
}

const listImagesByIDs = `-- name: ListImagesByIDs :many
SELECT id, product_id, url, rank, metadata, created_at, updated_at, deleted_at, upload_id, alt_text FROM product_image
WHERE id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY product_id, rank, id
`

// The reverse read of the image/upload binding ends here: the link service
// answers "which images use this upload" with IDS, and the records themselves
// are read in a SINGLE query rather than one per id.
//
// An id with no live row is simply not returned. That is not an error but the
// residue the write order accepts: the binding is written before the image, so
// a create that failed afterwards can leave a link row for an image that never
// existed (see service/links.go).
func (q *Queries) ListImagesByIDs(ctx context.Context, dollar_1 []string) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listImagesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.Rank,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UploadID,
			&i.AltText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByProductIDs = `-- name: ListImagesByProductIDs :many
SELECT id, product_id, url, rank, metadata, created_at, updated_at, deleted_at, upload_id, alt_text FROM product_image
WHERE product_id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY product_id, rank, id
`

func (q *Queries) ListImagesByProductIDs(ctx context.Context, dollar_1 []string) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listImagesByProductIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.Rank,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UploadID,
			&i.AltText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByIDs = `-- name: ListProductsByIDs :many

SELECT id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at, type_id FROM product
WHERE id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

// ListProducts and CountProducts are NOT HERE; they sit in
// repository/saleschannel.go as hand-written SQL.
//
// The reason is not visible from this file alone: for the sales channel filter
// the two queries carry an EXISTS/NOT EXISTS condition against the link table
// (link_product_sales_channel), and that table is NOT in this module's
// migrations — core/link creates its schema at run time. Because sqlc reads the
// schema from this directory, it refuses generation with "relation does not
// exist". For the full rationale, and for why the filter is applied in the
// database, see repository/saleschannel.go.
func (q *Queries) ListProductsByIDs(ctx context.Context, dollar_1 []string) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.Weight,
			&i.Length,
			&i.Height,
			&i.Width,
			&i.Material,
			&i.OriginCountry,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantIDsByProduct = `-- name: ListVariantIDsByProduct :many
SELECT id FROM product_variant
WHERE product_id = $1 AND deleted_at IS NULL
ORDER BY rank, id
`

// When a product is deleted the links of its variants (price/inventory) are
// cleaned up; for that, the IDs are read BEFORE the deletion.
func (q *Queries) ListVariantIDsByProduct(ctx context.Context, productID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listVariantIDsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteImage = `-- name: SoftDeleteImage :execrows
UPDATE product_image SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND product_id = $2 AND deleted_at IS NULL
`

type SoftDeleteImageParams struct {
	ID        string
	ProductID string
}

func (q *Queries) SoftDeleteImage(ctx context.Context, arg SoftDeleteImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteImage, arg.ID, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteOptionsByProduct = `-- name: SoftDeleteOptionsByProduct :execrows
UPDATE product_option SET deleted_at = now(), updated_at = now()
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOptionsByProduct(ctx context.Context, productID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOptionsByProduct, productID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE product SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteVariantsByProduct = `-- name: SoftDeleteVariantsByProduct :execrows
UPDATE product_variant SET deleted_at = now(), updated_at = now()
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteVariantsByProduct(ctx context.Context, productID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteVariantsByProduct, productID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE product_image SET
    alt_text   = COALESCE($1::text, alt_text),
    rank       = COALESCE($2::int, rank),
    metadata   = COALESCE($3::jsonb, metadata),
    updated_at = now()
WHERE id = $4 AND product_id = $5 AND deleted_at IS NULL
RETURNING id, product_id, url, rank, metadata, created_at, updated_at, deleted_at, upload_id, alt_text
`

type UpdateImageParams struct {
	AltText   *string
	Rank      *int32
	Metadata  []byte
	ID        string
	ProductID string
}

// The COALESCE pattern, as in UpdateProduct: a field passed as NULL DOES NOT
// CHANGE. The address is NOT here — an image's url and its upload binding were
// written together, and letting the address move on its own would put the row's
// own column at odds with the link record (see migration 000002).
//
// alt_text is in it, and it is the reason this query exists: until it did, a
// wrong alt text could only be corrected by deleting the product.
func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, updateImage,
		arg.AltText,
		arg.Rank,
		arg.Metadata,
		arg.ID,
		arg.ProductID,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.Rank,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UploadID,
		&i.AltText,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product SET
    handle         = COALESCE($1::text, handle),
    title          = COALESCE($2::text, title),
    subtitle       = COALESCE($3::text, subtitle),
    description    = COALESCE($4::text, description),
    thumbnail      = COALESCE($5::text, thumbnail),
    status         = COALESCE($6::text, status),
    discountable   = COALESCE($7::boolean, discountable),
    weight         = COALESCE($8::int, weight),
    length         = COALESCE($9::int, length),
    height         = COALESCE($10::int, height),
    width          = COALESCE($11::int, width),
    material       = COALESCE($12::text, material),
    origin_country = COALESCE($13::text, origin_country),
    collection_id  = COALESCE($14::text, collection_id),
    type_id        = COALESCE($15::text, type_id),
    metadata       = COALESCE($16::jsonb, metadata),
    updated_at     = now()
WHERE id = $17 AND deleted_at IS NULL
RETURNING id, handle, title, subtitle, description, thumbnail, status, is_giftcard, discountable, weight, length, height, width, material, origin_country, collection_id, metadata, created_at, updated_at, deleted_at, type_id
`

type UpdateProductParams struct {
	Handle        *string
	Title         *string
	Subtitle      *string
	Description   *string
	Thumbnail     *string
	Status        *string
	Discountable  *bool
	Weight        *int32
	Length        *int32
	Height        *int32
	Width         *int32
	Material      *string
	OriginCountry *string
	CollectionID  *string
	TypeID        *string
	Metadata      []byte
	ID            string
}

// The COALESCE pattern: a field passed as NULL DOES NOT CHANGE. Its known limit
// is that setting a field back to NULL (clearing the subtitle, say) cannot be
// done through this endpoint; the PATCH contract is documented as "a field that
// is not supplied is preserved".
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Handle,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Thumbnail,
		arg.Status,
		arg.Discountable,
		arg.Weight,
		arg.Length,
		arg.Height,
		arg.Width,
		arg.Material,
		arg.OriginCountry,
		arg.CollectionID,
		arg.TypeID,
		arg.Metadata,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.Weight,
		&i.Length,
		&i.Height,
		&i.Width,
		&i.Material,
		&i.OriginCountry,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TypeID,
	)
	return i, err
}
