// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notificationdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationDelivery struct {
	ID         string
	Template   string
	Channel    string
	Reference  string
	ProviderID string
	Status     string
	Error      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
