// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_deliveries.sql

package notificationdb

import (
	"context"
)

const claimNotificationDelivery = `-- name: ClaimNotificationDelivery :one

INSERT INTO notification_deliveries (
    id, template, channel, reference, provider_id, status
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (template, reference) DO NOTHING
RETURNING id, template, channel, reference, provider_id, status, error, created_at, updated_at
`

type ClaimNotificationDeliveryParams struct {
	ID         string
	Template   string
	Channel    string
	Reference  string
	ProviderID string
	Status     string
}

// notification_deliveries sorguları — TESLİM GÜNLÜĞÜ.
//
// Günlük iki adımda yazılır: gönderimden ÖNCE kayıt açılır (Claim), gönderimden
// SONRA sonucu yazılır (Finish). Tek adımda yazmak — yani önce gönderip sonra
// kaydetmek — mükerrer bildirime kapı açardı: iki eşzamanlı işleyici de
// sağlayıcıya gider, benzersizlik ihlali ancak İKİ e-posta gittikten sonra
// görünürdü.
// ClaimNotificationDelivery kaydı yalnızca o (şablon, referans) çifti HENÜZ
// KULLANILMAMIŞSA yazar.
//
// Çakışma hâlinde satır DÖNMEZ (pgx.ErrNoRows) ve bu bir hata değildir:
// çağıran o zaman gönderimi ATLAR. "Önce oku, yoksa yaz" iki adımı arasına
// giren eşzamanlı bir çağrı benzersiz indekse çarpardı; ON CONFLICT DO NOTHING
// yarışı tek deyime indirir ve kazananı veritabanı seçer.
func (q *Queries) ClaimNotificationDelivery(ctx context.Context, arg ClaimNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, claimNotificationDelivery,
		arg.ID,
		arg.Template,
		arg.Channel,
		arg.Reference,
		arg.ProviderID,
		arg.Status,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.Template,
		&i.Channel,
		&i.Reference,
		&i.ProviderID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countNotificationDeliveries = `-- name: CountNotificationDeliveries :one
SELECT COUNT(*) FROM notification_deliveries
WHERE ($1::text IS NULL OR reference = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
`

type CountNotificationDeliveriesParams struct {
	Reference *string
	Status    *string
}

// CountNotificationDeliveries sayfalama zarfının toplam sayısını verir ve
// ListNotificationDeliveries ile AYNI süzgeçleri uygular; ikisi birlikte
// değiştirilmelidir.
//
// Toplam, satırlarla birlikte dönen bir pencere fonksiyonundan okunamaz:
// aralık dışı bir sayfada hiç satır dönmez, pencere değerlendirilmez ve toplam
// 0 görünürdü. Toplam sayfanın değil SÜZGECİN sayısıdır.
func (q *Queries) CountNotificationDeliveries(ctx context.Context, arg CountNotificationDeliveriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationDeliveries, arg.Reference, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishNotificationDelivery = `-- name: FinishNotificationDelivery :one
UPDATE notification_deliveries
SET status     = $2,
    error      = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, template, channel, reference, provider_id, status, error, created_at, updated_at
`

type FinishNotificationDeliveryParams struct {
	ID     string
	Status string
	Error  string
}

// FinishNotificationDelivery gönderim denemesinin sonucunu yazar.
//
// Durum MUTLAK değerle yazılır, artımlı bir geçişle değil: yazan kod sonucu
// elinde tutar ve okuduğu satıra göre karar vermez.
func (q *Queries) FinishNotificationDelivery(ctx context.Context, arg FinishNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, finishNotificationDelivery, arg.ID, arg.Status, arg.Error)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.Template,
		&i.Channel,
		&i.Reference,
		&i.ProviderID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationDelivery = `-- name: GetNotificationDelivery :one
SELECT id, template, channel, reference, provider_id, status, error, created_at, updated_at FROM notification_deliveries
WHERE id = $1
`

func (q *Queries) GetNotificationDelivery(ctx context.Context, id string) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, getNotificationDelivery, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.Template,
		&i.Channel,
		&i.Reference,
		&i.ProviderID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many
SELECT id, template, channel, reference, provider_id, status, error, created_at, updated_at FROM notification_deliveries
WHERE ($1::text IS NULL OR reference = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4::bigint OFFSET $3::bigint
`

type ListNotificationDeliveriesParams struct {
	Reference *string
	Status    *string
	RowOffset int64
	RowLimit  int64
}

func (q *Queries) ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listNotificationDeliveries,
		arg.Reference,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.Template,
			&i.Channel,
			&i.Reference,
			&i.ProviderID,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
