// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_method_revise.sql

package promotiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reviseMethodValue = `-- name: ReviseMethodValue :one
UPDATE promotion_application_method
SET value      = $1::bigint,
    updated_at = $2
WHERE promotion_id = $3
  AND deleted_at IS NULL
  AND type = $4::text
  AND value = $5::bigint
RETURNING id, promotion_id, type, target_type, allocation, value, max_quantity, currency_code, created_at, updated_at, deleted_at, buy_quantity, apply_to_quantity
`

type ReviseMethodValueParams struct {
	Value       int64
	UpdatedAt   pgtype.Timestamptz
	PromotionID string
	ReadType    string
	ReadValue   int64
}

// ReviseMethodValue writes the discount's value only while the method is
// still of the type and the value the caller read (ADR 0338): one
// conditional UPDATE, so a change made meanwhile is never written over. The
// type, the target, the allocation, the quantities and the currency are not
// among what it writes.
func (q *Queries) ReviseMethodValue(ctx context.Context, arg ReviseMethodValueParams) (PromotionApplicationMethod, error) {
	row := q.db.QueryRow(ctx, reviseMethodValue,
		arg.Value,
		arg.UpdatedAt,
		arg.PromotionID,
		arg.ReadType,
		arg.ReadValue,
	)
	var i PromotionApplicationMethod
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.Type,
		&i.TargetType,
		&i.Allocation,
		&i.Value,
		&i.MaxQuantity,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BuyQuantity,
		&i.ApplyToQuantity,
	)
	return i, err
}
