// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_method.sql

package promotiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApplicationMethod = `-- name: GetApplicationMethod :one
SELECT id, promotion_id, type, target_type, allocation, value, max_quantity, currency_code, created_at, updated_at, deleted_at, buy_quantity, apply_to_quantity FROM promotion_application_method
WHERE promotion_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetApplicationMethod(ctx context.Context, promotionID string) (PromotionApplicationMethod, error) {
	row := q.db.QueryRow(ctx, getApplicationMethod, promotionID)
	var i PromotionApplicationMethod
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.Type,
		&i.TargetType,
		&i.Allocation,
		&i.Value,
		&i.MaxQuantity,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BuyQuantity,
		&i.ApplyToQuantity,
	)
	return i, err
}

const getApplicationMethodsByPromotions = `-- name: GetApplicationMethodsByPromotions :many
SELECT id, promotion_id, type, target_type, allocation, value, max_quantity, currency_code, created_at, updated_at, deleted_at, buy_quantity, apply_to_quantity FROM promotion_application_method
WHERE promotion_id = ANY ($1::text[]) AND deleted_at IS NULL
ORDER BY promotion_id
`

// GetApplicationMethodsByPromotions returns the methods of ALL the promotions
// entering the computation in one round trip; no query is issued per promotion
// (N+1).
func (q *Queries) GetApplicationMethodsByPromotions(ctx context.Context, promotionIds []string) ([]PromotionApplicationMethod, error) {
	rows, err := q.db.Query(ctx, getApplicationMethodsByPromotions, promotionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromotionApplicationMethod{}
	for rows.Next() {
		var i PromotionApplicationMethod
		if err := rows.Scan(
			&i.ID,
			&i.PromotionID,
			&i.Type,
			&i.TargetType,
			&i.Allocation,
			&i.Value,
			&i.MaxQuantity,
			&i.CurrencyCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.BuyQuantity,
			&i.ApplyToQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteApplicationMethod = `-- name: SoftDeleteApplicationMethod :one
UPDATE promotion_application_method
SET deleted_at = $2, updated_at = $2
WHERE promotion_id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteApplicationMethodParams struct {
	PromotionID string
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) SoftDeleteApplicationMethod(ctx context.Context, arg SoftDeleteApplicationMethodParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteApplicationMethod, arg.PromotionID, arg.DeletedAt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertApplicationMethod = `-- name: UpsertApplicationMethod :one

INSERT INTO promotion_application_method (
    id, promotion_id, type, target_type, allocation, value, max_quantity,
    buy_quantity, apply_to_quantity, currency_code, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11)
ON CONFLICT (promotion_id) WHERE deleted_at IS NULL
DO UPDATE SET
    type              = EXCLUDED.type,
    target_type       = EXCLUDED.target_type,
    allocation        = EXCLUDED.allocation,
    value             = EXCLUDED.value,
    max_quantity      = EXCLUDED.max_quantity,
    buy_quantity      = EXCLUDED.buy_quantity,
    apply_to_quantity = EXCLUDED.apply_to_quantity,
    currency_code     = EXCLUDED.currency_code,
    updated_at        = EXCLUDED.updated_at
RETURNING id, promotion_id, type, target_type, allocation, value, max_quantity, currency_code, created_at, updated_at, deleted_at, buy_quantity, apply_to_quantity
`

type UpsertApplicationMethodParams struct {
	ID              string
	PromotionID     string
	Type            string
	TargetType      string
	Allocation      string
	Value           int64
	MaxQuantity     *int64
	BuyQuantity     *int64
	ApplyToQuantity *int64
	CurrencyCode    *string
	CreatedAt       pgtype.Timestamptz
}

// promotion_application_method queries.
// UpsertApplicationMethod writes the method; if the promotion already has one
// it OVERWRITES it.
//
// The upsert is deliberate: there is at most one method per promotion, and a
// "delete first, then insert" would leave the promotion without a method
// between the two statements — a computation running in that gap would produce
// no discount. The conflict target is the partial unique index; a deleted
// method does not take part in the conflict, which is why the WHERE condition
// here is character for character the index's own.
func (q *Queries) UpsertApplicationMethod(ctx context.Context, arg UpsertApplicationMethodParams) (PromotionApplicationMethod, error) {
	row := q.db.QueryRow(ctx, upsertApplicationMethod,
		arg.ID,
		arg.PromotionID,
		arg.Type,
		arg.TargetType,
		arg.Allocation,
		arg.Value,
		arg.MaxQuantity,
		arg.BuyQuantity,
		arg.ApplyToQuantity,
		arg.CurrencyCode,
		arg.CreatedAt,
	)
	var i PromotionApplicationMethod
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.Type,
		&i.TargetType,
		&i.Allocation,
		&i.Value,
		&i.MaxQuantity,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BuyQuantity,
		&i.ApplyToQuantity,
	)
	return i, err
}
