// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign_revise.sql

package promotiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reviseCampaign = `-- name: ReviseCampaign :one
UPDATE campaign
SET name         = $1::text,
    description  = $2::text,
    starts_at    = $3::timestamptz,
    ends_at      = $4::timestamptz,
    budget_limit = $5::bigint,
    updated_at   = $6
WHERE id = $7
  AND deleted_at IS NULL
  AND name = $8::text
  AND description = $9::text
  AND starts_at IS NOT DISTINCT FROM $10::timestamptz
  AND ends_at IS NOT DISTINCT FROM $11::timestamptz
  AND budget_limit IS NOT DISTINCT FROM $12::bigint
  AND (budget_type = 'none') = ($5::bigint IS NULL)
RETURNING id, name, campaign_identifier, description, starts_at, ends_at, budget_type, budget_limit, budget_used, budget_currency_code, created_at, updated_at, deleted_at
`

type ReviseCampaignParams struct {
	Name            string
	Description     string
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	BudgetLimit     *int64
	UpdatedAt       pgtype.Timestamptz
	ID              string
	ReadName        string
	ReadDescription string
	ReadStartsAt    pgtype.Timestamptz
	ReadEndsAt      pgtype.Timestamptz
	ReadBudgetLimit *int64
}

// ReviseCampaign writes the campaign's name, description, window and budget
// limit only while they are still the ones the caller read (ADR 0331): one
// conditional UPDATE, so a revision made meanwhile is never written over.
//
// The business identifier and the budget's unit are not among them, and
// budget_used stays the redemption flow's. A limit is written only beside a
// budget type and an open one only without, as campaign_budget_none_check
// and the service's budget rule say; a row the statement leaves alone is
// explained by the service from the campaign as it is.
func (q *Queries) ReviseCampaign(ctx context.Context, arg ReviseCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, reviseCampaign,
		arg.Name,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.BudgetLimit,
		arg.UpdatedAt,
		arg.ID,
		arg.ReadName,
		arg.ReadDescription,
		arg.ReadStartsAt,
		arg.ReadEndsAt,
		arg.ReadBudgetLimit,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CampaignIdentifier,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.BudgetType,
		&i.BudgetLimit,
		&i.BudgetUsed,
		&i.BudgetCurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
