// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package promotiondb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID                 string
	Name               string
	CampaignIdentifier string
	Description        string
	StartsAt           pgtype.Timestamptz
	EndsAt             pgtype.Timestamptz
	BudgetType         string
	BudgetLimit        *int64
	BudgetUsed         int64
	BudgetCurrencyCode *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type Promotion struct {
	ID          string
	Code        string
	IsAutomatic bool
	Type        string
	CampaignID  *string
	Status      string
	UsageLimit  *int64
	UsageCount  int64
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type PromotionApplicationMethod struct {
	ID           string
	PromotionID  string
	Type         string
	TargetType   string
	Allocation   string
	Value        int64
	MaxQuantity  *int64
	CurrencyCode *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type PromotionRedemption struct {
	ID           string
	PromotionID  string
	CampaignID   *string
	Reference    string
	Amount       int64
	CurrencyCode string
	BudgetDelta  int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ReleasedAt   pgtype.Timestamptz
}

type PromotionRule struct {
	ID          string
	PromotionID string
	RuleType    string
	Attribute   string
	Operator    string
	RuleValues  []string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}
