// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotion_rule.sql

package promotiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPromotionRule = `-- name: GetPromotionRule :one
SELECT id, promotion_id, rule_type, attribute, operator, rule_values, created_at, updated_at, deleted_at FROM promotion_rule
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPromotionRule(ctx context.Context, id string) (PromotionRule, error) {
	row := q.db.QueryRow(ctx, getPromotionRule, id)
	var i PromotionRule
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.RuleType,
		&i.Attribute,
		&i.Operator,
		&i.RuleValues,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertPromotionRule = `-- name: InsertPromotionRule :one

INSERT INTO promotion_rule (
    id, promotion_id, rule_type, attribute, operator, rule_values,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, promotion_id, rule_type, attribute, operator, rule_values, created_at, updated_at, deleted_at
`

type InsertPromotionRuleParams struct {
	ID          string
	PromotionID string
	RuleType    string
	Attribute   string
	Operator    string
	RuleValues  []string
	CreatedAt   pgtype.Timestamptz
}

// promotion_rule sorguları.
func (q *Queries) InsertPromotionRule(ctx context.Context, arg InsertPromotionRuleParams) (PromotionRule, error) {
	row := q.db.QueryRow(ctx, insertPromotionRule,
		arg.ID,
		arg.PromotionID,
		arg.RuleType,
		arg.Attribute,
		arg.Operator,
		arg.RuleValues,
		arg.CreatedAt,
	)
	var i PromotionRule
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.RuleType,
		&i.Attribute,
		&i.Operator,
		&i.RuleValues,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPromotionRules = `-- name: ListPromotionRules :many
SELECT id, promotion_id, rule_type, attribute, operator, rule_values, created_at, updated_at, deleted_at FROM promotion_rule
WHERE promotion_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListPromotionRules(ctx context.Context, promotionID string) ([]PromotionRule, error) {
	rows, err := q.db.Query(ctx, listPromotionRules, promotionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromotionRule{}
	for rows.Next() {
		var i PromotionRule
		if err := rows.Scan(
			&i.ID,
			&i.PromotionID,
			&i.RuleType,
			&i.Attribute,
			&i.Operator,
			&i.RuleValues,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotionRulesByPromotions = `-- name: ListPromotionRulesByPromotions :many
SELECT id, promotion_id, rule_type, attribute, operator, rule_values, created_at, updated_at, deleted_at FROM promotion_rule
WHERE promotion_id = ANY ($1::text[]) AND deleted_at IS NULL
ORDER BY promotion_id, id
`

// ListPromotionRulesByPromotions hesaplamaya giren TÜM promosyonların
// kurallarını tek turda döner; promosyon başına sorgu (N+1) yapılmaz.
func (q *Queries) ListPromotionRulesByPromotions(ctx context.Context, promotionIds []string) ([]PromotionRule, error) {
	rows, err := q.db.Query(ctx, listPromotionRulesByPromotions, promotionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromotionRule{}
	for rows.Next() {
		var i PromotionRule
		if err := rows.Scan(
			&i.ID,
			&i.PromotionID,
			&i.RuleType,
			&i.Attribute,
			&i.Operator,
			&i.RuleValues,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePromotionRule = `-- name: SoftDeletePromotionRule :one
UPDATE promotion_rule
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeletePromotionRuleParams struct {
	ID        string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeletePromotionRule(ctx context.Context, arg SoftDeletePromotionRuleParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeletePromotionRule, arg.ID, arg.DeletedAt)
	var id string
	err := row.Scan(&id)
	return id, err
}
