// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotion_status.sql

package promotiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const switchPromotionStatus = `-- name: SwitchPromotionStatus :one
UPDATE promotion
SET status     = $1::text,
    updated_at = $2
WHERE id = $3
  AND status = $4::text
  AND deleted_at IS NULL
RETURNING id, code, is_automatic, type, campaign_id, status, usage_limit, usage_count, metadata, created_at, updated_at, deleted_at
`

type SwitchPromotionStatusParams struct {
	ToStatus   string
	UpdatedAt  pgtype.Timestamptz
	ID         string
	FromStatus string
}

// SwitchPromotionStatus moves the promotion from the status the caller read to
// another, and only if it is still in the first (ADR 0312): an operator who
// paused a coupon another operator had already paused, or published a draft
// somebody had already withdrawn, is told so rather than undoing the other.
func (q *Queries) SwitchPromotionStatus(ctx context.Context, arg SwitchPromotionStatusParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, switchPromotionStatus,
		arg.ToStatus,
		arg.UpdatedAt,
		arg.ID,
		arg.FromStatus,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IsAutomatic,
		&i.Type,
		&i.CampaignID,
		&i.Status,
		&i.UsageLimit,
		&i.UsageCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
