package app

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"path"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	coreerrors "github.com/bdrtr/gobit/core/errors"
	"github.com/bdrtr/gobit/internal/scaffold"
)

// newCommand writes a new project that embeds gobit (ADR 0154).
//
// # It is the ONE verb that reads no configuration
//
// Every other subcommand calls config.Load, and that is deliberate: run inside
// the running container, they are already pointed at the right database. This one
// runs on a developer's laptop before anything exists — there is no database, no
// .env and no environment — so touching the configuration would make the front
// door of the framework depend on the thing the front door is supposed to set up.
const newCommand = "new"

// The flags of `gobit new`.
const (
	// flagModule overrides the generated project's own module path.
	flagModule = "module"
	// flagReplace points the generated go.mod at a gobit CHECKOUT.
	flagReplace = "replace"
)

// The build facts the generator needs, filled in at build time with -ldflags.
//
// They are separate from [Options.Version] because they answer a different
// question. Version is what this binary CALLS itself in a log line; these say
// which library version a project generated by it can require — and the two are
// not the same string (see [scaffold.Build]).
//
// A plain `go build ./...` leaves all three empty, and that is the case the
// refusal below exists for.
var (
	buildRelease    string
	buildBaseTag    string
	buildCommit     string
	buildCommitTime string
)

// goDirective is the `go` line written into a generated go.mod.
//
// It is this repository's own, because a project requiring gobit cannot declare
// an older language version than the library it compiles against. The value is
// kept in step by a gate that reads the root go.mod (see the arch tests).
const goDirective = "1.26.6"

// The error codes of this command.
const (
	// codeNewInvalidInput reports an invocation this command cannot make sense
	// of, or a build that cannot name a version.
	codeNewInvalidInput = "cli_new_invalid_input"
	// codeNewFailed reports that the project could not be written.
	codeNewFailed = "cli_new_failed"
)

// newFlags is what one invocation asked for.
type newFlags struct {
	dir     string
	module  string
	replace string
}

// runNew parses the flags and writes the project.
func runNew(args []string, out io.Writer, _ Options) error {
	parsed, err := parseNewFlags(args)
	switch {
	case errors.Is(err, flag.ErrHelp):
		// The flag set's output is discarded, so the caller is told what the
		// command takes rather than left with nothing.
		return writeReport(out, usageText("dev"))
	case err != nil:
		return err
	}

	version, err := requiredVersion(parsed.replace)
	if err != nil {
		return err
	}

	replace := parsed.replace
	if replace != "" {
		absolute, absErr := filepath.Abs(replace)
		if absErr != nil {
			return coreerrors.Invalid(codeNewInvalidInput,
				"-%s %q could not be resolved to a path: %v", flagReplace, replace, absErr)
		}
		replace = absolute
	}

	if err := scaffold.Write(scaffold.Input{
		Dir:          parsed.dir,
		Module:       parsed.module,
		GobitVersion: version,
		Replace:      replace,
		GoVersion:    goDirective,
	}); err != nil {
		return coreerrors.Invalid(codeNewFailed, "%v", err)
	}

	return writeReport(out, newReport(parsed, version))
}

// requiredVersion decides what the generated go.mod requires.
//
// # Why an unknown version is a REFUSAL and not a guess
//
// The alternatives were measured. Writing `@latest` or the newest tag resolves
// to a release that does not contain the published surface, so the generated
// project fails at `go mod tidy` — a project the user cannot build and cannot
// diagnose. Writing nothing produces a go.mod that requires no version at all.
// Refusing says which build produced this binary and what to do about it.
func requiredVersion(replace string) (string, error) {
	if replace != "" {
		// A checkout answers the question completely; asking the build for a
		// version it may not have would refuse an invocation that is already
		// correct.
		return "", nil
	}

	build := scaffold.Build{
		Release: buildRelease,
		BaseTag: buildBaseTag,
		Commit:  buildCommit,
	}
	if buildCommitTime != "" {
		seconds, err := strconv.ParseInt(buildCommitTime, 10, 64)
		if err != nil {
			return "", coreerrors.Internal(codeNewFailed,
				"this binary carries an unreadable build timestamp (%q); it was built wrongly",
				buildCommitTime)
		}
		build.CommitTime = time.Unix(seconds, 0).UTC()
	}

	version := build.Version()
	if version == "" {
		return "", coreerrors.Invalid(codeNewInvalidInput,
			"this binary does not know which %s version a generated project should require, "+
				"so it will not write one that cannot build. It was built without the build "+
				"facts (`go build` alone does that; `make build` injects them). Either use a "+
				"released binary, or generate against a checkout with -%s <path-to-gobit>",
			scaffold.GobitModule, flagReplace)
	}

	return version, nil
}

// parseNewFlags reads the target directory and the flags.
//
// The directory is required to be the FIRST argument, exactly as the id is for
// `recover` and the owner for `migrate down`: the flag package stops at the
// first non-flag argument, so a directory written after the flags would be
// swallowed as a leftover.
func parseNewFlags(args []string) (newFlags, error) {
	if len(args) == 0 || strings.HasPrefix(args[0], "-") {
		return newFlags{}, coreerrors.Invalid(codeNewInvalidInput,
			"%s needs the directory to create as its FIRST argument "+
				"(%s %s <dir> [-%s PATH] [-%s DIR])",
			newCommand, binaryName, newCommand, flagModule, flagReplace)
	}

	set := flag.NewFlagSet(binaryName+" "+newCommand, flag.ContinueOnError)
	set.SetOutput(io.Discard)
	module := set.String(flagModule, "",
		"the generated project's module path (default example.com/<dir>)")
	replace := set.String(flagReplace, "",
		"point the generated go.mod at a gobit checkout instead of a released version")

	if err := set.Parse(args[1:]); err != nil {
		return newFlags{}, coreerrors.Wrap(err, coreerrors.KindInvalid, codeNewInvalidInput,
			"the flags of %s could not be parsed", newCommand)
	}
	if rest := set.Args(); len(rest) > 0 {
		return newFlags{}, coreerrors.Invalid(codeNewInvalidInput,
			"unexpected argument %q after the flags of %s", rest[0], newCommand)
	}

	dir := strings.TrimSpace(args[0])
	if dir == "" {
		return newFlags{}, coreerrors.Invalid(codeNewInvalidInput,
			"the directory to create cannot be empty")
	}

	name := filepath.Base(filepath.Clean(dir))
	if name == "." || name == string(filepath.Separator) {
		return newFlags{}, coreerrors.Invalid(codeNewInvalidInput,
			"%q does not name a directory to create", dir)
	}

	modulePath := strings.TrimSpace(*module)
	if modulePath == "" {
		// example.com is reserved for documentation, so a project whose module
		// path was never chosen cannot accidentally collide with a real one.
		modulePath = "example.com/" + name
	}
	if strings.ContainsAny(modulePath, " \t") || path.Base(modulePath) == "" {
		return newFlags{}, coreerrors.Invalid(codeNewInvalidInput,
			"%q is not a module path", modulePath)
	}

	return newFlags{dir: dir, module: modulePath, replace: strings.TrimSpace(*replace)}, nil
}

// newReport is what the command prints.
//
// It lists what was written and the two commands that follow, because a
// generator that said nothing would leave the user to find out with ls — and the
// next step (bringing up a database) is the one a reader of a fresh directory
// cannot guess.
func newReport(parsed newFlags, version string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "wrote %s (module %s)\n", parsed.dir, parsed.module)
	for _, name := range scaffold.Written() {
		fmt.Fprintf(&b, "  %s\n", name)
	}
	if version != "" {
		fmt.Fprintf(&b, "\nrequires %s %s\n", scaffold.GobitModule, version)
	} else {
		fmt.Fprintf(&b, "\nreplaces %s with %s — this project is NOT portable\n",
			scaffold.GobitModule, parsed.replace)
	}
	fmt.Fprintf(&b, "\nnext:\n  cd %s\n  docker compose up -d\n"+
		"  # fill in JWT_SECRET and ADMIN_BOOTSTRAP_* in .env\n  go run .\n", parsed.dir)

	return b.String()
}
