// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee.sql

package b2bdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmployees = `-- name: CountEmployees :one
SELECT count(*) FROM b2b_company_employee
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR company_id = $1::text)
  AND ($2::boolean IS NULL
       OR is_company_admin = $2::boolean)
`

type CountEmployeesParams struct {
	CompanyID      *string
	IsCompanyAdmin *bool
}

func (q *Queries) CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, arg.CompanyID, arg.IsCompanyAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, company_id, spending_limit, is_company_admin, created_at, updated_at, deleted_at FROM b2b_company_employee
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEmployee(ctx context.Context, id string) (B2bCompanyEmployee, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i B2bCompanyEmployee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SpendingLimit,
		&i.IsCompanyAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertEmployee = `-- name: InsertEmployee :one

INSERT INTO b2b_company_employee (
    id, company_id, spending_limit, is_company_admin, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id, company_id, spending_limit, is_company_admin, created_at, updated_at, deleted_at
`

type InsertEmployeeParams struct {
	ID             string
	CompanyID      string
	SpendingLimit  *int64
	IsCompanyAdmin bool
	CreatedAt      pgtype.Timestamptz
}

// b2b_company_employee sorguları. Tüm okumalar deleted_at IS NULL filtresi
// uygular.
//
// Bu dosyada customer_id GEÇMEZ: çalışan ile müşteri arasındaki bağ şemada
// değil core/link'tedir (bkz. migrations/000001_b2b_init.up.sql).
func (q *Queries) InsertEmployee(ctx context.Context, arg InsertEmployeeParams) (B2bCompanyEmployee, error) {
	row := q.db.QueryRow(ctx, insertEmployee,
		arg.ID,
		arg.CompanyID,
		arg.SpendingLimit,
		arg.IsCompanyAdmin,
		arg.CreatedAt,
	)
	var i B2bCompanyEmployee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SpendingLimit,
		&i.IsCompanyAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, company_id, spending_limit, is_company_admin, created_at, updated_at, deleted_at FROM b2b_company_employee
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR company_id = $1::text)
  AND ($2::boolean IS NULL
       OR is_company_admin = $2::boolean)
ORDER BY created_at DESC, id DESC
LIMIT $4::int OFFSET $3::int
`

type ListEmployeesParams struct {
	CompanyID      *string
	IsCompanyAdmin *bool
	Off            int32
	Lim            int32
}

// ListEmployees süzgeçlenmiş ve sayfalanmış çalışan listesini döner.
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]B2bCompanyEmployee, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.CompanyID,
		arg.IsCompanyAdmin,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []B2bCompanyEmployee{}
	for rows.Next() {
		var i B2bCompanyEmployee
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SpendingLimit,
			&i.IsCompanyAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEmployee = `-- name: SoftDeleteEmployee :one
UPDATE b2b_company_employee
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteEmployeeParams struct {
	ID        string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteEmployee(ctx context.Context, arg SoftDeleteEmployeeParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteEmployee, arg.ID, arg.DeletedAt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const softDeleteEmployeesOfCompany = `-- name: SoftDeleteEmployeesOfCompany :many
UPDATE b2b_company_employee
SET deleted_at = $2, updated_at = $2
WHERE company_id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteEmployeesOfCompanyParams struct {
	CompanyID string
	DeletedAt pgtype.Timestamptz
}

// SoftDeleteEmployeesOfCompany şirketin tüm çalışanlarını yumuşak siler ve
// SİLİNENLERİN KİMLİKLERİNİ döner.
//
// Kimlikler dönmek zorundadır: çalışanın müşteriyle bağı link tablosundadır ve
// o bağ silinmezse müşteri, kardinalite kısıtı yüzünden bir daha HİÇBİR
// şirkete çalışan olarak eklenemez (bkz. service.Definitions, OneToOne).
func (q *Queries) SoftDeleteEmployeesOfCompany(ctx context.Context, arg SoftDeleteEmployeesOfCompanyParams) ([]string, error) {
	rows, err := q.db.Query(ctx, softDeleteEmployeesOfCompany, arg.CompanyID, arg.DeletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE b2b_company_employee SET
    spending_limit   = CASE
        WHEN $1::boolean THEN NULL
        ELSE COALESCE($2::bigint, spending_limit)
    END,
    is_company_admin = COALESCE($3::boolean, is_company_admin),
    updated_at       = $4
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, company_id, spending_limit, is_company_admin, created_at, updated_at, deleted_at
`

type UpdateEmployeeParams struct {
	ClearLimit     bool
	SpendingLimit  *int64
	IsCompanyAdmin *bool
	UpdatedAt      pgtype.Timestamptz
	ID             string
}

// UpdateEmployee verilmeyen alanları OLDUĞU GİBİ bırakır.
//
// spending_limit için COALESCE KULLANILAMAZ: alanın kendisi NULL olabilir
// ("sınırsız") ve COALESCE, "sınırsız yap" isteğini "dokunma"dan ayıramazdı.
// Ayrım ayrı bir bayrakla taşınır: clear_limit doğruysa sütun NULL'a çekilir,
// değilse verilen değer yazılır ya da eski değer korunur.
func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (B2bCompanyEmployee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ClearLimit,
		arg.SpendingLimit,
		arg.IsCompanyAdmin,
		arg.UpdatedAt,
		arg.ID,
	)
	var i B2bCompanyEmployee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SpendingLimit,
		&i.IsCompanyAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
