// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package orderdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID                   string
	DisplayID            int64
	Status               string
	RegionID             string
	CustomerID           *string
	Email                *string
	CurrencyCode         string
	CartID               *string
	IdempotencyKey       *string
	Subtotal             int64
	DiscountTotal        int64
	TaxTotal             int64
	ShippingTotal        int64
	Total                int64
	Metadata             []byte
	PlacedAt             pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	CanceledAt           pgtype.Timestamptz
	CancelReason         *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
	PersonalDataErasedAt pgtype.Timestamptz
	AddsToOrderID        *string
	PricesIncludeTax     bool
	PlacedBy             *string
	SalesChannelID       *string
}

type OrderAddress struct {
	ID              string
	OrderID         string
	AddressType     string
	SourceAddressID *string
	FirstName       *string
	LastName        *string
	Company         *string
	Address1        *string
	Address2        *string
	City            *string
	Province        *string
	PostalCode      *string
	CountryCode     *string
	Phone           *string
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SupersededAt    pgtype.Timestamptz
}

type OrderClaim struct {
	ID           string
	OrderID      string
	ClaimType    string
	Status       string
	RefundAmount int64
	Reason       *string
	Note         *string
	Metadata     []byte
	CompletedAt  pgtype.Timestamptz
	CanceledAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type OrderClaimEvidence struct {
	ID           string
	OrderClaimID string
	UploadID     string
	Caption      string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type OrderCreditLine struct {
	ID        string
	OrderID   string
	Amount    int64
	Reason    string
	Note      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrderDeliveryChange struct {
	ID                  string
	OrderID             string
	ShippingMethodID    string
	ShippingOptionID    string
	Name                string
	Amount              int64
	Difference          int64
	CreditLineID        *string
	CreatedAt           pgtype.Timestamptz
	PaymentCollectionID *string
}

type OrderExchange struct {
	ID                  string
	OrderID             string
	Status              string
	DifferenceDue       int64
	Note                *string
	Metadata            []byte
	CanceledAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
	PaymentCollectionID *string
	FundedAt            pgtype.Timestamptz
}

type OrderLineCancellation struct {
	ID              string
	OrderLineItemID string
	Quantity        int64
	Reason          string
	Note            string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Seq             *int64
}

type OrderLineItem struct {
	ID               string
	OrderID          string
	VariantID        string
	Title            string
	Quantity         int64
	UnitPrice        int64
	Subtotal         int64
	DiscountTotal    int64
	TaxTotal         int64
	Total            int64
	Metadata         []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	TaxRateBps       int32
	PriceID          *string
	PriceListID      *string
	PriceListType    *string
	IsGiftcard       bool
	Properties       []byte
	ParentLineItemID *string
	Seq              *int64
	Components       []byte
	ProductTitle     string
	UnitCost         *int64
}

type OrderLineTax struct {
	ID              string
	OrderLineItemID string
	Position        int32
	RateID          string
	RateBps         int32
	Compound        bool
	TaxableAmount   int64
	TaxAmount       int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type OrderReplacement struct {
	ID               string
	OrderClaimID     *string
	Status           string
	ShippingOptionID string
	LocationID       string
	Note             *string
	CanceledAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DispatchedAt     pgtype.Timestamptz
	FulfillmentID    *string
	OrderExchangeID  *string
	Recalls          int32
}

type OrderReplacementItem struct {
	ID                 string
	OrderReplacementID string
	OrderLineItemID    *string
	Quantity           int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	ReservationID      *string
	VariantID          *string
	Seq                *int64
}

type OrderReplacementItemPart struct {
	OrderReplacementItemID string
	VariantID              string
	Quantity               int64
	Rank                   int32
	ReservationID          *string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type OrderReturn struct {
	ID                 string
	OrderID            string
	Status             string
	RefundAmount       int64
	Reason             *string
	Note               *string
	Metadata           []byte
	ReceivedAt         pgtype.Timestamptz
	CanceledAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	ReceivedLocationID *string
}

type OrderReturnItem struct {
	ID              string
	OrderReturnID   string
	OrderLineItemID string
	Quantity        int64
	RefundAmount    int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Seq             *int64
}

type OrderShippingMethod struct {
	ID               string
	OrderID          string
	ShippingOptionID *string
	Name             string
	Amount           int64
	CreatedAt        pgtype.Timestamptz
	Seq              *int64
}

type OrderSummary struct {
	ID            string
	OrderID       string
	PaidTotal     int64
	RefundedTotal int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
