// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package orderdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID             string
	DisplayID      int64
	Status         string
	RegionID       string
	CustomerID     *string
	Email          *string
	CurrencyCode   string
	CartID         *string
	IdempotencyKey *string
	Subtotal       int64
	DiscountTotal  int64
	TaxTotal       int64
	ShippingTotal  int64
	Total          int64
	Metadata       []byte
	PlacedAt       pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CanceledAt     pgtype.Timestamptz
	CancelReason   *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type OrderClaim struct {
	ID           string
	OrderID      string
	ClaimType    string
	Status       string
	RefundAmount int64
	Reason       *string
	Note         *string
	Metadata     []byte
	CompletedAt  pgtype.Timestamptz
	CanceledAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type OrderExchange struct {
	ID            string
	OrderID       string
	Status        string
	DifferenceDue int64
	Note          *string
	Metadata      []byte
	CompletedAt   pgtype.Timestamptz
	CanceledAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type OrderLineItem struct {
	ID            string
	OrderID       string
	VariantID     string
	Title         string
	Quantity      int64
	UnitPrice     int64
	Subtotal      int64
	DiscountTotal int64
	TaxTotal      int64
	Total         int64
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type OrderReturn struct {
	ID           string
	OrderID      string
	Status       string
	RefundAmount int64
	Reason       *string
	Note         *string
	Metadata     []byte
	ReceivedAt   pgtype.Timestamptz
	CanceledAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type OrderSummary struct {
	ID            string
	OrderID       string
	PaidTotal     int64
	RefundedTotal int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
