// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_exchanges.sql

package orderdb

import (
	"context"
)

const cancelOrderExchange = `-- name: CancelOrderExchange :one
UPDATE order_exchanges
SET status = 'canceled', canceled_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, order_id, status, difference_due, note, metadata, canceled_at, created_at, updated_at, completed_at
`

// CancelOrderExchange withdraws the exchange request.
//
// canceled_at comes from the DATABASE clock, as every other after-sales stamp
// does: the moment belongs to the record, and letting the caller supply it
// makes the ordering of two records depend on which machine wrote them.
func (q *Queries) CancelOrderExchange(ctx context.Context, id string) (OrderExchange, error) {
	row := q.db.QueryRow(ctx, cancelOrderExchange, id)
	var i OrderExchange
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.DifferenceDue,
		&i.Note,
		&i.Metadata,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeOrderExchange = `-- name: CompleteOrderExchange :one
UPDATE order_exchanges
SET status = 'completed', completed_at = now(), updated_at = now()
WHERE id = $1 AND status = 'requested'
RETURNING id, order_id, status, difference_due, note, metadata, canceled_at, created_at, updated_at, completed_at
`

// CompleteOrderExchange records that the exchange was settled.
//
// The moment comes from the DATABASE clock for the reason the withdrawal's does.
// The WHERE narrows to 'requested' rather than trusting a status read a moment
// ago: the caller holds the row's lock, so this cannot lose a race, and the
// narrowing is what makes the query safe to read on its own.
//
// An exchange that owes money is refused by order_exchanges_completed_owes_nothing
// rather than by this statement. The rule needs only the row, so the database is
// where it can be kept once instead of in every writer.
func (q *Queries) CompleteOrderExchange(ctx context.Context, id string) (OrderExchange, error) {
	row := q.db.QueryRow(ctx, completeOrderExchange, id)
	var i OrderExchange
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.DifferenceDue,
		&i.Note,
		&i.Metadata,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countOrderExchanges = `-- name: CountOrderExchanges :one
SELECT COUNT(*) FROM order_exchanges
WHERE order_id = $1
`

func (q *Queries) CountOrderExchanges(ctx context.Context, orderID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderExchanges, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrderExchange = `-- name: CreateOrderExchange :one

INSERT INTO order_exchanges (id, order_id, status, difference_due, note, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, status, difference_due, note, metadata, canceled_at, created_at, updated_at, completed_at
`

type CreateOrderExchangeParams struct {
	ID            string
	OrderID       string
	Status        string
	DifferenceDue int64
	Note          *string
	Metadata      []byte
}

// order_exchanges queries (plan Section 6).
//
// The record is created, read, listed, WITHDRAWN and -- since ADR 0114 -- can be
// COMPLETED when it owes nothing. The completion came back because one of the two
// capabilities migration 000008 named arrived: goods can now be shipped against an
// existing order (ADR 0090), and an exchange whose difference_due is zero needs
// nothing else. The other half is still missing -- the order-to-payment link is
// one-to-one, so money cannot be collected against an existing order -- which is
// why the completion is bounded by a CHECK rather than offered for every record.
func (q *Queries) CreateOrderExchange(ctx context.Context, arg CreateOrderExchangeParams) (OrderExchange, error) {
	row := q.db.QueryRow(ctx, createOrderExchange,
		arg.ID,
		arg.OrderID,
		arg.Status,
		arg.DifferenceDue,
		arg.Note,
		arg.Metadata,
	)
	var i OrderExchange
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.DifferenceDue,
		&i.Note,
		&i.Metadata,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOrderExchange = `-- name: GetOrderExchange :one
SELECT id, order_id, status, difference_due, note, metadata, canceled_at, created_at, updated_at, completed_at FROM order_exchanges
WHERE id = $1
`

func (q *Queries) GetOrderExchange(ctx context.Context, id string) (OrderExchange, error) {
	row := q.db.QueryRow(ctx, getOrderExchange, id)
	var i OrderExchange
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.DifferenceDue,
		&i.Note,
		&i.Metadata,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listOrderExchanges = `-- name: ListOrderExchanges :many
SELECT id, order_id, status, difference_due, note, metadata, canceled_at, created_at, updated_at, completed_at FROM order_exchanges
WHERE order_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3::bigint OFFSET $2::bigint
`

type ListOrderExchangesParams struct {
	OrderID   string
	RowOffset int64
	RowLimit  int64
}

func (q *Queries) ListOrderExchanges(ctx context.Context, arg ListOrderExchangesParams) ([]OrderExchange, error) {
	rows, err := q.db.Query(ctx, listOrderExchanges, arg.OrderID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderExchange{}
	for rows.Next() {
		var i OrderExchange
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Status,
			&i.DifferenceDue,
			&i.Note,
			&i.Metadata,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrderExchange = `-- name: LockOrderExchange :one
SELECT id, order_id, status, difference_due, note, metadata, canceled_at, created_at, updated_at, completed_at FROM order_exchanges
WHERE id = $1
FOR UPDATE
`

// LockOrderExchange locks the exchange row until the end of the transaction.
//
// The reason is the one LockOrderReturn states: the transition reads the
// current status and writes the next one, and two operators withdrawing the
// same exchange at the same moment would otherwise both read "requested" and
// both write a timestamp, leaving the record holding the later one.
func (q *Queries) LockOrderExchange(ctx context.Context, id string) (OrderExchange, error) {
	row := q.db.QueryRow(ctx, lockOrderExchange, id)
	var i OrderExchange
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.DifferenceDue,
		&i.Note,
		&i.Metadata,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
