// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_delivery_changes.sql

package orderdb

import (
	"context"
)

const createDeliveryChange = `-- name: CreateDeliveryChange :one

INSERT INTO order_delivery_changes (
    id, order_id, shipping_method_id, shipping_option_id, name, amount, difference,
    credit_line_id, payment_collection_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, order_id, shipping_method_id, shipping_option_id, name, amount, difference, credit_line_id, created_at, payment_collection_id
`

type CreateDeliveryChangeParams struct {
	ID                  string
	OrderID             string
	ShippingMethodID    string
	ShippingOptionID    string
	Name                string
	Amount              int64
	Difference          int64
	CreditLineID        *string
	PaymentCollectionID *string
}

// order_delivery_changes queries (ADR 0199).
//
// A change is written once and never updated: the method's current delivery is
// its latest change, and the earlier ones are what it was before.
func (q *Queries) CreateDeliveryChange(ctx context.Context, arg CreateDeliveryChangeParams) (OrderDeliveryChange, error) {
	row := q.db.QueryRow(ctx, createDeliveryChange,
		arg.ID,
		arg.OrderID,
		arg.ShippingMethodID,
		arg.ShippingOptionID,
		arg.Name,
		arg.Amount,
		arg.Difference,
		arg.CreditLineID,
		arg.PaymentCollectionID,
	)
	var i OrderDeliveryChange
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ShippingMethodID,
		&i.ShippingOptionID,
		&i.Name,
		&i.Amount,
		&i.Difference,
		&i.CreditLineID,
		&i.CreatedAt,
		&i.PaymentCollectionID,
	)
	return i, err
}

const deliveryChangePaidBy = `-- name: DeliveryChangePaidBy :many
SELECT id FROM order_delivery_changes
WHERE payment_collection_id = $1
LIMIT 1
`

// DeliveryChangePaidBy names the change a collection paid for, if any
// (ADR 0200).
func (q *Queries) DeliveryChangePaidBy(ctx context.Context, paymentCollectionID *string) ([]string, error) {
	rows, err := q.db.Query(ctx, deliveryChangePaidBy, paymentCollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryChanges = `-- name: ListDeliveryChanges :many
SELECT id, order_id, shipping_method_id, shipping_option_id, name, amount, difference, credit_line_id, created_at, payment_collection_id FROM order_delivery_changes
WHERE order_id = ANY ($1::text[])
ORDER BY order_id, created_at, id
`

// ListDeliveryChanges reads the changes of several orders in ONE query, oldest
// first within an order.
func (q *Queries) ListDeliveryChanges(ctx context.Context, orderIds []string) ([]OrderDeliveryChange, error) {
	rows, err := q.db.Query(ctx, listDeliveryChanges, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderDeliveryChange{}
	for rows.Next() {
		var i OrderDeliveryChange
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ShippingMethodID,
			&i.ShippingOptionID,
			&i.Name,
			&i.Amount,
			&i.Difference,
			&i.CreditLineID,
			&i.CreatedAt,
			&i.PaymentCollectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
