// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_replacement_items.sql

package orderdb

import (
	"context"
)

const createOrderReplacementItem = `-- name: CreateOrderReplacementItem :one

INSERT INTO order_replacement_items
    (id, order_replacement_id, order_line_item_id, variant_id, quantity)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_replacement_id, order_line_item_id, quantity, created_at, updated_at, reservation_id, variant_id
`

type CreateOrderReplacementItemParams struct {
	ID                 string
	OrderReplacementID string
	OrderLineItemID    *string
	VariantID          *string
	Quantity           int64
}

// order_replacement_items queries: which lines are being replaced.
// Exactly ONE of order_line_item_id and variant_id is set; the CHECK in
// migration 000019 holds it, and the service decides which shape a request has.
func (q *Queries) CreateOrderReplacementItem(ctx context.Context, arg CreateOrderReplacementItemParams) (OrderReplacementItem, error) {
	row := q.db.QueryRow(ctx, createOrderReplacementItem,
		arg.ID,
		arg.OrderReplacementID,
		arg.OrderLineItemID,
		arg.VariantID,
		arg.Quantity,
	)
	var i OrderReplacementItem
	err := row.Scan(
		&i.ID,
		&i.OrderReplacementID,
		&i.OrderLineItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReservationID,
		&i.VariantID,
	)
	return i, err
}

const listOrderReplacementItems = `-- name: ListOrderReplacementItems :many
SELECT id, order_replacement_id, order_line_item_id, quantity, created_at, updated_at, reservation_id, variant_id FROM order_replacement_items
WHERE order_replacement_id = $1
ORDER BY created_at, id
`

// ListOrderReplacementItems returns a replacement's lines in the order they
// were written.
func (q *Queries) ListOrderReplacementItems(ctx context.Context, orderReplacementID string) ([]OrderReplacementItem, error) {
	rows, err := q.db.Query(ctx, listOrderReplacementItems, orderReplacementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderReplacementItem{}
	for rows.Next() {
		var i OrderReplacementItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderReplacementID,
			&i.OrderLineItemID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReservationID,
			&i.VariantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderReplacementItemReservation = `-- name: SetOrderReplacementItemReservation :one
UPDATE order_replacement_items
SET reservation_id = $1::text,
    updated_at = now()
WHERE id = $2::text
RETURNING id, order_replacement_id, order_line_item_id, quantity, created_at, updated_at, reservation_id, variant_id
`

type SetOrderReplacementItemReservationParams struct {
	ReservationID string
	ID            string
}

// SetOrderReplacementItemReservation writes the promise a line's units are held
// under.
//
// It is written BEFORE the units are confirmed, so a dispatch that dies between
// the two finds the promise on the row instead of making a second one.
func (q *Queries) SetOrderReplacementItemReservation(ctx context.Context, arg SetOrderReplacementItemReservationParams) (OrderReplacementItem, error) {
	row := q.db.QueryRow(ctx, setOrderReplacementItemReservation, arg.ReservationID, arg.ID)
	var i OrderReplacementItem
	err := row.Scan(
		&i.ID,
		&i.OrderReplacementID,
		&i.OrderLineItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReservationID,
		&i.VariantID,
	)
	return i, err
}

const sumReplacedQuantities = `-- name: SumReplacedQuantities :many
SELECT i.order_line_item_id, SUM(i.quantity)::bigint AS replaced
FROM order_replacement_items i
JOIN order_replacements r ON r.id = i.order_replacement_id
WHERE i.order_line_item_id = ANY($1::text[])
  AND i.order_line_item_id IS NOT NULL
  AND r.status <> 'canceled'
GROUP BY i.order_line_item_id
`

type SumReplacedQuantitiesRow struct {
	OrderLineItemID *string
	Replaced        int64
}

// SumReplacedQuantities reports how many units of each of the given order lines
// have ALREADY been promised, across every live replacement of the order.
//
// # Why canceled replacements are excluded
//
// A withdrawn promise releases the units it was holding: they can be promised
// again. An open one must count, or two requests could each promise the whole
// line and together send twice what was bought.
//
// The service reads this under the order's lock and compares it against the
// ordered quantity, exactly as SumReturnedQuantities is used. It has to be a
// query rather than a CHECK because the rule spans rows.
//
// # Variant-shaped rows are NOT counted, and cannot be
//
// Since migration 000019 a replacement item may name a VARIANT instead of a line
// (ADR 0145). The ceiling this sum feeds is "no more of a line than was bought on
// it", and a row that names no line is not against any line's ceiling — it is
// goods the order never sold. The `IS NOT NULL` is therefore a statement rather
// than a filter: counting such a row would attribute it to a line chosen by
// nothing.
//
// What bounds a variant-shaped row instead is written where the decision is: the
// exchange's money guard, which refuses a dispatch until the difference is funded.
func (q *Queries) SumReplacedQuantities(ctx context.Context, lineItemIds []string) ([]SumReplacedQuantitiesRow, error) {
	rows, err := q.db.Query(ctx, sumReplacedQuantities, lineItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumReplacedQuantitiesRow{}
	for rows.Next() {
		var i SumReplacedQuantitiesRow
		if err := rows.Scan(&i.OrderLineItemID, &i.Replaced); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
