// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_claims.sql

package orderdb

import (
	"context"
)

const cancelOrderClaim = `-- name: CancelOrderClaim :one
UPDATE order_claims
SET status = 'canceled', canceled_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, order_id, claim_type, status, refund_amount, reason, note, metadata, completed_at, canceled_at, created_at, updated_at, deleted_at
`

// CancelOrderClaim withdraws the claim.
func (q *Queries) CancelOrderClaim(ctx context.Context, id string) (OrderClaim, error) {
	row := q.db.QueryRow(ctx, cancelOrderClaim, id)
	var i OrderClaim
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ClaimType,
		&i.Status,
		&i.RefundAmount,
		&i.Reason,
		&i.Note,
		&i.Metadata,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const completeOrderClaim = `-- name: CompleteOrderClaim :one
UPDATE order_claims
SET status = 'completed', completed_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, order_id, claim_type, status, refund_amount, reason, note, metadata, completed_at, canceled_at, created_at, updated_at, deleted_at
`

// CompleteOrderClaim records that the claim was settled.
func (q *Queries) CompleteOrderClaim(ctx context.Context, id string) (OrderClaim, error) {
	row := q.db.QueryRow(ctx, completeOrderClaim, id)
	var i OrderClaim
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ClaimType,
		&i.Status,
		&i.RefundAmount,
		&i.Reason,
		&i.Note,
		&i.Metadata,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countOrderClaims = `-- name: CountOrderClaims :one
SELECT COUNT(*) FROM order_claims
WHERE order_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountOrderClaims(ctx context.Context, orderID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderClaims, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrderClaim = `-- name: CreateOrderClaim :one

INSERT INTO order_claims (id, order_id, claim_type, status, refund_amount, reason, note, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, order_id, claim_type, status, refund_amount, reason, note, metadata, completed_at, canceled_at, created_at, updated_at, deleted_at
`

type CreateOrderClaimParams struct {
	ID           string
	OrderID      string
	ClaimType    string
	Status       string
	RefundAmount int64
	Reason       *string
	Note         *string
	Metadata     []byte
}

// order_claims queries (damage/shortage record skeleton; plan Section 6).
func (q *Queries) CreateOrderClaim(ctx context.Context, arg CreateOrderClaimParams) (OrderClaim, error) {
	row := q.db.QueryRow(ctx, createOrderClaim,
		arg.ID,
		arg.OrderID,
		arg.ClaimType,
		arg.Status,
		arg.RefundAmount,
		arg.Reason,
		arg.Note,
		arg.Metadata,
	)
	var i OrderClaim
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ClaimType,
		&i.Status,
		&i.RefundAmount,
		&i.Reason,
		&i.Note,
		&i.Metadata,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrderClaim = `-- name: GetOrderClaim :one
SELECT id, order_id, claim_type, status, refund_amount, reason, note, metadata, completed_at, canceled_at, created_at, updated_at, deleted_at FROM order_claims
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrderClaim(ctx context.Context, id string) (OrderClaim, error) {
	row := q.db.QueryRow(ctx, getOrderClaim, id)
	var i OrderClaim
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ClaimType,
		&i.Status,
		&i.RefundAmount,
		&i.Reason,
		&i.Note,
		&i.Metadata,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrderClaims = `-- name: ListOrderClaims :many
SELECT id, order_id, claim_type, status, refund_amount, reason, note, metadata, completed_at, canceled_at, created_at, updated_at, deleted_at FROM order_claims
WHERE order_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $3::bigint OFFSET $2::bigint
`

type ListOrderClaimsParams struct {
	OrderID   string
	RowOffset int64
	RowLimit  int64
}

func (q *Queries) ListOrderClaims(ctx context.Context, arg ListOrderClaimsParams) ([]OrderClaim, error) {
	rows, err := q.db.Query(ctx, listOrderClaims, arg.OrderID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderClaim{}
	for rows.Next() {
		var i OrderClaim
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ClaimType,
			&i.Status,
			&i.RefundAmount,
			&i.Reason,
			&i.Note,
			&i.Metadata,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrderClaim = `-- name: LockOrderClaim :one
SELECT id, order_id, claim_type, status, refund_amount, reason, note, metadata, completed_at, canceled_at, created_at, updated_at, deleted_at FROM order_claims
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// LockOrderClaim locks the claim row until the end of the transaction.
func (q *Queries) LockOrderClaim(ctx context.Context, id string) (OrderClaim, error) {
	row := q.db.QueryRow(ctx, lockOrderClaim, id)
	var i OrderClaim
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ClaimType,
		&i.Status,
		&i.RefundAmount,
		&i.Reason,
		&i.Note,
		&i.Metadata,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
