// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_credit_lines.sql

package orderdb

import (
	"context"
)

const createOrderCreditLine = `-- name: CreateOrderCreditLine :one

INSERT INTO order_credit_lines (id, order_id, amount, reason, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, amount, reason, note, created_at, updated_at
`

type CreateOrderCreditLineParams struct {
	ID      string
	OrderID string
	Amount  int64
	Reason  string
	Note    string
}

// order_credit_lines queries.
//
// A credit line is written once and never updated: it is a record of a
// concession that was made, and a concession that is edited afterwards is not
// the same record. Withdrawing one is a second line in the other direction --
// which this table cannot hold, deliberately (see migration 000014).
func (q *Queries) CreateOrderCreditLine(ctx context.Context, arg CreateOrderCreditLineParams) (OrderCreditLine, error) {
	row := q.db.QueryRow(ctx, createOrderCreditLine,
		arg.ID,
		arg.OrderID,
		arg.Amount,
		arg.Reason,
		arg.Note,
	)
	var i OrderCreditLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Reason,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderCreditLines = `-- name: ListOrderCreditLines :many
SELECT id, order_id, amount, reason, note, created_at, updated_at FROM order_credit_lines
WHERE order_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListOrderCreditLines(ctx context.Context, orderID string) ([]OrderCreditLine, error) {
	rows, err := q.db.Query(ctx, listOrderCreditLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderCreditLine{}
	for rows.Next() {
		var i OrderCreditLine
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Amount,
			&i.Reason,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumOrderCreditLines = `-- name: SumOrderCreditLines :one

SELECT COALESCE(sum(amount), 0)::bigint FROM order_credit_lines
WHERE order_id = $1
`

// SumOrderCreditLines is the running total, read rather than stored.
//
// COALESCE because an order with no credit lines has to answer 0 rather than
// NULL: the caller subtracts this from the order's total and a NULL would make
// the whole outstanding amount NULL.
func (q *Queries) SumOrderCreditLines(ctx context.Context, orderID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumOrderCreditLines, orderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
