// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_replacement_item_parts.sql

package orderdb

import (
	"context"
)

const createOrderReplacementItemParts = `-- name: CreateOrderReplacementItemParts :exec

INSERT INTO order_replacement_item_parts (order_replacement_item_id, variant_id, quantity, rank)
SELECT $1::text, p.variant_id, ($2::bigint[])[p.ordinality],
       (p.ordinality - 1)::integer
FROM unnest($3::text[]) WITH ORDINALITY AS p(variant_id, ordinality)
`

type CreateOrderReplacementItemPartsParams struct {
	ItemID     string
	Quantities []int64
	VariantIds []string
}

// order_replacement_item_parts queries (ADR 0238).
// Writes a replacement item's parts; the position in the arrays is the rank.
func (q *Queries) CreateOrderReplacementItemParts(ctx context.Context, arg CreateOrderReplacementItemPartsParams) error {
	_, err := q.db.Exec(ctx, createOrderReplacementItemParts, arg.ItemID, arg.Quantities, arg.VariantIds)
	return err
}

const listOrderReplacementItemParts = `-- name: ListOrderReplacementItemParts :many
SELECT p.order_replacement_item_id, p.variant_id, p.quantity, p.reservation_id
FROM order_replacement_item_parts AS p
JOIN order_replacement_items AS i ON i.id = p.order_replacement_item_id
WHERE i.order_replacement_id = $1::text
ORDER BY p.order_replacement_item_id, p.rank
`

type ListOrderReplacementItemPartsRow struct {
	OrderReplacementItemID string
	VariantID              string
	Quantity               int64
	ReservationID          *string
}

// The parts of every item of a replacement, each item's in its rank.
func (q *Queries) ListOrderReplacementItemParts(ctx context.Context, replacementID string) ([]ListOrderReplacementItemPartsRow, error) {
	rows, err := q.db.Query(ctx, listOrderReplacementItemParts, replacementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderReplacementItemPartsRow{}
	for rows.Next() {
		var i ListOrderReplacementItemPartsRow
		if err := rows.Scan(
			&i.OrderReplacementItemID,
			&i.VariantID,
			&i.Quantity,
			&i.ReservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderReplacementItemPartReservation = `-- name: SetOrderReplacementItemPartReservation :execrows
UPDATE order_replacement_item_parts
SET reservation_id = $1::text, updated_at = now()
WHERE order_replacement_item_id = $2::text AND variant_id = $3::text
`

type SetOrderReplacementItemPartReservationParams struct {
	ReservationID string
	ItemID        string
	VariantID     string
}

// Writes the promise one part's units are held under.
func (q *Queries) SetOrderReplacementItemPartReservation(ctx context.Context, arg SetOrderReplacementItemPartReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOrderReplacementItemPartReservation, arg.ReservationID, arg.ItemID, arg.VariantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
