// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_line_items.sql

package orderdb

import (
	"context"
)

const createOrderLineItem = `-- name: CreateOrderLineItem :one

INSERT INTO order_line_items (
    id, order_id, variant_id, title, quantity,
    unit_price, subtotal, discount_total, tax_total, total, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, order_id, variant_id, title, quantity, unit_price, subtotal, discount_total, tax_total, total, metadata, created_at, updated_at, deleted_at
`

type CreateOrderLineItemParams struct {
	ID            string
	OrderID       string
	VariantID     string
	Title         string
	Quantity      int64
	UnitPrice     int64
	Subtotal      int64
	DiscountTotal int64
	TaxTotal      int64
	Total         int64
	Metadata      []byte
}

// order_line_items sorguları.
//
// Sipariş satırları YAZILDIKTAN SONRA DEĞİŞMEZ: sipariş, "o an ne satıldı"
// sorusunun kalıcı yanıtıdır ve satırın adedini ya da tutarını sonradan
// düzeltmek o yanıtı bozmak olurdu. Bu yüzden burada UPDATE sorgusu YOKTUR;
// düzeltme yolu iade/değişim kayıtlarıdır.
func (q *Queries) CreateOrderLineItem(ctx context.Context, arg CreateOrderLineItemParams) (OrderLineItem, error) {
	row := q.db.QueryRow(ctx, createOrderLineItem,
		arg.ID,
		arg.OrderID,
		arg.VariantID,
		arg.Title,
		arg.Quantity,
		arg.UnitPrice,
		arg.Subtotal,
		arg.DiscountTotal,
		arg.TaxTotal,
		arg.Total,
		arg.Metadata,
	)
	var i OrderLineItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.VariantID,
		&i.Title,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.Total,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrderLineItems = `-- name: ListOrderLineItems :many
SELECT id, order_id, variant_id, title, quantity, unit_price, subtotal, discount_total, tax_total, total, metadata, created_at, updated_at, deleted_at FROM order_line_items
WHERE order_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListOrderLineItems(ctx context.Context, orderID string) ([]OrderLineItem, error) {
	rows, err := q.db.Query(ctx, listOrderLineItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderLineItem{}
	for rows.Next() {
		var i OrderLineItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.VariantID,
			&i.Title,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.TaxTotal,
			&i.Total,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
