// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_summaries.sql

package orderdb

import (
	"context"
)

const createOrderSummary = `-- name: CreateOrderSummary :one

INSERT INTO order_summaries (id, order_id)
VALUES ($1, $2)
RETURNING id, order_id, paid_total, refunded_total, created_at, updated_at
`

type CreateOrderSummaryParams struct {
	ID      string
	OrderID string
}

// order_summaries sorguları.
//
// Özet siparişle BİRLİKTE ve sıfırlanmış olarak doğar; "özeti olmayan sipariş"
// diye bir durum yoktur.
func (q *Queries) CreateOrderSummary(ctx context.Context, arg CreateOrderSummaryParams) (OrderSummary, error) {
	row := q.db.QueryRow(ctx, createOrderSummary, arg.ID, arg.OrderID)
	var i OrderSummary
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaidTotal,
		&i.RefundedTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderSummary = `-- name: GetOrderSummary :one
SELECT id, order_id, paid_total, refunded_total, created_at, updated_at FROM order_summaries
WHERE order_id = $1
`

func (q *Queries) GetOrderSummary(ctx context.Context, orderID string) (OrderSummary, error) {
	row := q.db.QueryRow(ctx, getOrderSummary, orderID)
	var i OrderSummary
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaidTotal,
		&i.RefundedTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOrderSummaryTotals = `-- name: SetOrderSummaryTotals :one
UPDATE order_summaries
SET paid_total     = GREATEST(paid_total, $2),
    refunded_total = GREATEST(refunded_total, $3),
    updated_at     = now()
WHERE order_id = $1
RETURNING id, order_id, paid_total, refunded_total, created_at, updated_at
`

type SetOrderSummaryTotalsParams struct {
	OrderID       string
	PaidTotal     int64
	RefundedTotal int64
}

// SetOrderSummaryTotals ödenen ve iade edilen KÜMÜLATİF tutarları birleştirir.
//
// Artımlı (paid_total = paid_total + $2) bir yazma seçilmedi: ödeme olayları
// en az bir kez teslim edilir (bkz. core/eventbus) ve tekrarlanan bir olay
// artımlı yazmada tutarı İKİ KEZ eklerdi.
//
// Ama düz mutlak yazma da (paid_total = $2) yetmez: en-az-bir-kez teslim SIRA
// garantisi VERMEZ. Gecikmiş bir tahsilat olayı yeniden işlendiğinde, daha
// sonra kaydedilmiş bir iadeyi sıfıra yazar ve kimse hata görmezdi. Bu yüzden
// yazma GREATEST ile birleştirilir: iki tutar da siparişin ÖMÜR BOYU
// toplamlarıdır ve yalnızca BÜYÜYEBİLİR. Sonuç hem idempotent (aynı değer
// ikinci kez zararsız) hem de SIRADAN BAĞIMSIZDIR — hangi sırayla gelirse
// gelsin aynı yere yakınsar ve kaydedilmiş hiçbir tutar kaybolmaz.
//
// Birleştirme order_summaries_refund_within_paid kısıtını KIRAMAZ: her iki
// girdi de refunded <= paid sağlıyorsa max(r1,r2) <= max(p1,p2) da sağlanır.
func (q *Queries) SetOrderSummaryTotals(ctx context.Context, arg SetOrderSummaryTotalsParams) (OrderSummary, error) {
	row := q.db.QueryRow(ctx, setOrderSummaryTotals, arg.OrderID, arg.PaidTotal, arg.RefundedTotal)
	var i OrderSummary
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaidTotal,
		&i.RefundedTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
