// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spending.sql

package orderdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sumCustomerSpend = `-- name: SumCustomerSpend :one

SELECT COALESCE(SUM(o.total - COALESCE(s.refunded_total, 0)), 0)::bigint AS spent
FROM orders o
LEFT JOIN order_summaries s ON s.order_id = o.id
WHERE o.customer_id = $1::text
  AND o.currency_code = $2::text
  AND o.deleted_at IS NULL
  AND o.status <> 'canceled'
  AND (
      $3::timestamptz IS NULL
      OR o.placed_at >= $3::timestamptz
  )
`

type SumCustomerSpendParams struct {
	CustomerID   string
	CurrencyCode string
	WindowStart  pgtype.Timestamptz
}

// Spending queries.
//
// This module does not know the spending LIMIT (the limit is the b2b module's
// data); what it does know is SPENDING itself: the sum of the orders a customer
// has placed. That is why the sum is computed here, in the database — pulling the
// rows into the application and summing them there would be a read that grows
// without bound for a customer who placed many orders within the period, and
// because it is not paginated it could silently produce an incomplete total.
// SumCustomerSpend returns the customer's spending within the window.
//
// # What gets summed
//
// CANCELED orders DO NOT ENTER the sum: a cancellation means "this purchase did
// not happen", and letting a canceled order burn the budget would be counting a
// good that was never sold as spending. Soft-deleted orders do not enter either.
//
// 'pending' orders DO ENTER. An order is opened before its payment is taken, and
// if the payment falls through the saga cancels it (status = 'canceled'), so a
// pending order either turns into spending or removes itself from the sum. Not
// counting the pending ones would allow the same budget to be spent a second time
// in the window that opens during payment.
//
// The REFUNDED amount IS SUBTRACTED: if the money went back to the company, the
// budget must come back too. Were it not subtracted, a fully refunded order would
// lock up the employee's budget until the end of the period. The source is the
// order_summaries.refunded_total column, and the side that writes it is the flow
// that knows the payment result (see service.Service.SetOrderSummaryTotals); the
// return FLOW itself does not exist yet (plan Phase 7+), so today the term is in
// practice zero. It is part of the rule all the same: leaving the definition for
// later would mean the budget being silently miscalculated once the return flow
// arrives.
//
// # Currency
//
// The sum is taken in a SINGLE currency and NO conversion is performed: an
// exchange rate exists nowhere in this repository, and two amounts summed with a
// made-up rate would produce a number whose wrongness never becomes visible. That
// is why the sum DOES NOT SEE orders in a different currency; keeping those from
// slipping past the limit is ensured by the caller's currency check
// (see service/spending.go).
//
// # Window
//
// If window_start is NULL there is no window and the customer's ENTIRE history is
// summed (the counterpart of the "never" period in b2b). If it is set, the lower
// bound is INCLUSIVE and the upper bound is open: the start of the window is
// exactly the first instant of the calendar month/year, and the difference between
// ">= " and "> " is which period an order landing on that very instant is written
// to.
func (q *Queries) SumCustomerSpend(ctx context.Context, arg SumCustomerSpendParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumCustomerSpend, arg.CustomerID, arg.CurrencyCode, arg.WindowStart)
	var spent int64
	err := row.Scan(&spent)
	return spent, err
}
