// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_group.sql

package customerdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCustomerToGroup = `-- name: AddCustomerToGroup :exec
INSERT INTO customer_group_customer (customer_id, customer_group_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (customer_id, customer_group_id) DO NOTHING
`

type AddCustomerToGroupParams struct {
	CustomerID      string
	CustomerGroupID string
	CreatedAt       pgtype.Timestamptz
}

// AddCustomerToGroup üyeliği yazar; zaten varsa hiçbir şey yapmaz.
//
// Üyelik bir KÜMEDİR: aynı çağrının iki kez gelmesi (yeniden deneme, çift
// tıklama) hata değil, aynı sonuçtur. ON CONFLICT DO NOTHING bu idempotansı
// tek satırda ifade eder.
func (q *Queries) AddCustomerToGroup(ctx context.Context, arg AddCustomerToGroupParams) error {
	_, err := q.db.Exec(ctx, addCustomerToGroup, arg.CustomerID, arg.CustomerGroupID, arg.CreatedAt)
	return err
}

const countCustomerGroups = `-- name: CountCustomerGroups :one
SELECT count(*) FROM customer_group
WHERE deleted_at IS NULL
`

func (q *Queries) CountCustomerGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomerGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCustomerGroup = `-- name: GetCustomerGroup :one
SELECT id, name, metadata, created_at, updated_at, deleted_at FROM customer_group
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerGroup(ctx context.Context, id string) (CustomerGroup, error) {
	row := q.db.QueryRow(ctx, getCustomerGroup, id)
	var i CustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertCustomerGroup = `-- name: InsertCustomerGroup :one

INSERT INTO customer_group (id, name, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, name, metadata, created_at, updated_at, deleted_at
`

type InsertCustomerGroupParams struct {
	ID        string
	Name      string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

// customer_group ve üyelik sorguları.
func (q *Queries) InsertCustomerGroup(ctx context.Context, arg InsertCustomerGroupParams) (CustomerGroup, error) {
	row := q.db.QueryRow(ctx, insertCustomerGroup,
		arg.ID,
		arg.Name,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i CustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCustomerGroups = `-- name: ListCustomerGroups :many
SELECT id, name, metadata, created_at, updated_at, deleted_at FROM customer_group
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2::int OFFSET $1::int
`

type ListCustomerGroupsParams struct {
	Off int32
	Lim int32
}

func (q *Queries) ListCustomerGroups(ctx context.Context, arg ListCustomerGroupsParams) ([]CustomerGroup, error) {
	rows, err := q.db.Query(ctx, listCustomerGroups, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerGroup{}
	for rows.Next() {
		var i CustomerGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupIDsOfCustomers = `-- name: ListGroupIDsOfCustomers :many
SELECT m.customer_id, m.customer_group_id
FROM customer_group_customer m
JOIN customer_group g ON g.id = m.customer_group_id
WHERE m.customer_id = ANY($1::text[]) AND g.deleted_at IS NULL
ORDER BY m.customer_id, m.customer_group_id
`

type ListGroupIDsOfCustomersRow struct {
	CustomerID      string
	CustomerGroupID string
}

// ListGroupIDsOfCustomers birden çok müşterinin grup kimliklerini TEK sorguda
// döner.
//
// Query sağlayıcısı müşterileri grup kimlikleriyle birlikte sunar; müşteri
// başına ayrı sorgu, ADR 0004'ün yapısal olarak yasakladığı N+1 olurdu.
func (q *Queries) ListGroupIDsOfCustomers(ctx context.Context, customerIds []string) ([]ListGroupIDsOfCustomersRow, error) {
	rows, err := q.db.Query(ctx, listGroupIDsOfCustomers, customerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupIDsOfCustomersRow{}
	for rows.Next() {
		var i ListGroupIDsOfCustomersRow
		if err := rows.Scan(&i.CustomerID, &i.CustomerGroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsOfCustomer = `-- name: ListGroupsOfCustomer :many
SELECT g.id, g.name, g.metadata, g.created_at, g.updated_at, g.deleted_at FROM customer_group g
JOIN customer_group_customer m ON m.customer_group_id = g.id
WHERE m.customer_id = $1 AND g.deleted_at IS NULL
ORDER BY g.created_at DESC, g.id DESC
`

func (q *Queries) ListGroupsOfCustomer(ctx context.Context, customerID string) ([]CustomerGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsOfCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerGroup{}
	for rows.Next() {
		var i CustomerGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCustomerFromGroup = `-- name: RemoveCustomerFromGroup :execrows
DELETE FROM customer_group_customer
WHERE customer_id = $1 AND customer_group_id = $2
`

type RemoveCustomerFromGroupParams struct {
	CustomerID      string
	CustomerGroupID string
}

// RemoveCustomerFromGroup üyeliği siler ve SİLİNEN SATIR SAYISINI döner.
//
// Sayı, "üyelik yoktu" ile "üyelik kaldırıldı" ayrımını yapan tek bilgidir;
// servis olmayan bir üyeliğin kaldırılması isteğine errors.NotFound döner.
func (q *Queries) RemoveCustomerFromGroup(ctx context.Context, arg RemoveCustomerFromGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeCustomerFromGroup, arg.CustomerID, arg.CustomerGroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteCustomerGroup = `-- name: SoftDeleteCustomerGroup :one
UPDATE customer_group
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteCustomerGroupParams struct {
	ID        string
	DeletedAt pgtype.Timestamptz
}

// SoftDeleteCustomerGroup grubu yumuşak siler.
//
// Üyelik satırları BIRAKILIR: silinmiş grup zaten hiçbir okumada görünmez
// (grup okuyan her sorgu deleted_at IS NULL süzer) ve satırlar kayıt bir gün
// gerçekten silindiğinde cascade ile gider. Ad, kısmi benzersiz indeksin
// kapsamından çıktığı için yeniden kullanılabilir hâle gelir.
func (q *Queries) SoftDeleteCustomerGroup(ctx context.Context, arg SoftDeleteCustomerGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteCustomerGroup, arg.ID, arg.DeletedAt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateCustomerGroup = `-- name: UpdateCustomerGroup :one
UPDATE customer_group SET
    name       = COALESCE($1::text, name),
    metadata   = COALESCE($2::jsonb, metadata),
    updated_at = $3
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, name, metadata, created_at, updated_at, deleted_at
`

type UpdateCustomerGroupParams struct {
	Name      *string
	Metadata  []byte
	UpdatedAt pgtype.Timestamptz
	ID        string
}

// UpdateCustomerGroup verilmeyen alanları OLDUĞU GİBİ bırakır.
//
// Adın düzeltilebilmesi şarttır: ad canlı gruplar arasında benzersizdir ve
// yanlış girilmiş bir ad, düzeltme yolu olmadan o adı sonsuza dek işgal
// ederdi.
func (q *Queries) UpdateCustomerGroup(ctx context.Context, arg UpdateCustomerGroupParams) (CustomerGroup, error) {
	row := q.db.QueryRow(ctx, updateCustomerGroup,
		arg.Name,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ID,
	)
	var i CustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
