// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package customerdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountEmailTakenByOther = `-- name: AccountEmailTakenByOther :one
SELECT EXISTS (
    SELECT 1 FROM customer
    WHERE email = $1 AND id <> $2 AND has_account AND deleted_at IS NULL
)
`

type AccountEmailTakenByOtherParams struct {
	Email string
	ID    string
}

// AccountEmailTakenByOther verilen e-postayı BAŞKA bir hesabın kullanıp
// kullanmadığını bildirir; misafirden hesaba geçişin ön denetimidir.
func (q *Queries) AccountEmailTakenByOther(ctx context.Context, arg AccountEmailTakenByOtherParams) (bool, error) {
	row := q.db.QueryRow(ctx, accountEmailTakenByOther, arg.Email, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCustomers = `-- name: CountCustomers :one
SELECT count(*) FROM customer c
WHERE c.deleted_at IS NULL
  AND ($1::text IS NULL OR c.email = $1::text)
  AND ($2::boolean IS NULL OR c.has_account = $2::boolean)
  AND ($3::text IS NULL OR EXISTS (
        SELECT 1 FROM customer_group_customer m
        JOIN customer_group g ON g.id = m.customer_group_id AND g.deleted_at IS NULL
        WHERE m.customer_id = c.id AND m.customer_group_id = $3::text))
`

type CountCustomersParams struct {
	Email      *string
	HasAccount *bool
	GroupID    *string
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, arg.Email, arg.HasAccount, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, first_name, last_name, phone, has_account, metadata, created_at, updated_at, deleted_at FROM customer
WHERE email = $1 AND has_account AND deleted_at IS NULL
`

// GetAccountByEmail YALNIZCA kayıtlı hesabı arar.
//
// Misafir kayıtları aynı e-postayı paylaşabildiği için "e-postaya göre tek
// müşteri" ancak hesaplar için anlamlıdır; bu sorgunun has_account süzgeci
// kısmi benzersiz indeksin kapsamıyla birebir aynıdır.
func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.HasAccount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, email, first_name, last_name, phone, has_account, metadata, created_at, updated_at, deleted_at FROM customer
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomer(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.HasAccount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerForUpdate = `-- name: GetCustomerForUpdate :one
SELECT id, email, first_name, last_name, phone, has_account, metadata, created_at, updated_at, deleted_at FROM customer
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// GetCustomerForUpdate müşteriyi okur ve satırını İŞLEM SONUNA KADAR kilitler.
//
// Aynı müşteriye yapılan durum değiştiren akışlar (misafirden hesaba geçiş,
// varsayılan adres atama) bu kilidi HER ZAMAN İLK sırada alır. Sıra sabit
// olduğu için iki akış birbirini ters sırada bekleyemez; kilitlenme (deadlock)
// yapısal olarak imkânsızdır.
//
// FOR UPDATE kilit alındıktan sonra WHERE koşulunu YENİDEN değerlendirir; araya
// giren bir silme bu yüzden "kayıt yok" olarak görünür.
func (q *Queries) GetCustomerForUpdate(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerForUpdate, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.HasAccount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertCustomer = `-- name: InsertCustomer :one

INSERT INTO customer (id, email, first_name, last_name, phone, has_account, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, email, first_name, last_name, phone, has_account, metadata, created_at, updated_at, deleted_at
`

type InsertCustomerParams struct {
	ID         string
	Email      string
	FirstName  string
	LastName   string
	Phone      string
	HasAccount bool
	Metadata   []byte
	CreatedAt  pgtype.Timestamptz
}

// customer sorguları. Tüm okumalar deleted_at IS NULL filtresi uygular.
func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, insertCustomer,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.HasAccount,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.HasAccount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT c.id, c.email, c.first_name, c.last_name, c.phone, c.has_account, c.metadata, c.created_at, c.updated_at, c.deleted_at FROM customer c
WHERE c.deleted_at IS NULL
  AND ($1::text IS NULL OR c.email = $1::text)
  AND ($2::boolean IS NULL OR c.has_account = $2::boolean)
  AND ($3::text IS NULL OR EXISTS (
        SELECT 1 FROM customer_group_customer m
        JOIN customer_group g ON g.id = m.customer_group_id AND g.deleted_at IS NULL
        WHERE m.customer_id = c.id AND m.customer_group_id = $3::text))
  AND (c.created_at, c.id) < (
    COALESCE($4::timestamptz, 'infinity'::timestamptz),
    COALESCE($5::text, '')
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $7::int OFFSET $6::int
`

type ListCustomersParams struct {
	Email      *string
	HasAccount *bool
	GroupID    *string
	AfterAt    pgtype.Timestamptz
	AfterID    *string
	Off        int32
	Lim        int32
}

// ListCustomers süzgeçlenmiş ve sayfalanmış müşteri listesini döner.
//
// group_id süzgeci üyelik satırına DEĞİL, canlı gruba bakar: üyelik satırları
// grup yumuşak silindiğinde de yerinde kalır ve yalnızca üyeliğe bakan bir
// süzgeç, silinmiş bir grubun üyelerini listelemeye devam ederdi. Grubu okuyan
// her sorgu deleted_at IS NULL süzer; burası da aynı kurala uyar.
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.Email,
		arg.HasAccount,
		arg.GroupID,
		arg.AfterAt,
		arg.AfterID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.HasAccount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByIDs = `-- name: ListCustomersByIDs :many
SELECT id, email, first_name, last_name, phone, has_account, metadata, created_at, updated_at, deleted_at FROM customer
WHERE id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListCustomersByIDs(ctx context.Context, ids []string) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.HasAccount,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteCustomerToAccount = `-- name: PromoteCustomerToAccount :one
UPDATE customer
SET has_account = TRUE, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL AND has_account = FALSE
RETURNING id, email, first_name, last_name, phone, has_account, metadata, created_at, updated_at, deleted_at
`

type PromoteCustomerToAccountParams struct {
	ID        string
	UpdatedAt pgtype.Timestamptz
}

// PromoteCustomerToAccount misafiri hesaba çevirir.
//
// has_account = FALSE koşulu şarttır: zaten hesap olan bir kaydı yeniden
// yükseltmek sessiz bir no-op olurdu ve çağıran işlemin gerçekleştiğini
// sanırdı. Koşul tutmazsa satır dönmez ve servis durumu ayırt eder.
func (q *Queries) PromoteCustomerToAccount(ctx context.Context, arg PromoteCustomerToAccountParams) (Customer, error) {
	row := q.db.QueryRow(ctx, promoteCustomerToAccount, arg.ID, arg.UpdatedAt)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.HasAccount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteAddressesOfCustomer = `-- name: SoftDeleteAddressesOfCustomer :exec
UPDATE customer_address
SET deleted_at = $2, updated_at = $2
WHERE customer_id = $1 AND deleted_at IS NULL
`

type SoftDeleteAddressesOfCustomerParams struct {
	CustomerID string
	DeletedAt  pgtype.Timestamptz
}

// SoftDeleteAddressesOfCustomer müşteri silinirken adreslerini de siler.
//
// Foreign key ON DELETE CASCADE yalnızca GERÇEK silmede çalışır; yumuşak silme
// bir UPDATE olduğu için adresleri kendiliğinden götürmez. Silinmiş bir
// müşterinin canlı adresleri geride kalsaydı, adres listeleri sahipsiz kayıt
// gösterirdi.
func (q *Queries) SoftDeleteAddressesOfCustomer(ctx context.Context, arg SoftDeleteAddressesOfCustomerParams) error {
	_, err := q.db.Exec(ctx, softDeleteAddressesOfCustomer, arg.CustomerID, arg.DeletedAt)
	return err
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :one
UPDATE customer
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteCustomerParams struct {
	ID        string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteCustomer(ctx context.Context, arg SoftDeleteCustomerParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteCustomer, arg.ID, arg.DeletedAt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customer SET
    email      = COALESCE($1::text, email),
    first_name = COALESCE($2::text, first_name),
    last_name  = COALESCE($3::text, last_name),
    phone      = COALESCE($4::text, phone),
    metadata   = COALESCE($5::jsonb, metadata),
    updated_at = $6
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, email, first_name, last_name, phone, has_account, metadata, created_at, updated_at, deleted_at
`

type UpdateCustomerParams struct {
	Email     *string
	FirstName *string
	LastName  *string
	Phone     *string
	Metadata  []byte
	UpdatedAt pgtype.Timestamptz
	ID        string
}

// UpdateCustomer verilmeyen alanları OLDUĞU GİBİ bırakır.
//
// COALESCE ile yazılan bu kısmi güncelleme, "alan gönderilmedi" ile "alan boşa
// çekildi" ayrımını korur: NULL parametre eski değeri saklar, boş dize gerçek
// bir temizlemedir.
func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.HasAccount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
