// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_wishlist.sql

package customerdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const armStockAlert = `-- name: ArmStockAlert :execrows
UPDATE customer_wishlist_item
SET stock_alert_armed_at = now()
WHERE customer_id = $1 AND variant_id = $2 AND stock_alert AND stock_alert_armed_at IS NULL
`

type ArmStockAlertParams struct {
	CustomerID string
	VariantID  string
}

// ArmStockAlert records that a marked variant was seen out of stock.
func (q *Queries) ArmStockAlert(ctx context.Context, arg ArmStockAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, armStockAlert, arg.CustomerID, arg.VariantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearStockAlert = `-- name: ClearStockAlert :execrows
UPDATE customer_wishlist_item
SET stock_alert = false, stock_alert_channels = NULL, stock_alert_armed_at = NULL
WHERE customer_id = $1 AND variant_id = $2 AND stock_alert_armed_at = $3
`

type ClearStockAlertParams struct {
	CustomerID        string
	VariantID         string
	StockAlertArmedAt pgtype.Timestamptz
}

// ClearStockAlert clears a mark once its mail went, only if it is still the
// arming the mail was sent for.
func (q *Queries) ClearStockAlert(ctx context.Context, arg ClearStockAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearStockAlert, arg.CustomerID, arg.VariantID, arg.StockAlertArmedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countWishlistItems = `-- name: CountWishlistItems :one
SELECT count(*)::bigint AS item_count FROM customer_wishlist_item
WHERE customer_id = $1
`

func (q *Queries) CountWishlistItems(ctx context.Context, customerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countWishlistItems, customerID)
	var item_count int64
	err := row.Scan(&item_count)
	return item_count, err
}

const deleteWishlistItem = `-- name: DeleteWishlistItem :execrows
DELETE FROM customer_wishlist_item
WHERE customer_id = $1 AND variant_id = $2
`

type DeleteWishlistItemParams struct {
	CustomerID string
	VariantID  string
}

func (q *Queries) DeleteWishlistItem(ctx context.Context, arg DeleteWishlistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWishlistItem, arg.CustomerID, arg.VariantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWishlistOfCustomer = `-- name: DeleteWishlistOfCustomer :execrows
DELETE FROM customer_wishlist_item
WHERE customer_id = $1
`

// DeleteWishlistOfCustomer is the erasure's: a wishlist row is the person's
// stated preference and nothing else refers to it.
func (q *Queries) DeleteWishlistOfCustomer(ctx context.Context, customerID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWishlistOfCustomer, customerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWishlistItem = `-- name: GetWishlistItem :one
SELECT customer_id, variant_id, created_at, stock_alert, stock_alert_channels, stock_alert_armed_at FROM customer_wishlist_item
WHERE customer_id = $1 AND variant_id = $2
`

type GetWishlistItemParams struct {
	CustomerID string
	VariantID  string
}

func (q *Queries) GetWishlistItem(ctx context.Context, arg GetWishlistItemParams) (CustomerWishlistItem, error) {
	row := q.db.QueryRow(ctx, getWishlistItem, arg.CustomerID, arg.VariantID)
	var i CustomerWishlistItem
	err := row.Scan(
		&i.CustomerID,
		&i.VariantID,
		&i.CreatedAt,
		&i.StockAlert,
		&i.StockAlertChannels,
		&i.StockAlertArmedAt,
	)
	return i, err
}

const insertWishlistItem = `-- name: InsertWishlistItem :one

INSERT INTO customer_wishlist_item (customer_id, variant_id, created_at)
VALUES ($1, $2, $3)
RETURNING customer_id, variant_id, created_at, stock_alert, stock_alert_channels, stock_alert_armed_at
`

type InsertWishlistItemParams struct {
	CustomerID string
	VariantID  string
	CreatedAt  pgtype.Timestamptz
}

// A customer's wishlist (ADR 0190).
//
// Every write runs under the customer row's lock (GetCustomerForUpdate), so the
// count and the insert that follows it see the same list.
func (q *Queries) InsertWishlistItem(ctx context.Context, arg InsertWishlistItemParams) (CustomerWishlistItem, error) {
	row := q.db.QueryRow(ctx, insertWishlistItem, arg.CustomerID, arg.VariantID, arg.CreatedAt)
	var i CustomerWishlistItem
	err := row.Scan(
		&i.CustomerID,
		&i.VariantID,
		&i.CreatedAt,
		&i.StockAlert,
		&i.StockAlertChannels,
		&i.StockAlertArmedAt,
	)
	return i, err
}

const listStockAlerts = `-- name: ListStockAlerts :many
SELECT w.customer_id, w.variant_id, w.created_at, w.stock_alert, w.stock_alert_channels, w.stock_alert_armed_at FROM customer_wishlist_item w
JOIN customer c ON c.id = w.customer_id
WHERE w.stock_alert AND c.deleted_at IS NULL
  AND (w.customer_id, w.variant_id) > ($1::text, $2::text)
ORDER BY w.customer_id, w.variant_id
LIMIT $3
`

type ListStockAlertsParams struct {
	AfterCustomerID string
	AfterVariantID  string
	RowLimit        int32
}

// ListStockAlerts pages the marked items of live customers in key order.
func (q *Queries) ListStockAlerts(ctx context.Context, arg ListStockAlertsParams) ([]CustomerWishlistItem, error) {
	rows, err := q.db.Query(ctx, listStockAlerts, arg.AfterCustomerID, arg.AfterVariantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerWishlistItem{}
	for rows.Next() {
		var i CustomerWishlistItem
		if err := rows.Scan(
			&i.CustomerID,
			&i.VariantID,
			&i.CreatedAt,
			&i.StockAlert,
			&i.StockAlertChannels,
			&i.StockAlertArmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishlistForDisclosure = `-- name: ListWishlistForDisclosure :many
SELECT customer_id, variant_id, created_at, stock_alert, stock_alert_channels, stock_alert_armed_at FROM customer_wishlist_item
WHERE customer_id = ANY ($1::text[])
ORDER BY customer_id, created_at, variant_id
`

func (q *Queries) ListWishlistForDisclosure(ctx context.Context, customerIds []string) ([]CustomerWishlistItem, error) {
	rows, err := q.db.Query(ctx, listWishlistForDisclosure, customerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerWishlistItem{}
	for rows.Next() {
		var i CustomerWishlistItem
		if err := rows.Scan(
			&i.CustomerID,
			&i.VariantID,
			&i.CreatedAt,
			&i.StockAlert,
			&i.StockAlertChannels,
			&i.StockAlertArmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishlistItems = `-- name: ListWishlistItems :many
SELECT customer_id, variant_id, created_at, stock_alert, stock_alert_channels, stock_alert_armed_at FROM customer_wishlist_item
WHERE customer_id = $1
ORDER BY created_at DESC, variant_id
`

// ListWishlistItems is not paged: the cap bounds it when it is written.
func (q *Queries) ListWishlistItems(ctx context.Context, customerID string) ([]CustomerWishlistItem, error) {
	rows, err := q.db.Query(ctx, listWishlistItems, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerWishlistItem{}
	for rows.Next() {
		var i CustomerWishlistItem
		if err := rows.Scan(
			&i.CustomerID,
			&i.VariantID,
			&i.CreatedAt,
			&i.StockAlert,
			&i.StockAlertChannels,
			&i.StockAlertArmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStockAlert = `-- name: MarkStockAlert :one

UPDATE customer_wishlist_item
SET stock_alert = true,
    stock_alert_channels = $1::text[],
    stock_alert_armed_at = NULL
WHERE customer_id = $2 AND variant_id = $3
RETURNING customer_id, variant_id, created_at, stock_alert, stock_alert_channels, stock_alert_armed_at
`

type MarkStockAlertParams struct {
	Channels   []string
	CustomerID string
	VariantID  string
}

// A wishlist item's stock alert (ADR 0215).
// MarkStockAlert marks an item and forgets any earlier arming: a mark set again
// waits again to see the variant run out.
func (q *Queries) MarkStockAlert(ctx context.Context, arg MarkStockAlertParams) (CustomerWishlistItem, error) {
	row := q.db.QueryRow(ctx, markStockAlert, arg.Channels, arg.CustomerID, arg.VariantID)
	var i CustomerWishlistItem
	err := row.Scan(
		&i.CustomerID,
		&i.VariantID,
		&i.CreatedAt,
		&i.StockAlert,
		&i.StockAlertChannels,
		&i.StockAlertArmedAt,
	)
	return i, err
}

const unmarkStockAlert = `-- name: UnmarkStockAlert :execrows
UPDATE customer_wishlist_item
SET stock_alert = false, stock_alert_channels = NULL, stock_alert_armed_at = NULL
WHERE customer_id = $1 AND variant_id = $2 AND stock_alert
`

type UnmarkStockAlertParams struct {
	CustomerID string
	VariantID  string
}

func (q *Queries) UnmarkStockAlert(ctx context.Context, arg UnmarkStockAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, unmarkStockAlert, arg.CustomerID, arg.VariantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
