// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_group.sql

package customerdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCustomerToGroup = `-- name: AddCustomerToGroup :exec
INSERT INTO customer_group_customer (customer_id, customer_group_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (customer_id, customer_group_id) DO NOTHING
`

type AddCustomerToGroupParams struct {
	CustomerID      string
	CustomerGroupID string
	CreatedAt       pgtype.Timestamptz
}

// AddCustomerToGroup üyeliği yazar; zaten varsa hiçbir şey yapmaz.
//
// Üyelik bir KÜMEDİR: aynı çağrının iki kez gelmesi (yeniden deneme, çift
// tıklama) hata değil, aynı sonuçtur. ON CONFLICT DO NOTHING bu idempotansı
// tek satırda ifade eder.
func (q *Queries) AddCustomerToGroup(ctx context.Context, arg AddCustomerToGroupParams) error {
	_, err := q.db.Exec(ctx, addCustomerToGroup, arg.CustomerID, arg.CustomerGroupID, arg.CreatedAt)
	return err
}

const addSegmentMembers = `-- name: AddSegmentMembers :execrows
INSERT INTO customer_group_customer (customer_id, customer_group_id, created_at)
SELECT c.id, $1, $2
FROM customer c
WHERE c.id = ANY($3::text[]) AND c.deleted_at IS NULL
ON CONFLICT (customer_id, customer_group_id) DO NOTHING
`

type AddSegmentMembersParams struct {
	GroupID   string
	CreatedAt pgtype.Timestamptz
	Members   []string
}

// AddSegmentMembers puts the given live customers in a segment.
func (q *Queries) AddSegmentMembers(ctx context.Context, arg AddSegmentMembersParams) (int64, error) {
	result, err := q.db.Exec(ctx, addSegmentMembers, arg.GroupID, arg.CreatedAt, arg.Members)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearGroupSegment = `-- name: ClearGroupSegment :one
UPDATE customer_group
SET segment = NULL, segment_set_at = NULL, segment_evaluated_at = NULL, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, metadata, created_at, updated_at, deleted_at, rank, segment, segment_set_at, segment_evaluated_at
`

type ClearGroupSegmentParams struct {
	ID        string
	UpdatedAt pgtype.Timestamptz
}

// ClearGroupSegment hands a segment back to the operator; its members stay.
func (q *Queries) ClearGroupSegment(ctx context.Context, arg ClearGroupSegmentParams) (CustomerGroup, error) {
	row := q.db.QueryRow(ctx, clearGroupSegment, arg.ID, arg.UpdatedAt)
	var i CustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Rank,
		&i.Segment,
		&i.SegmentSetAt,
		&i.SegmentEvaluatedAt,
	)
	return i, err
}

const countCustomerGroups = `-- name: CountCustomerGroups :one
SELECT count(*) FROM customer_group
WHERE deleted_at IS NULL
`

func (q *Queries) CountCustomerGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomerGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSegments = `-- name: CountSegments :one
SELECT count(*) FROM customer_group
WHERE segment IS NOT NULL AND deleted_at IS NULL AND id <> $1
`

// CountSegments counts the live segments other than the given group.
func (q *Queries) CountSegments(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, countSegments, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishSegment = `-- name: FinishSegment :execrows
UPDATE customer_group
SET segment_evaluated_at = $1
WHERE id = $2 AND deleted_at IS NULL AND segment_set_at = $3
`

type FinishSegmentParams struct {
	EvaluatedAt pgtype.Timestamptz
	ID          string
	SetAt       pgtype.Timestamptz
}

// FinishSegment records that a pass wrote a segment's members, only while the
// rule it evaluated is still the segment's.
func (q *Queries) FinishSegment(ctx context.Context, arg FinishSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishSegment, arg.EvaluatedAt, arg.ID, arg.SetAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomerGroup = `-- name: GetCustomerGroup :one
SELECT id, name, metadata, created_at, updated_at, deleted_at, rank, segment, segment_set_at, segment_evaluated_at FROM customer_group
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerGroup(ctx context.Context, id string) (CustomerGroup, error) {
	row := q.db.QueryRow(ctx, getCustomerGroup, id)
	var i CustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Rank,
		&i.Segment,
		&i.SegmentSetAt,
		&i.SegmentEvaluatedAt,
	)
	return i, err
}

const insertCustomerGroup = `-- name: InsertCustomerGroup :one

INSERT INTO customer_group (id, name, rank, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id, name, metadata, created_at, updated_at, deleted_at, rank, segment, segment_set_at, segment_evaluated_at
`

type InsertCustomerGroupParams struct {
	ID        string
	Name      string
	Rank      int32
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

// customer_group ve üyelik sorguları.
func (q *Queries) InsertCustomerGroup(ctx context.Context, arg InsertCustomerGroupParams) (CustomerGroup, error) {
	row := q.db.QueryRow(ctx, insertCustomerGroup,
		arg.ID,
		arg.Name,
		arg.Rank,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i CustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Rank,
		&i.Segment,
		&i.SegmentSetAt,
		&i.SegmentEvaluatedAt,
	)
	return i, err
}

const listCustomerGroups = `-- name: ListCustomerGroups :many
SELECT id, name, metadata, created_at, updated_at, deleted_at, rank, segment, segment_set_at, segment_evaluated_at FROM customer_group
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2::int OFFSET $1::int
`

type ListCustomerGroupsParams struct {
	Off int32
	Lim int32
}

func (q *Queries) ListCustomerGroups(ctx context.Context, arg ListCustomerGroupsParams) ([]CustomerGroup, error) {
	rows, err := q.db.Query(ctx, listCustomerGroups, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerGroup{}
	for rows.Next() {
		var i CustomerGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Rank,
			&i.Segment,
			&i.SegmentSetAt,
			&i.SegmentEvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupIDsOfCustomers = `-- name: ListGroupIDsOfCustomers :many
SELECT m.customer_id, m.customer_group_id
FROM customer_group_customer m
JOIN customer_group g ON g.id = m.customer_group_id
WHERE m.customer_id = ANY($1::text[]) AND g.deleted_at IS NULL
ORDER BY m.customer_id, m.customer_group_id
`

type ListGroupIDsOfCustomersRow struct {
	CustomerID      string
	CustomerGroupID string
}

// ListGroupIDsOfCustomers birden çok müşterinin grup kimliklerini TEK sorguda
// döner.
//
// Query sağlayıcısı müşterileri grup kimlikleriyle birlikte sunar; müşteri
// başına ayrı sorgu, ADR 0004'ün yapısal olarak yasakladığı N+1 olurdu.
func (q *Queries) ListGroupIDsOfCustomers(ctx context.Context, customerIds []string) ([]ListGroupIDsOfCustomersRow, error) {
	rows, err := q.db.Query(ctx, listGroupIDsOfCustomers, customerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupIDsOfCustomersRow{}
	for rows.Next() {
		var i ListGroupIDsOfCustomersRow
		if err := rows.Scan(&i.CustomerID, &i.CustomerGroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsOfCustomer = `-- name: ListGroupsOfCustomer :many
SELECT g.id, g.name, g.metadata, g.created_at, g.updated_at, g.deleted_at, g.rank, g.segment, g.segment_set_at, g.segment_evaluated_at FROM customer_group g
JOIN customer_group_customer m ON m.customer_group_id = g.id
WHERE m.customer_id = $1 AND g.deleted_at IS NULL
ORDER BY g.rank, g.id
`

// ListGroupsOfCustomer bir musterinin gruplarini SIRALI dondurur.
//
// Siralama RANK, sonra id: bastaki grup, saticinin sectigi kazanandir. Bu
// siralama ADR 0049 ile SOZLESME haline geldi — Service.CustomerGroupIDs'in
// basi, sepetin kural baglamina yazdigi tek gruptur. Onceki siralama
// (created_at DESC, id DESC) keyfi degildi ama bir SOZ de degildi; simdi soz.
func (q *Queries) ListGroupsOfCustomer(ctx context.Context, customerID string) ([]CustomerGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsOfCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerGroup{}
	for rows.Next() {
		var i CustomerGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Rank,
			&i.Segment,
			&i.SegmentSetAt,
			&i.SegmentEvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegments = `-- name: ListSegments :many
SELECT id, name, metadata, created_at, updated_at, deleted_at, rank, segment, segment_set_at, segment_evaluated_at FROM customer_group
WHERE segment IS NOT NULL AND deleted_at IS NULL
ORDER BY id
LIMIT $1
`

// ListSegments reads the live segments in id order.
func (q *Queries) ListSegments(ctx context.Context, limit int32) ([]CustomerGroup, error) {
	rows, err := q.db.Query(ctx, listSegments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerGroup{}
	for rows.Next() {
		var i CustomerGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Rank,
			&i.Segment,
			&i.SegmentSetAt,
			&i.SegmentEvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSegment = `-- name: LockSegment :one
SELECT segment_set_at FROM customer_group
WHERE id = $1 AND deleted_at IS NULL AND segment IS NOT NULL
FOR UPDATE
`

// LockSegment locks a live segment's row and returns the moment of its rule;
// no row is a group that is gone or is no segment any more.
func (q *Queries) LockSegment(ctx context.Context, id string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lockSegment, id)
	var segment_set_at pgtype.Timestamptz
	err := row.Scan(&segment_set_at)
	return segment_set_at, err
}

const lockSegmentCount = `-- name: LockSegmentCount :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// LockSegmentCount serializes the writers that turn a group into a segment, so
// the count under MaxSegments is the count they all see. The key is the
// repository's SegmentCountLockKey.
func (q *Queries) LockSegmentCount(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, lockSegmentCount, lockKey)
	return err
}

const removeCustomerFromGroup = `-- name: RemoveCustomerFromGroup :execrows
DELETE FROM customer_group_customer
WHERE customer_id = $1 AND customer_group_id = $2
`

type RemoveCustomerFromGroupParams struct {
	CustomerID      string
	CustomerGroupID string
}

// RemoveCustomerFromGroup üyeliği siler ve SİLİNEN SATIR SAYISINI döner.
//
// Sayı, "üyelik yoktu" ile "üyelik kaldırıldı" ayrımını yapan tek bilgidir;
// servis olmayan bir üyeliğin kaldırılması isteğine errors.NotFound döner.
func (q *Queries) RemoveCustomerFromGroup(ctx context.Context, arg RemoveCustomerFromGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeCustomerFromGroup, arg.CustomerID, arg.CustomerGroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeSegmentStrays = `-- name: RemoveSegmentStrays :execrows
DELETE FROM customer_group_customer
WHERE customer_group_id = $1
  AND customer_id > $2::text
  AND ($3::text = '' OR customer_id <= $3::text)
  AND NOT (customer_id = ANY($4::text[]))
`

type RemoveSegmentStraysParams struct {
	GroupID string
	AfterID string
	LastID  string
	Members []string
}

// RemoveSegmentStrays takes out of a segment the members whose id falls in
// (after_id, last_id] and who are not among the given ones; an empty last_id
// reaches the end of the ids.
func (q *Queries) RemoveSegmentStrays(ctx context.Context, arg RemoveSegmentStraysParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSegmentStrays,
		arg.GroupID,
		arg.AfterID,
		arg.LastID,
		arg.Members,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGroupSegment = `-- name: SetGroupSegment :one
UPDATE customer_group
SET segment = $1, segment_set_at = $2,
    segment_evaluated_at = NULL, updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, metadata, created_at, updated_at, deleted_at, rank, segment, segment_set_at, segment_evaluated_at
`

type SetGroupSegmentParams struct {
	Segment []byte
	SetAt   pgtype.Timestamptz
	ID      string
}

// SetGroupSegment makes a group a segment with the given rule, or gives it a
// new rule (ADR 0217). The rule's moment is new, so a pass that read the old
// rule writes nothing more, and the group waits for its next evaluation.
func (q *Queries) SetGroupSegment(ctx context.Context, arg SetGroupSegmentParams) (CustomerGroup, error) {
	row := q.db.QueryRow(ctx, setGroupSegment, arg.Segment, arg.SetAt, arg.ID)
	var i CustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Rank,
		&i.Segment,
		&i.SegmentSetAt,
		&i.SegmentEvaluatedAt,
	)
	return i, err
}

const softDeleteCustomerGroup = `-- name: SoftDeleteCustomerGroup :one
UPDATE customer_group
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteCustomerGroupParams struct {
	ID        string
	DeletedAt pgtype.Timestamptz
}

// SoftDeleteCustomerGroup grubu yumuşak siler.
//
// Üyelik satırları BIRAKILIR: silinmiş grup zaten hiçbir okumada görünmez
// (grup okuyan her sorgu deleted_at IS NULL süzer) ve satırlar kayıt bir gün
// gerçekten silindiğinde cascade ile gider. Ad, kısmi benzersiz indeksin
// kapsamından çıktığı için yeniden kullanılabilir hâle gelir.
func (q *Queries) SoftDeleteCustomerGroup(ctx context.Context, arg SoftDeleteCustomerGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteCustomerGroup, arg.ID, arg.DeletedAt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateCustomerGroup = `-- name: UpdateCustomerGroup :one
UPDATE customer_group SET
    name       = COALESCE($1::text, name),
    -- rank is nullable in the ARGUMENT and not in the column: a nil means "do
    -- not touch", which is what lets a merchant rename a group without silently
    -- resetting the order they set (ADR 0049).
    rank       = COALESCE($2::int, rank),
    metadata   = COALESCE($3::jsonb, metadata),
    updated_at = $4
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, name, metadata, created_at, updated_at, deleted_at, rank, segment, segment_set_at, segment_evaluated_at
`

type UpdateCustomerGroupParams struct {
	Name      *string
	Rank      *int32
	Metadata  []byte
	UpdatedAt pgtype.Timestamptz
	ID        string
}

// UpdateCustomerGroup verilmeyen alanları OLDUĞU GİBİ bırakır.
//
// Adın düzeltilebilmesi şarttır: ad canlı gruplar arasında benzersizdir ve
// yanlış girilmiş bir ad, düzeltme yolu olmadan o adı sonsuza dek işgal
// ederdi.
func (q *Queries) UpdateCustomerGroup(ctx context.Context, arg UpdateCustomerGroupParams) (CustomerGroup, error) {
	row := q.db.QueryRow(ctx, updateCustomerGroup,
		arg.Name,
		arg.Rank,
		arg.Metadata,
		arg.UpdatedAt,
		arg.ID,
	)
	var i CustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Rank,
		&i.Segment,
		&i.SegmentSetAt,
		&i.SegmentEvaluatedAt,
	)
	return i, err
}
