// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package settingsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StoreProfile struct {
	ID          string
	LegalName   string
	TaxNumber   string
	TaxOffice   string
	Email       string
	Address     string
	CountryCode string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
