// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_profile.sql

package settingsdb

import (
	"context"
)

const getStoreProfile = `-- name: GetStoreProfile :one

SELECT id, legal_name, tax_number, tax_office, email, address, country_code, created_at, updated_at FROM store_profile
WHERE id = $1
`

// store_profile queries: who the shop is.
// GetStoreProfile reads the single row.
//
// The identifier is passed rather than hardcoded here so the query stays a
// statement about a table; the ONE row is the schema's rule (store_profile_singleton)
// and the service holds the name.
func (q *Queries) GetStoreProfile(ctx context.Context, id string) (StoreProfile, error) {
	row := q.db.QueryRow(ctx, getStoreProfile, id)
	var i StoreProfile
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TaxNumber,
		&i.TaxOffice,
		&i.Email,
		&i.Address,
		&i.CountryCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStoreProfile = `-- name: UpsertStoreProfile :one
INSERT INTO store_profile (
    id, legal_name, tax_number, tax_office, email, address, country_code
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id)
DO UPDATE SET
    legal_name   = EXCLUDED.legal_name,
    tax_number   = EXCLUDED.tax_number,
    tax_office   = EXCLUDED.tax_office,
    email        = EXCLUDED.email,
    address      = EXCLUDED.address,
    country_code = EXCLUDED.country_code,
    updated_at   = now()
RETURNING id, legal_name, tax_number, tax_office, email, address, country_code, created_at, updated_at
`

type UpsertStoreProfileParams struct {
	ID          string
	LegalName   string
	TaxNumber   string
	TaxOffice   string
	Email       string
	Address     string
	CountryCode string
}

// UpsertStoreProfile writes the profile, replacing what was there.
//
// One statement, not "read then insert or update": the two would race, and the
// row this table holds is the one every document is printed against. A caller
// sends the whole record because that is what an identity is -- a half-written
// one is a document that names a shop that does not exist.
func (q *Queries) UpsertStoreProfile(ctx context.Context, arg UpsertStoreProfileParams) (StoreProfile, error) {
	row := q.db.QueryRow(ctx, upsertStoreProfile,
		arg.ID,
		arg.LegalName,
		arg.TaxNumber,
		arg.TaxOffice,
		arg.Email,
		arg.Address,
		arg.CountryCode,
	)
	var i StoreProfile
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TaxNumber,
		&i.TaxOffice,
		&i.Email,
		&i.Address,
		&i.CountryCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
