// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_profile_revise.sql

package settingsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStoreProfile = `-- name: CreateStoreProfile :one
INSERT INTO store_profile (
    id, legal_name, tax_number, tax_office, email, address, country_code
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (id) DO NOTHING
RETURNING id, legal_name, tax_number, tax_office, email, address, country_code, created_at, updated_at
`

type CreateStoreProfileParams struct {
	ID          string
	LegalName   string
	TaxNumber   string
	TaxOffice   string
	Email       string
	Address     string
	CountryCode string
}

// CreateStoreProfile writes the first profile, and writes nothing when one
// was written in between (ADR 0336).
func (q *Queries) CreateStoreProfile(ctx context.Context, arg CreateStoreProfileParams) (StoreProfile, error) {
	row := q.db.QueryRow(ctx, createStoreProfile,
		arg.ID,
		arg.LegalName,
		arg.TaxNumber,
		arg.TaxOffice,
		arg.Email,
		arg.Address,
		arg.CountryCode,
	)
	var i StoreProfile
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TaxNumber,
		&i.TaxOffice,
		&i.Email,
		&i.Address,
		&i.CountryCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reviseStoreProfile = `-- name: ReviseStoreProfile :one
UPDATE store_profile
SET legal_name   = $1,
    tax_number   = $2,
    tax_office   = $3,
    email        = $4,
    address      = $5,
    country_code = $6,
    updated_at   = now()
WHERE id = $7
  AND updated_at = $8::timestamptz
RETURNING id, legal_name, tax_number, tax_office, email, address, country_code, created_at, updated_at
`

type ReviseStoreProfileParams struct {
	LegalName     string
	TaxNumber     string
	TaxOffice     string
	Email         string
	Address       string
	CountryCode   string
	ID            string
	ReadUpdatedAt pgtype.Timestamptz
}

// ReviseStoreProfile writes the profile only while it is the one the caller
// read, named by the moment it was last written (ADR 0336). The form writes
// every field, so that moment is exactly what the caller read; a profile
// written in between leaves the row alone.
func (q *Queries) ReviseStoreProfile(ctx context.Context, arg ReviseStoreProfileParams) (StoreProfile, error) {
	row := q.db.QueryRow(ctx, reviseStoreProfile,
		arg.LegalName,
		arg.TaxNumber,
		arg.TaxOffice,
		arg.Email,
		arg.Address,
		arg.CountryCode,
		arg.ID,
		arg.ReadUpdatedAt,
	)
	var i StoreProfile
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TaxNumber,
		&i.TaxOffice,
		&i.Email,
		&i.Address,
		&i.CountryCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
