// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reviewdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Review struct {
	ID             string
	ProductID      string
	Rating         int16
	Title          string
	Body           string
	AuthorName     string
	Status         string
	ModeratedAt    pgtype.Timestamptz
	ModerationNote string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
