// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package reviewdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApprovedReviews = `-- name: CountApprovedReviews :one
SELECT count(*) FROM reviews
WHERE product_id = $1::text AND status = 'approved'
`

func (q *Queries) CountApprovedReviews(ctx context.Context, productID string) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedReviews, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviews = `-- name: CountReviews :one
SELECT count(*) FROM reviews
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR product_id = $2::text)
  AND ($3::text IS NULL
       OR suggested_status = $3::text)
  AND (NOT $4::boolean OR suggested_status IS NULL)
`

type CountReviewsParams struct {
	Status      *string
	ProductID   *string
	Suggested   *string
	Unsuggested bool
}

// The proposal filter is TWO clauses and not one expression with a sentinel.
//
// A single parameter carrying a reserved word for "no proposal" would put that
// word in the SQL and in Go, two copies free to drift; and the word would have
// to be one no status could ever be, which is a promise about a CHECK
// constraint in a different file. Two independent clauses need neither: one is
// an equality, the other a null test, and each is inert when its argument says
// so. The API's single `suggested` parameter is translated into the pair one
// layer up, which is the only place the word "none" appears.
func (q *Queries) CountReviews(ctx context.Context, arg CountReviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviews,
		arg.Status,
		arg.ProductID,
		arg.Suggested,
		arg.Unsuggested,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one

INSERT INTO reviews (
    id, product_id, rating, title, body, author_name, status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, product_id, rating, title, body, author_name, status, moderated_at, moderation_note, created_at, updated_at, suggested_status, suggested_at, suggestion_note, suggestion_model
`

type CreateReviewParams struct {
	ID         string
	ProductID  string
	Rating     int16
	Title      string
	Body       string
	AuthorName string
	Status     string
}

// reviews queries.
//
// The storefront and the admin read the SAME table through different queries,
// and the difference is the point of the module: the storefront's listing and
// its summary both carry status = 'approved' as a LITERAL rather than as a
// parameter, so no request, no filter and no future refactor can widen them.
func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ID,
		arg.ProductID,
		arg.Rating,
		arg.Title,
		arg.Body,
		arg.AuthorName,
		arg.Status,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.AuthorName,
		&i.Status,
		&i.ModeratedAt,
		&i.ModerationNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedStatus,
		&i.SuggestedAt,
		&i.SuggestionNote,
		&i.SuggestionModel,
	)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT id, product_id, rating, title, body, author_name, status, moderated_at, moderation_note, created_at, updated_at, suggested_status, suggested_at, suggestion_note, suggestion_model FROM reviews WHERE id = $1
`

func (q *Queries) GetReview(ctx context.Context, id string) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.AuthorName,
		&i.Status,
		&i.ModeratedAt,
		&i.ModerationNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedStatus,
		&i.SuggestedAt,
		&i.SuggestionNote,
		&i.SuggestionModel,
	)
	return i, err
}

const listApprovedReviews = `-- name: ListApprovedReviews :many
SELECT id, product_id, rating, title, body, author_name, status, moderated_at, moderation_note, created_at, updated_at, suggested_status, suggested_at, suggestion_note, suggestion_model FROM reviews
WHERE product_id = $1::text
  AND status = 'approved'
  AND (created_at, id) < (
    COALESCE($2::timestamptz, 'infinity'::timestamptz),
    COALESCE($3::text, '')
  )
ORDER BY created_at DESC, id DESC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListApprovedReviewsParams struct {
	ProductID string
	AfterAt   pgtype.Timestamptz
	AfterID   *string
	RowOffset int64
	RowLimit  int64
}

// ListApprovedReviews pages the reviews a STOREFRONT may see.
//
// It is a separate query from ListReviews rather than the same one called with
// status = 'approved', and that is the module's central safety property written
// in SQL: here the status is a literal the caller cannot supply, so the one
// listing a shopper reaches cannot be widened by a parameter, a nil pointer or
// a filter that a later change forgets to set. A shared query with a status
// argument would put the whole design one missing assignment away from
// publishing everything ever submitted.
func (q *Queries) ListApprovedReviews(ctx context.Context, arg ListApprovedReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listApprovedReviews,
		arg.ProductID,
		arg.AfterAt,
		arg.AfterID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.AuthorName,
			&i.Status,
			&i.ModeratedAt,
			&i.ModerationNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuggestedStatus,
			&i.SuggestedAt,
			&i.SuggestionNote,
			&i.SuggestionModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT id, product_id, rating, title, body, author_name, status, moderated_at, moderation_note, created_at, updated_at, suggested_status, suggested_at, suggestion_note, suggestion_model FROM reviews
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR product_id = $2::text)
  AND ($3::text IS NULL
       OR suggested_status = $3::text)
  AND (NOT $4::boolean OR suggested_status IS NULL)
  AND (created_at, id) < (
    COALESCE($5::timestamptz, 'infinity'::timestamptz),
    COALESCE($6::text, '')
  )
ORDER BY created_at DESC, id DESC
LIMIT $8::bigint OFFSET $7::bigint
`

type ListReviewsParams struct {
	Status      *string
	ProductID   *string
	Suggested   *string
	Unsuggested bool
	AfterAt     pgtype.Timestamptz
	AfterID     *string
	RowOffset   int64
	RowLimit    int64
}

// ListReviews pages the reviews for the ADMIN surface.
//
// The keyset bound is written with COALESCE sentinels rather than
// "@after IS NULL OR ...": the OR form measures perfectly and then degrades,
// because Postgres folds it away in a custom plan and keeps it as a Filter in a
// generic one, turning the seek into a full index walk. See internal/core/page.
func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviews,
		arg.Status,
		arg.ProductID,
		arg.Suggested,
		arg.Unsuggested,
		arg.AfterAt,
		arg.AfterID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.AuthorName,
			&i.Status,
			&i.ModeratedAt,
			&i.ModerationNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuggestedStatus,
			&i.SuggestedAt,
			&i.SuggestionNote,
			&i.SuggestionModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsAwaitingSuggestion = `-- name: ListReviewsAwaitingSuggestion :many
SELECT id, product_id, rating, title, body, author_name, status, moderated_at, moderation_note, created_at, updated_at, suggested_status, suggested_at, suggestion_note, suggestion_model FROM reviews
WHERE status = 'submitted'
  AND suggested_status IS NULL
ORDER BY created_at, id
LIMIT $1::bigint
`

// ListReviewsAwaitingSuggestion is the JOB's read: reviews waiting for a human,
// about which no model has been asked.
//
// Both narrowings are LITERALS. The status one for the reason every other
// literal in this file is a literal — it is a rule no request may widen — and
// the null check because "awaiting a suggestion" is the whole of what this query
// names; a parameter there would let a caller ask for reviews that already have
// one and pay a model to answer a question already answered.
//
// OLDEST FIRST, which is the queue's own order and the opposite of every other
// listing here. A job with a bounded appetite that took the newest would leave
// the oldest reviews unsuggested forever on a shop that receives more reviews
// per pass than the pass can read.
func (q *Queries) ListReviewsAwaitingSuggestion(ctx context.Context, rowLimit int64) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsAwaitingSuggestion, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.AuthorName,
			&i.Status,
			&i.ModeratedAt,
			&i.ModerationNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuggestedStatus,
			&i.SuggestedAt,
			&i.SuggestionNote,
			&i.SuggestionModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderateReview = `-- name: ModerateReview :one
UPDATE reviews
SET status          = $1::text,
    moderation_note = $2::text,
    moderated_at    = now(),
    updated_at      = now()
WHERE id = $3::text
  AND status = $4::text
RETURNING id, product_id, rating, title, body, author_name, status, moderated_at, moderation_note, created_at, updated_at, suggested_status, suggested_at, suggestion_note, suggestion_model
`

type ModerateReviewParams struct {
	NextStatus     string
	ModerationNote string
	ID             string
	CurrentStatus  string
}

// ModerateReview moves a review and records why.
//
// The WHERE carries the CURRENT status as well, so the move is decided by the
// database rather than by what the caller read a moment ago: two operators
// approving and rejecting at the same instant cannot both win, and the loser is
// told the review moved under them.
//
// moderated_at is stamped from now() and not from the application clock, so the
// moment on the row comes from the same clock as created_at. It is never
// cleared, because no transition returns a review to 'submitted'.
func (q *Queries) ModerateReview(ctx context.Context, arg ModerateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, moderateReview,
		arg.NextStatus,
		arg.ModerationNote,
		arg.ID,
		arg.CurrentStatus,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.AuthorName,
		&i.Status,
		&i.ModeratedAt,
		&i.ModerationNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedStatus,
		&i.SuggestedAt,
		&i.SuggestionNote,
		&i.SuggestionModel,
	)
	return i, err
}

const suggestReview = `-- name: SuggestReview :one
UPDATE reviews
SET suggested_status = $1::text,
    suggestion_note  = $2::text,
    suggestion_model = $3::text,
    suggested_at     = now(),
    updated_at       = now()
WHERE id = $4::text
  AND status = 'submitted'
RETURNING id, product_id, rating, title, body, author_name, status, moderated_at, moderation_note, created_at, updated_at, suggested_status, suggested_at, suggestion_note, suggestion_model
`

type SuggestReviewParams struct {
	SuggestedStatus string
	SuggestionNote  string
	SuggestionModel string
	ID              string
}

// SuggestReview records a model's PROPOSAL about a review that is still
// waiting.
//
// The WHERE carries status = 'submitted' as a LITERAL for the same reason the
// storefront reads do: it is a narrowing no request and no later refactor may
// widen. A proposal about a review an operator has already decided is not a
// smaller version of a useful thing, it is a machine second-guessing a person
// in a column the person cannot answer.
//
// It REPLACES any earlier proposal rather than refusing when one is there. A
// proposal is not a record of anything that happened — nothing was decided, and
// no operator acted on it — so the older sentence has no reader once a newer
// one exists, and keeping it would mean a history table for text nobody
// consulted. What is worth telling apart is a proposal made before a model
// changed, and suggested_at with suggestion_model answers that.
//
// Nothing here touches status or moderated_at. That is the property the whole
// table rests on and it is enforced twice over: this statement does not name
// them, and reviews_moderation_mirror would refuse a row where one moved
// without the other.
func (q *Queries) SuggestReview(ctx context.Context, arg SuggestReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, suggestReview,
		arg.SuggestedStatus,
		arg.SuggestionNote,
		arg.SuggestionModel,
		arg.ID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.AuthorName,
		&i.Status,
		&i.ModeratedAt,
		&i.ModerationNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedStatus,
		&i.SuggestedAt,
		&i.SuggestionNote,
		&i.SuggestionModel,
	)
	return i, err
}

const summarizeApprovedReviews = `-- name: SummarizeApprovedReviews :one
SELECT count(*)::bigint AS review_count,
       COALESCE(round(avg(rating) * 100), 0)::bigint AS average_hundredths
FROM reviews
WHERE product_id = $1::text AND status = 'approved'
`

type SummarizeApprovedReviewsRow struct {
	ReviewCount       int64
	AverageHundredths int64
}

// SummarizeApprovedReviews is the count and the average a product page shows.
//
// The average is COMPUTED HERE and stored nowhere. Measured against PostgreSQL
// 16 on 505,000 reviews over 20,001 products, with the module's partial index:
// 0.2 ms at 19 approved reviews, 1.3-2.0 ms at 5,000, 9.3 ms at 50,000 — and
// 33-38 ms with no index at all, where it is a full sequential scan whatever the
// product's size. A stored counter would save those milliseconds and buy an
// obligation on every path that writes a review; the trade is argued in full on
// the Summary type in the models package.
//
// The average comes back in HUNDREDTHS as a bigint rather than as a numeric:
// avg() returns numeric, the driver would hand it over as a decimal type this
// module would then have to round somewhere, and the rounding decision belongs
// in the one place that can state it. COALESCE covers the product with no
// approved review at all, where avg() is NULL — count is 0 in the same row, so
// the client can tell that zero apart from a genuine average of zero, which
// cannot occur anyway because the rating floor is 1.
func (q *Queries) SummarizeApprovedReviews(ctx context.Context, productID string) (SummarizeApprovedReviewsRow, error) {
	row := q.db.QueryRow(ctx, summarizeApprovedReviews, productID)
	var i SummarizeApprovedReviewsRow
	err := row.Scan(&i.ReviewCount, &i.AverageHundredths)
	return i, err
}

const summarizeSuggestionAgreement = `-- name: SummarizeSuggestionAgreement :many
SELECT suggestion_model AS model,
       count(*) AS decided,
       count(*) FILTER (WHERE suggested_status = status) AS agreed
FROM reviews
WHERE moderated_at IS NOT NULL
  AND suggested_status IS NOT NULL
GROUP BY suggestion_model
ORDER BY suggestion_model
`

type SummarizeSuggestionAgreementRow struct {
	Model   string
	Decided int64
	Agreed  int64
}

// SummarizeSuggestionAgreement counts how often a model's proposal matched the
// decision a person then made.
//
// "Decided" is `moderated_at IS NOT NULL` and not a list of statuses. The
// moment is the column that RECORDS the decision — reviews_moderation_mirror
// ties the two together — so a status added tomorrow lands on the right side of
// this query without anybody remembering to edit it.
//
// Grouped by MODEL because that is the cut a shop acts on: the question is not
// "is the machine good" but "is the one I am paying for better than the one I
// replaced", and a single number over every model that ever ran cannot answer
// it. The total is the sum of the rows and is computed by the caller, so there
// is one query and not two that can disagree.
//
// No rate is computed here or anywhere above. Two counts are the honest
// primitive; a percentage over three decided reviews reads as a measurement.
func (q *Queries) SummarizeSuggestionAgreement(ctx context.Context) ([]SummarizeSuggestionAgreementRow, error) {
	rows, err := q.db.Query(ctx, summarizeSuggestionAgreement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeSuggestionAgreementRow{}
	for rows.Next() {
		var i SummarizeSuggestionAgreementRow
		if err := rows.Scan(&i.Model, &i.Decided, &i.Agreed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
