// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package taxdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TaxRate struct {
	ID          string
	TaxRegionID string
	Name        string
	Code        *string
	RateBps     int32
	IsDefault   bool
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type TaxRateRule struct {
	ID          string
	TaxRateID   string
	Reference   string
	ReferenceID string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type TaxRegion struct {
	ID           string
	CountryCode  string
	ProvinceCode *string
	ParentID     *string
	ProviderID   string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}
