// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tax_class.sql

package taxdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTaxClassMembers = `-- name: CountTaxClassMembers :one
SELECT count(*) FROM tax_class_member
WHERE tax_class_id = $1 AND deleted_at IS NULL
`

// CountTaxClassMembers reports how many products a class still holds; the
// delete reads it to refuse emptying a class out from under live rules.
func (q *Queries) CountTaxClassMembers(ctx context.Context, taxClassID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTaxClassMembers, taxClassID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTaxClass = `-- name: GetTaxClass :one
SELECT id, name, metadata, created_at, updated_at, deleted_at FROM tax_class
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTaxClass(ctx context.Context, id string) (TaxClass, error) {
	row := q.db.QueryRow(ctx, getTaxClass, id)
	var i TaxClass
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertTaxClass = `-- name: InsertTaxClass :one

INSERT INTO tax_class (id, name, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, name, metadata, created_at, updated_at, deleted_at
`

type InsertTaxClassParams struct {
	ID        string
	Name      string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

// tax_class and tax_class_member queries. Every read filters on
// deleted_at IS NULL.
func (q *Queries) InsertTaxClass(ctx context.Context, arg InsertTaxClassParams) (TaxClass, error) {
	row := q.db.QueryRow(ctx, insertTaxClass,
		arg.ID,
		arg.Name,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i TaxClass
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertTaxClassMember = `-- name: InsertTaxClassMember :one
INSERT INTO tax_class_member (id, tax_class_id, product_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (product_id) WHERE deleted_at IS NULL
DO UPDATE SET tax_class_id = EXCLUDED.tax_class_id, updated_at = EXCLUDED.updated_at
RETURNING id, tax_class_id, product_id, created_at, updated_at, deleted_at
`

type InsertTaxClassMemberParams struct {
	ID         string
	TaxClassID string
	ProductID  string
	CreatedAt  pgtype.Timestamptz
}

// InsertTaxClassMember binds a product to a class.
//
// The product is the conflict target rather than the pair: a product belongs to
// AT MOST ONE class, so binding it again MOVES it instead of failing. An
// operator who reclassifies a product is doing the ordinary thing, and refusing
// it would make them delete the old membership first for no reason.
func (q *Queries) InsertTaxClassMember(ctx context.Context, arg InsertTaxClassMemberParams) (TaxClassMember, error) {
	row := q.db.QueryRow(ctx, insertTaxClassMember,
		arg.ID,
		arg.TaxClassID,
		arg.ProductID,
		arg.CreatedAt,
	)
	var i TaxClassMember
	err := row.Scan(
		&i.ID,
		&i.TaxClassID,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTaxClassMembers = `-- name: ListTaxClassMembers :many
SELECT id, tax_class_id, product_id, created_at, updated_at, deleted_at FROM tax_class_member
WHERE tax_class_id = $1 AND deleted_at IS NULL
ORDER BY product_id
`

func (q *Queries) ListTaxClassMembers(ctx context.Context, taxClassID string) ([]TaxClassMember, error) {
	rows, err := q.db.Query(ctx, listTaxClassMembers, taxClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxClassMember{}
	for rows.Next() {
		var i TaxClassMember
		if err := rows.Scan(
			&i.ID,
			&i.TaxClassID,
			&i.ProductID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxClassMembersByProducts = `-- name: ListTaxClassMembersByProducts :many
SELECT id, tax_class_id, product_id, created_at, updated_at, deleted_at FROM tax_class_member
WHERE product_id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY product_id
`

// ListTaxClassMembersByProducts resolves the class of EVERY product entering a
// calculation in one query; however many lines a cart has, the number of round
// trips stays constant (no N+1).
func (q *Queries) ListTaxClassMembersByProducts(ctx context.Context, productIds []string) ([]TaxClassMember, error) {
	rows, err := q.db.Query(ctx, listTaxClassMembersByProducts, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxClassMember{}
	for rows.Next() {
		var i TaxClassMember
		if err := rows.Scan(
			&i.ID,
			&i.TaxClassID,
			&i.ProductID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxClasses = `-- name: ListTaxClasses :many
SELECT id, name, metadata, created_at, updated_at, deleted_at FROM tax_class
WHERE deleted_at IS NULL
ORDER BY name, id
`

func (q *Queries) ListTaxClasses(ctx context.Context) ([]TaxClass, error) {
	rows, err := q.db.Query(ctx, listTaxClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxClass{}
	for rows.Next() {
		var i TaxClass
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTaxClass = `-- name: SoftDeleteTaxClass :one
UPDATE tax_class
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, metadata, created_at, updated_at, deleted_at
`

type SoftDeleteTaxClassParams struct {
	ID        string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteTaxClass(ctx context.Context, arg SoftDeleteTaxClassParams) (TaxClass, error) {
	row := q.db.QueryRow(ctx, softDeleteTaxClass, arg.ID, arg.DeletedAt)
	var i TaxClass
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTaxClassMember = `-- name: SoftDeleteTaxClassMember :one
UPDATE tax_class_member
SET deleted_at = $2, updated_at = $2
WHERE product_id = $1 AND deleted_at IS NULL
RETURNING id, tax_class_id, product_id, created_at, updated_at, deleted_at
`

type SoftDeleteTaxClassMemberParams struct {
	ProductID string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteTaxClassMember(ctx context.Context, arg SoftDeleteTaxClassMemberParams) (TaxClassMember, error) {
	row := q.db.QueryRow(ctx, softDeleteTaxClassMember, arg.ProductID, arg.DeletedAt)
	var i TaxClassMember
	err := row.Scan(
		&i.ID,
		&i.TaxClassID,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
