// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tax_region.sql

package taxdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTaxRegions = `-- name: CountTaxRegions :one
SELECT count(*) FROM tax_region
WHERE deleted_at IS NULL
  AND ($1::text = '' OR country_code = $1::text)
`

func (q *Queries) CountTaxRegions(ctx context.Context, countryCode string) (int64, error) {
	row := q.db.QueryRow(ctx, countTaxRegions, countryCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTaxRegion = `-- name: GetTaxRegion :one
SELECT id, country_code, province_code, parent_id, provider_id, metadata, created_at, updated_at, deleted_at FROM tax_region
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTaxRegion(ctx context.Context, id string) (TaxRegion, error) {
	row := q.db.QueryRow(ctx, getTaxRegion, id)
	var i TaxRegion
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.ProvinceCode,
		&i.ParentID,
		&i.ProviderID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaxRegionForUpdate = `-- name: GetTaxRegionForUpdate :one
SELECT id, country_code, province_code, parent_id, provider_id, metadata, created_at, updated_at, deleted_at FROM tax_region
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetTaxRegionForUpdate(ctx context.Context, id string) (TaxRegion, error) {
	row := q.db.QueryRow(ctx, getTaxRegionForUpdate, id)
	var i TaxRegion
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.ProvinceCode,
		&i.ParentID,
		&i.ProviderID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaxRegionsByIDs = `-- name: GetTaxRegionsByIDs :many
SELECT id, country_code, province_code, parent_id, provider_id, metadata, created_at, updated_at, deleted_at FROM tax_region
WHERE id = ANY($1::text[]) AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) GetTaxRegionsByIDs(ctx context.Context, ids []string) ([]TaxRegion, error) {
	rows, err := q.db.Query(ctx, getTaxRegionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxRegion{}
	for rows.Next() {
		var i TaxRegion
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.ProvinceCode,
			&i.ParentID,
			&i.ProviderID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTaxRegion = `-- name: InsertTaxRegion :one

INSERT INTO tax_region (id, country_code, province_code, parent_id, provider_id, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, country_code, province_code, parent_id, provider_id, metadata, created_at, updated_at, deleted_at
`

type InsertTaxRegionParams struct {
	ID           string
	CountryCode  string
	ProvinceCode *string
	ParentID     *string
	ProviderID   string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
}

// tax_region sorguları. Tüm okumalar deleted_at IS NULL süzer.
func (q *Queries) InsertTaxRegion(ctx context.Context, arg InsertTaxRegionParams) (TaxRegion, error) {
	row := q.db.QueryRow(ctx, insertTaxRegion,
		arg.ID,
		arg.CountryCode,
		arg.ProvinceCode,
		arg.ParentID,
		arg.ProviderID,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i TaxRegion
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.ProvinceCode,
		&i.ParentID,
		&i.ProviderID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTaxRegions = `-- name: ListTaxRegions :many
SELECT id, country_code, province_code, parent_id, provider_id, metadata, created_at, updated_at, deleted_at FROM tax_region
WHERE deleted_at IS NULL
  AND ($3::text = '' OR country_code = $3::text)
ORDER BY country_code, (parent_id IS NULL) DESC, id
LIMIT $1 OFFSET $2
`

type ListTaxRegionsParams struct {
	Limit       int32
	Offset      int32
	CountryCode string
}

func (q *Queries) ListTaxRegions(ctx context.Context, arg ListTaxRegionsParams) ([]TaxRegion, error) {
	rows, err := q.db.Query(ctx, listTaxRegions, arg.Limit, arg.Offset, arg.CountryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxRegion{}
	for rows.Next() {
		var i TaxRegion
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.ProvinceCode,
			&i.ParentID,
			&i.ProviderID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTaxRegions = `-- name: ResolveTaxRegions :many
SELECT id, country_code, province_code, parent_id, provider_id, metadata, created_at, updated_at, deleted_at FROM tax_region
WHERE deleted_at IS NULL
  AND country_code = $1::text
  AND (parent_id IS NULL OR province_code = $2::text)
ORDER BY (parent_id IS NULL), id
`

type ResolveTaxRegionsParams struct {
	CountryCode  string
	ProvinceCode string
}

// ResolveTaxRegions bir ülkenin kökünü ve (verilmişse) eyalet bölgesini TEK
// sorguda döner.
//
// Tek sorgu olması bilinçlidir: hesap yolu her sepet turunda çağrılır ve iki
// gidiş dönüş, bölge çözümünün maliyetini iki katına çıkarırdı. Eyalet kodu
// boş verildiğinde ikinci koşul hiçbir satırla eşleşmez (province_code CHECK
// gereği boş olamaz), yani yalnızca kök döner.
//
// Sıra EYALET ÖNCE'dir: hesap zinciri en ÖZELDEN genele yürür ve sıranın
// sorguda sabitlenmesi, servisin satırları yeniden sıralamak zorunda
// kalmamasını sağlar.
func (q *Queries) ResolveTaxRegions(ctx context.Context, arg ResolveTaxRegionsParams) ([]TaxRegion, error) {
	rows, err := q.db.Query(ctx, resolveTaxRegions, arg.CountryCode, arg.ProvinceCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxRegion{}
	for rows.Next() {
		var i TaxRegion
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.ProvinceCode,
			&i.ParentID,
			&i.ProviderID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTaxRegionTree = `-- name: SoftDeleteTaxRegionTree :many
UPDATE tax_region
SET deleted_at = $1, updated_at = $1
WHERE deleted_at IS NULL AND (id = $2::text OR parent_id = $2::text)
RETURNING id
`

type SoftDeleteTaxRegionTreeParams struct {
	DeletedAt pgtype.Timestamptz
	ID        string
}

// SoftDeleteTaxRegionTree bölgeyi ve (kök ise) alt bölgelerini birlikte siler.
//
// Ağaç iki seviye olduğu için "kendisi ya da çocuğu" koşulu tüm alt ağacı
// kapsar; özyinelemeli bir CTE gerekmez. Silinen kimlikler DÖNER: çağıran,
// oranları aynı işlem içinde bu kimliklerle siler. Bölge silinip oranları
// kalsaydı, aynı ülkeye açılan yeni bir bölge eski oranları görmez ama eski
// oranlar yetim satır olarak defterde durur ve rapor toplamlarını bozardı.
func (q *Queries) SoftDeleteTaxRegionTree(ctx context.Context, arg SoftDeleteTaxRegionTreeParams) ([]string, error) {
	rows, err := q.db.Query(ctx, softDeleteTaxRegionTree, arg.DeletedAt, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
