// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package cartdb

import (
	"context"
)

const bumpCartRevision = `-- name: BumpCartRevision :one
UPDATE carts
SET revision = revision + 1, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL AND completed_at IS NULL
RETURNING id, region_id, customer_id, email, currency_code, subtotal, discount_total, tax_total, shipping_total, total, revision, totals_revision, metadata, completed_at, created_at, updated_at, deleted_at
`

// BumpCartRevision sepetin şekil sayacını bir artırır; toplamları etkileyen
// her yapısal değişiklikten sonra AYNI işlemde çağrılır.
func (q *Queries) BumpCartRevision(ctx context.Context, id string) (Cart, error) {
	row := q.db.QueryRow(ctx, bumpCartRevision, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.CustomerID,
		&i.Email,
		&i.CurrencyCode,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.Total,
		&i.Revision,
		&i.TotalsRevision,
		&i.Metadata,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countCarts = `-- name: CountCarts :one
SELECT COUNT(*) FROM carts
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR customer_id = $1::text)
  AND ($2::text IS NULL OR region_id = $2::text)
  AND ($3::boolean IS NULL
       OR (completed_at IS NOT NULL) = $3::boolean)
`

type CountCartsParams struct {
	CustomerID *string
	RegionID   *string
	Completed  *bool
}

// CountCarts sayfalama zarfının toplam sayısını verir ve ListCarts ile AYNI
// filtreleri uygular; ikisi birlikte değiştirilmelidir.
//
// Toplam, satırlarla birlikte dönen bir pencere fonksiyonundan okunamaz:
// aralık dışı bir sayfada hiç satır dönmez, pencere değerlendirilmez ve toplam
// 0 görünürdü. Toplam sayfanın değil FİLTRENİN sayısıdır.
func (q *Queries) CountCarts(ctx context.Context, arg CountCartsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCarts, arg.CustomerID, arg.RegionID, arg.Completed)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCart = `-- name: CreateCart :one

INSERT INTO carts (
    id, region_id, customer_id, email, currency_code, metadata
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, region_id, customer_id, email, currency_code, subtotal, discount_total, tax_total, shipping_total, total, revision, totals_revision, metadata, completed_at, created_at, updated_at, deleted_at
`

type CreateCartParams struct {
	ID           string
	RegionID     string
	CustomerID   *string
	Email        *string
	CurrencyCode string
	Metadata     []byte
}

// carts sorguları.
//
// Her okuma deleted_at IS NULL süzer (plan Bölüm 8: silme yumuşaktır).
// Yazan sorgular ayrıca completed_at IS NULL şartı taşır: tamamlanmış sepet
// DEĞİŞMEZDİR ve bu, servis kontrolünün yanında ikinci kapıdır.
func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart,
		arg.ID,
		arg.RegionID,
		arg.CustomerID,
		arg.Email,
		arg.CurrencyCode,
		arg.Metadata,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.CustomerID,
		&i.Email,
		&i.CurrencyCode,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.Total,
		&i.Revision,
		&i.TotalsRevision,
		&i.Metadata,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCart = `-- name: GetCart :one
SELECT id, region_id, customer_id, email, currency_code, subtotal, discount_total, tax_total, shipping_total, total, revision, totals_revision, metadata, completed_at, created_at, updated_at, deleted_at FROM carts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCart(ctx context.Context, id string) (Cart, error) {
	row := q.db.QueryRow(ctx, getCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.CustomerID,
		&i.Email,
		&i.CurrencyCode,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.Total,
		&i.Revision,
		&i.TotalsRevision,
		&i.Metadata,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCartsByIDs = `-- name: GetCartsByIDs :many
SELECT id, region_id, customer_id, email, currency_code, subtotal, discount_total, tax_total, shipping_total, total, revision, totals_revision, metadata, completed_at, created_at, updated_at, deleted_at FROM carts
WHERE id = ANY ($1::text[]) AND deleted_at IS NULL
ORDER BY id
`

// GetCartsByIDs Query katmanının FetchByIDs çağrısını TEK turda karşılar;
// kimlik başına sorgu (N+1) yapılmaz.
func (q *Queries) GetCartsByIDs(ctx context.Context, ids []string) ([]Cart, error) {
	rows, err := q.db.Query(ctx, getCartsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.CustomerID,
			&i.Email,
			&i.CurrencyCode,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.TaxTotal,
			&i.ShippingTotal,
			&i.Total,
			&i.Revision,
			&i.TotalsRevision,
			&i.Metadata,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarts = `-- name: ListCarts :many
SELECT id, region_id, customer_id, email, currency_code, subtotal, discount_total, tax_total, shipping_total, total, revision, totals_revision, metadata, completed_at, created_at, updated_at, deleted_at FROM carts
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR customer_id = $1::text)
  AND ($2::text IS NULL OR region_id = $2::text)
  AND ($3::boolean IS NULL
       OR (completed_at IS NOT NULL) = $3::boolean)
ORDER BY created_at DESC, id DESC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListCartsParams struct {
	CustomerID *string
	RegionID   *string
	Completed  *bool
	RowOffset  int64
	RowLimit   int64
}

func (q *Queries) ListCarts(ctx context.Context, arg ListCartsParams) ([]Cart, error) {
	rows, err := q.db.Query(ctx, listCarts,
		arg.CustomerID,
		arg.RegionID,
		arg.Completed,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.CustomerID,
			&i.Email,
			&i.CurrencyCode,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.TaxTotal,
			&i.ShippingTotal,
			&i.Total,
			&i.Revision,
			&i.TotalsRevision,
			&i.Metadata,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCart = `-- name: LockCart :one
SELECT id, region_id, customer_id, email, currency_code, subtotal, discount_total, tax_total, shipping_total, total, revision, totals_revision, metadata, completed_at, created_at, updated_at, deleted_at FROM carts
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// LockCart sepeti işlem boyunca kilitler ve güncel hâlini döner.
//
// SEPETİ DEĞİŞTİREN HER AKIŞ BUNUNLA BAŞLAR. Kilit iki şeyi birden sağlar:
// eşzamanlı iki AddLineItem sepetin satırlarını bozamaz (ikincisi birincinin
// yazdığı satırı görür, yeni satır yerine adedi artırır) ve "tamamlanmış mı"
// kontrolü ile yazma arasına başka bir işlem giremez.
func (q *Queries) LockCart(ctx context.Context, id string) (Cart, error) {
	row := q.db.QueryRow(ctx, lockCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.CustomerID,
		&i.Email,
		&i.CurrencyCode,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.Total,
		&i.Revision,
		&i.TotalsRevision,
		&i.Metadata,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markCartCompleted = `-- name: MarkCartCompleted :one
UPDATE carts
SET completed_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL AND completed_at IS NULL
RETURNING id, region_id, customer_id, email, currency_code, subtotal, discount_total, tax_total, shipping_total, total, revision, totals_revision, metadata, completed_at, created_at, updated_at, deleted_at
`

// MarkCartCompleted sepeti tamamlanmış olarak damgalar.
//
// completed_at IS NULL şartı bilinçlidir: aynı sepeti ikinci kez tamamlamak
// hiçbir satırı etkilemez ve çağıran bunu ayırt edebilir. Servis kilidi zaten
// yarışı kapatır; buradaki şart doğrudan SQL ile yapılan bir müdahaleyi de
// kapsayan ikinci kapıdır.
func (q *Queries) MarkCartCompleted(ctx context.Context, id string) (Cart, error) {
	row := q.db.QueryRow(ctx, markCartCompleted, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.CustomerID,
		&i.Email,
		&i.CurrencyCode,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.Total,
		&i.Revision,
		&i.TotalsRevision,
		&i.Metadata,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteCart = `-- name: SoftDeleteCart :execrows
UPDATE carts
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCart(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCart, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCartContact = `-- name: UpdateCartContact :one
UPDATE carts
SET email       = $2,
    customer_id = $3,
    updated_at  = now()
WHERE id = $1 AND deleted_at IS NULL AND completed_at IS NULL
RETURNING id, region_id, customer_id, email, currency_code, subtotal, discount_total, tax_total, shipping_total, total, revision, totals_revision, metadata, completed_at, created_at, updated_at, deleted_at
`

type UpdateCartContactParams struct {
	ID         string
	Email      *string
	CustomerID *string
}

// UpdateCartContact sepetin e-postasını ve müşterisini MUTLAK değerle yazar.
//
// Misafir sepetin kayıtlı müşteriye devri ve ödeme adımında toplanan e-posta
// bu sorgudan geçer. Kimin kime devredilebileceği kararı SERVİSİNDİR (dolu bir
// müşteriyi başkasıyla değiştirmek reddedilir); buradaki sorgu yalnızca yazar.
func (q *Queries) UpdateCartContact(ctx context.Context, arg UpdateCartContactParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartContact, arg.ID, arg.Email, arg.CustomerID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.CustomerID,
		&i.Email,
		&i.CurrencyCode,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.Total,
		&i.Revision,
		&i.TotalsRevision,
		&i.Metadata,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCartTotals = `-- name: UpdateCartTotals :one
UPDATE carts
SET subtotal        = $2,
    discount_total  = $3,
    tax_total       = $4,
    shipping_total  = $5,
    total           = $6,
    totals_revision = $7,
    updated_at      = now()
WHERE id = $1 AND deleted_at IS NULL AND completed_at IS NULL
RETURNING id, region_id, customer_id, email, currency_code, subtotal, discount_total, tax_total, shipping_total, total, revision, totals_revision, metadata, completed_at, created_at, updated_at, deleted_at
`

type UpdateCartTotalsParams struct {
	ID             string
	Subtotal       int64
	DiscountTotal  int64
	TaxTotal       int64
	ShippingTotal  int64
	Total          int64
	TotalsRevision int64
}

// UpdateCartTotals workflow'un hesapladığı toplamları yazar ve toplamların
// hangi şekil için hesaplandığını damgalar.
func (q *Queries) UpdateCartTotals(ctx context.Context, arg UpdateCartTotalsParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartTotals,
		arg.ID,
		arg.Subtotal,
		arg.DiscountTotal,
		arg.TaxTotal,
		arg.ShippingTotal,
		arg.Total,
		arg.TotalsRevision,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.CustomerID,
		&i.Email,
		&i.CurrencyCode,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.ShippingTotal,
		&i.Total,
		&i.Revision,
		&i.TotalsRevision,
		&i.Metadata,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
