// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart_line_items.sql

package cartdb

import (
	"context"
)

const createLineItem = `-- name: CreateLineItem :one

INSERT INTO cart_line_items (
    id, cart_id, variant_id, title, quantity, unit_price, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, cart_id, variant_id, title, quantity, unit_price, subtotal, discount_total, tax_total, total, metadata, created_at, updated_at, deleted_at
`

type CreateLineItemParams struct {
	ID        string
	CartID    string
	VariantID string
	Title     string
	Quantity  int64
	UnitPrice int64
	Metadata  []byte
}

// cart_line_items sorguları.
//
// Satırlar her zaman SEPET KİLİDİ altında değiştirilir (bkz. LockCart); bu
// yüzden satırın kendisi ayrıca kilitlenmez. Kilit sırası tektir: önce sepet,
// sonra satır. Sıranın akışa göre değişmesi kilitlenme (deadlock) demektir.
func (q *Queries) CreateLineItem(ctx context.Context, arg CreateLineItemParams) (CartLineItem, error) {
	row := q.db.QueryRow(ctx, createLineItem,
		arg.ID,
		arg.CartID,
		arg.VariantID,
		arg.Title,
		arg.Quantity,
		arg.UnitPrice,
		arg.Metadata,
	)
	var i CartLineItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Title,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.Total,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLineItem = `-- name: GetLineItem :one
SELECT id, cart_id, variant_id, title, quantity, unit_price, subtotal, discount_total, tax_total, total, metadata, created_at, updated_at, deleted_at FROM cart_line_items
WHERE id = $1 AND cart_id = $2 AND deleted_at IS NULL
`

type GetLineItemParams struct {
	ID     string
	CartID string
}

func (q *Queries) GetLineItem(ctx context.Context, arg GetLineItemParams) (CartLineItem, error) {
	row := q.db.QueryRow(ctx, getLineItem, arg.ID, arg.CartID)
	var i CartLineItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Title,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.Total,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLineItemByVariant = `-- name: GetLineItemByVariant :one
SELECT id, cart_id, variant_id, title, quantity, unit_price, subtotal, discount_total, tax_total, total, metadata, created_at, updated_at, deleted_at FROM cart_line_items
WHERE cart_id = $1 AND variant_id = $2 AND deleted_at IS NULL
`

type GetLineItemByVariantParams struct {
	CartID    string
	VariantID string
}

// GetLineItemByVariant sepetteki bir varyantın YAŞAYAN satırını döner.
//
// AddLineItem bunu kullanır: aynı varyant ikinci kez eklendiğinde yeni satır
// açmak yerine var olanın adedini artırır (bkz. service.AddLineItem).
func (q *Queries) GetLineItemByVariant(ctx context.Context, arg GetLineItemByVariantParams) (CartLineItem, error) {
	row := q.db.QueryRow(ctx, getLineItemByVariant, arg.CartID, arg.VariantID)
	var i CartLineItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Title,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.Total,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLineItems = `-- name: ListLineItems :many
SELECT id, cart_id, variant_id, title, quantity, unit_price, subtotal, discount_total, tax_total, total, metadata, created_at, updated_at, deleted_at FROM cart_line_items
WHERE cart_id = $1 AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListLineItems(ctx context.Context, cartID string) ([]CartLineItem, error) {
	rows, err := q.db.Query(ctx, listLineItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartLineItem{}
	for rows.Next() {
		var i CartLineItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.VariantID,
			&i.Title,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.TaxTotal,
			&i.Total,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineItemsByCartIDs = `-- name: ListLineItemsByCartIDs :many
SELECT id, cart_id, variant_id, title, quantity, unit_price, subtotal, discount_total, tax_total, total, metadata, created_at, updated_at, deleted_at FROM cart_line_items
WHERE cart_id = ANY ($1::text[]) AND deleted_at IS NULL
ORDER BY cart_id, created_at, id
`

// ListLineItemsByCartIDs birden çok sepetin satırlarını TEK sorguda döner;
// sepet başına sorgu (N+1) yapılmaz.
func (q *Queries) ListLineItemsByCartIDs(ctx context.Context, cartIds []string) ([]CartLineItem, error) {
	rows, err := q.db.Query(ctx, listLineItemsByCartIDs, cartIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartLineItem{}
	for rows.Next() {
		var i CartLineItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.VariantID,
			&i.Title,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.TaxTotal,
			&i.Total,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLineItemQuantity = `-- name: SetLineItemQuantity :one
UPDATE cart_line_items
SET quantity = $3, updated_at = now()
WHERE id = $1 AND cart_id = $2 AND deleted_at IS NULL
RETURNING id, cart_id, variant_id, title, quantity, unit_price, subtotal, discount_total, tax_total, total, metadata, created_at, updated_at, deleted_at
`

type SetLineItemQuantityParams struct {
	ID       string
	CartID   string
	Quantity int64
}

func (q *Queries) SetLineItemQuantity(ctx context.Context, arg SetLineItemQuantityParams) (CartLineItem, error) {
	row := q.db.QueryRow(ctx, setLineItemQuantity, arg.ID, arg.CartID, arg.Quantity)
	var i CartLineItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Title,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.Total,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setLineItemTotals = `-- name: SetLineItemTotals :many
UPDATE cart_line_items AS li
SET unit_price     = v.unit_price,
    subtotal       = v.subtotal,
    discount_total = v.discount_total,
    tax_total      = v.tax_total,
    total          = v.total,
    updated_at     = now()
FROM ROWS FROM (
    unnest($2::text[]),
    unnest($3::bigint[]),
    unnest($4::bigint[]),
    unnest($5::bigint[]),
    unnest($6::bigint[]),
    unnest($7::bigint[])
) AS v (id, unit_price, subtotal, discount_total, tax_total, total)
WHERE li.id = v.id
  AND li.cart_id = $1
  AND li.deleted_at IS NULL
RETURNING li.id
`

type SetLineItemTotalsParams struct {
	CartID         string
	LineIds        []string
	UnitPrices     []int64
	Subtotals      []int64
	DiscountTotals []int64
	TaxTotals      []int64
	Totals         []int64
}

// SetLineItemTotals bir hesap turunun TÜM satır tutarlarını TEK deyimle yazar.
//
// Adet BURADA değişmez: adet sepet servisinin, tutarlar workflow'un verisidir.
// İkisinin ayrı sorgularda olması, bir hesaplama turunun adedi sessizce
// değiştirmesini yapısal olarak imkânsız kılar.
//
// Deyim TEKTİR çünkü satır başına bir UPDATE, sepetin KİLİDİ altında koşuyordu.
// Ölçüldü (yerel konteyner, TCP gidiş-dönüş ~30 µs, 100 satırlık sepet, kilit
// alındıktan SON YAZMA dönene kadar geçen süre, p50): satır başına UPDATE
// 8,0 ms, aynı UPDATE'ler tek boru hattında 3,0 ms, buradaki tek deyim
// 0,55 ms. Kazancın yalnızca bir bölümü gidiş-dönüşten gelir; geri kalanı
// deyim başına ayrıştırma/planlama maliyetidir ve onu ancak TEK deyim siler —
// boru hattı (pgx batch, sqlc :batchexec) kazancın üçte ikisinde kalırdı.
//
// ÖLÇÜM NEYİ İÇERMİYOR: harness'ın konteyneri fsync=off ile koşar
// (testcontainers-go postgres modülü bunu sabit yazar), yani yukarıdaki süreler
// kilidin altındaki YAZMA EVRESİDİR, ardından gelen commit'in WAL flush'ı
// DEĞİLDİR. Flush da aynı kilidin altındadır — kilit commit'te bırakılır — ve
// bu değişiklik ona DOKUNMAZ: kalıcı bir kümede (fsync=on, aynı makine)
// ölçüldü, 1 satır güncelleyen commit de 100 satır güncelleyen commit de
// 6,2 ms. Yani gerçek kilit süresi ~14,2 ms'den ~6,8 ms'ye iner: kazanç 14 kat
// değil ~2 kattır. 14 kat, yazma evresinin kendi içindeki orandır ve deyim
// sayısı hakkındaki iddia odur.
//
// Eşleştirme dizilerin SIRASIYLA yapılır: v.id ile aynı indeksteki tutarlar
// aynı satıra gider. Diziler tek bir döngüde kurulur (bkz. repository), bu
// yüzden uzunlukları yapısal olarak eşittir; eşit olmasalardı ROWS FROM kısa
// diziyi NULL ile doldurur ve NOT NULL kısıtı deyimi düşürürdü — sessiz bir
// yanlış tutar değil, gürültülü bir hata.
//
// ROWS FROM (unnest(a), unnest(b), ...) çok argümanlı unnest(a, b, ...) ile
// aynı şeydir; sqlc çok argümanlı biçimi ayrıştıramadığı için bu biçim yazıldı.
// Ölçüldü: ikisi arasında fark yok (100 satır, p50 545 µs / 555 µs).
//
// cart_id JOIN'in değil WHERE'in parçasıdır: başka sepetin satırı hiçbir
// dizide eşleşemez. Eşleşmeyen kimlik RETURNING'de görünmez ve çağıran yazılan
// kimlikleri istenenlerle karşılaştırıp turu düşürür.
//
// Tekrarlanan kimlik verilmez (servis reddeder): UPDATE ... FROM aynı hedef
// satır birden çok kaynak satırla eşleştiğinde HANGİ kaynağın kazandığını
// tanımlamaz.
func (q *Queries) SetLineItemTotals(ctx context.Context, arg SetLineItemTotalsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, setLineItemTotals,
		arg.CartID,
		arg.LineIds,
		arg.UnitPrices,
		arg.Subtotals,
		arg.DiscountTotals,
		arg.TaxTotals,
		arg.Totals,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLineItem = `-- name: SoftDeleteLineItem :execrows
UPDATE cart_line_items
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND cart_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLineItemParams struct {
	ID     string
	CartID string
}

func (q *Queries) SoftDeleteLineItem(ctx context.Context, arg SoftDeleteLineItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLineItem, arg.ID, arg.CartID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteLineItemsByCart = `-- name: SoftDeleteLineItemsByCart :exec
UPDATE cart_line_items
SET deleted_at = now(), updated_at = now()
WHERE cart_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteLineItemsByCart(ctx context.Context, cartID string) error {
	_, err := q.db.Exec(ctx, softDeleteLineItemsByCart, cartID)
	return err
}
