// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart_addresses.sql

package cartdb

import (
	"context"
)

const listCartAddresses = `-- name: ListCartAddresses :many
SELECT id, cart_id, address_type, source_address_id, first_name, last_name, company, address_1, address_2, city, province, postal_code, country_code, phone, metadata, created_at, updated_at, deleted_at FROM cart_addresses
WHERE cart_id = $1 AND deleted_at IS NULL
ORDER BY address_type
`

func (q *Queries) ListCartAddresses(ctx context.Context, cartID string) ([]CartAddress, error) {
	rows, err := q.db.Query(ctx, listCartAddresses, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartAddress{}
	for rows.Next() {
		var i CartAddress
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.AddressType,
			&i.SourceAddressID,
			&i.FirstName,
			&i.LastName,
			&i.Company,
			&i.Address1,
			&i.Address2,
			&i.City,
			&i.Province,
			&i.PostalCode,
			&i.CountryCode,
			&i.Phone,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCartAddressesByCart = `-- name: SoftDeleteCartAddressesByCart :exec
UPDATE cart_addresses
SET deleted_at = now(), updated_at = now()
WHERE cart_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCartAddressesByCart(ctx context.Context, cartID string) error {
	_, err := q.db.Exec(ctx, softDeleteCartAddressesByCart, cartID)
	return err
}

const upsertCartAddress = `-- name: UpsertCartAddress :one

INSERT INTO cart_addresses (
    id, cart_id, address_type, source_address_id,
    first_name, last_name, company,
    address_1, address_2, city, province, postal_code, country_code, phone,
    metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (cart_id, address_type) WHERE deleted_at IS NULL
DO UPDATE SET
    source_address_id = EXCLUDED.source_address_id,
    first_name        = EXCLUDED.first_name,
    last_name         = EXCLUDED.last_name,
    company           = EXCLUDED.company,
    address_1         = EXCLUDED.address_1,
    address_2         = EXCLUDED.address_2,
    city              = EXCLUDED.city,
    province          = EXCLUDED.province,
    postal_code       = EXCLUDED.postal_code,
    country_code      = EXCLUDED.country_code,
    phone             = EXCLUDED.phone,
    metadata          = EXCLUDED.metadata,
    updated_at        = now()
RETURNING id, cart_id, address_type, source_address_id, first_name, last_name, company, address_1, address_2, city, province, postal_code, country_code, phone, metadata, created_at, updated_at, deleted_at
`

type UpsertCartAddressParams struct {
	ID              string
	CartID          string
	AddressType     string
	SourceAddressID *string
	FirstName       *string
	LastName        *string
	Company         *string
	Address1        *string
	Address2        *string
	City            *string
	Province        *string
	PostalCode      *string
	CountryCode     *string
	Phone           *string
	Metadata        []byte
}

// cart_addresses queries.
//
// There is at most one LIVING address of each kind (shipping/billing) per
// cart; the constraint lives in the cart_addresses_cart_type_uniq index.
// UpsertCartAddress writes the address; if one of the same kind exists it is
// OVERWRITTEN.
//
// The conflict target is a partial unique index, so the WHERE clause must be
// EXACTLY the same as the index's; otherwise PostgreSQL cannot infer the index
// and the query errors out.
func (q *Queries) UpsertCartAddress(ctx context.Context, arg UpsertCartAddressParams) (CartAddress, error) {
	row := q.db.QueryRow(ctx, upsertCartAddress,
		arg.ID,
		arg.CartID,
		arg.AddressType,
		arg.SourceAddressID,
		arg.FirstName,
		arg.LastName,
		arg.Company,
		arg.Address1,
		arg.Address2,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.CountryCode,
		arg.Phone,
		arg.Metadata,
	)
	var i CartAddress
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.AddressType,
		&i.SourceAddressID,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Address1,
		&i.Address2,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.CountryCode,
		&i.Phone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
